### PR TITLE
Changing commons.send_request to self._request in sdss module

### LINKED ISSUE #582: Make use of older DRs for sdss actually work
The version merged in #545 has some xfails because older DRs (not dr12) aren't working.  That needs to be fixed to get older DRs to work right.

Either @bsipocz or @parejkoj were working on this, I think?

### LINKED ISSUE #583: MockResponse needs a way to return a json
In sdss.field_names.get_field_info(), we call _columns_json_to_table(qryres.json()), but a MockResponse doesn't have a json method. Without that, most of the new tests blow up with Errors.

### PR DESCRIPTION
**Pull request by bsipocz**
Basically most of the tests are failing as it tries to do remote connection when ``remote_data=False``, but also many tests fail went ``remote_data=True``. 

I'll investigate tomorrow.

Fixes #583
Closes #582 (as it's merged into this to resolve conflicts)

### CODE REVIEW

**Comment by keflavich** [comment]
@bsipocz this is because the sdss tests monkeypatch commons instead of `BaseQuery`

**Comment by parejkoj** [comment]
Oh, I was in the middle of working on this when I had to leave yesterday. I'll see if I can commit the changes I'd made: I still hadn't gotten back to tests passing, in part because it's self._request is not a drop-in replacement for send_request.

**Comment by bsipocz** [comment]
Ohh, based on the gitter stuff I thought this is the part I was supposed to work on.

**Comment by parejkoj** [comment]
In order to get some other tests to pass, I had to start on this.

**Comment by bsipocz** [comment]
@keflavich - I've cherry-picked the json related stuff from your alma branch here. We should double check before merging either of these PRs whether the other one is merged yet or not to avoid unnecessary mess.

**Comment by bsipocz** [comment]
@keflavich - If travis passes this is good to go I think. Could you give it a review as you know the differences between the old and new ``request`` infrastructures. 

However I would like somehow include the parallel work @parejkoj did. Should I just cherry-pick his commits from ``parejkoj/make_drs_work`` ? There are a loads of conflicts between that and this that will cause a painful rebase otherwise.

**Comment by bsipocz** [comment]
Also my bad that I've started with a PEP8 clean-up as my editor was blood red due to trivial stuff. Shouldn't have done that as it'll also add possible conflicts...

**Comment by keflavich** [comment]
@bsipocz - looks fine to me.  I read over the core changes but didn't look closely at the tests.  One comment - it would be nice to have `dr` renamed to `datarelease` or `data_release` within the source code and possible as a kwarg, perhaps supporting the optional short version `dr`, for readability.  But that's up to you.

In terms of how to merge it: could you merge https://github.com/parejkoj/astroquery/tree/make_drs_work into this branch on your machine, then push it into this branch before merging both?  `cherry-pick`ing involves a lot of history rewriting, which would be better to avoid if possible.

**Comment by bsipocz** [comment]
OK, I'll try to do a merge then, but I guess it will be super messy.

**Comment by keflavich** [comment]
Yeah, I don't really know what other option there is - cherry picking should be equally messy, no?

**Comment by bsipocz** [comment]
It's easier to deal with, I guess (like skipping the changes that both he and I cherry-picked from your alma branch). Another option is to rebase mine on top of his branch, thus keeping all of his commits in the history, too.

**Comment by keflavich** [comment]
OK.  It's up to you, then.  I'll deal with whatever mess leaks into the ALMA branch; it should be small.

**Comment by bsipocz** [comment]
Yes, I'm not worried about that. This whole issue was just badly organized, I thought that we clearly came up with distinct sub parts to work on, apparently we didn't.

**Comment by parejkoj** [comment]
Sorry about that. I just started digging in, and ended up needing to touch more things than I thought, and then I had to catch a train before I'd committed. I'll take the blame here.

**Comment by bsipocz** [comment]
well, by that time I've already touched many things, but left unfinished as
it got rather late on this side of the pond :)
Now I'm close to iron out the conflicts and fix the newly failed tests.

**Comment by bsipocz** [comment]
OK, so cherry-picking would have had the advantage to avoid the json stuff being included in the history several times. The version form @parejkoj was incomplete, but got to overwrite the one in the original branch, thus the py3 test fails. 
Now it should be fixed and if travis gives the green light, should be ready to be merged.

**Comment by bsipocz** [comment]
Thanks @keflavich. I've forgot to address the ``dr`` vs ``data_release`` naming thing here, but will open a new PR for it.

**Pull request merged**
