### PR TITLE
FIX: switching to https for sdss to avoid query issues

### LINKED ISSUE #2644: BUG: SDSS KeyNotFoundException for query_region
Hi, I am having the same problem with:
astroquery 0.4.7.d
python 3.10.9
numpy 1.23.5.

Using (for example) the example in the doc, as any other call:

```
from astropy.coordinates import SkyCoord
from astroquery.sdss import SDSS

pos = SkyCoord('0h8m05.63s +14d50m23.3s', frame='icrs')
xid = SDSS.query_region(pos, spectro=True)


Traceback (most recent call last):

  File "/var/folders/m2/32fmbv0s3hg46rj5ccx2r5g40000gn/T/ipykernel_49747/284473386.py", line 2, in <module>
    xid = SDSS.query_region(pos, spectro=True)

  File "/Users/filippo/opt/anaconda3/envs/Py310/lib/python3.10/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)

  File "/Users/filippo/opt/anaconda3/envs/Py310/lib/python3.10/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)

  File "/Users/filippo/opt/anaconda3/envs/Py310/lib/python3.10/site-packages/astroquery/sdss/core.py", line 905, in _parse_result
    arr = np.atleast_1d(np.genfromtxt(io.BytesIO(response.content),

  File "/Users/filippo/opt/anaconda3/envs/Py310/lib/python3.10/site-packages/numpy/lib/npyio.py", line 2291, in genfromtxt
    raise ValueError(errmsg)

ValueError: Some errors were detected !
    Line #3 (got 3 columns instead of 1)
    Line #5 (got 3 columns instead of 1)
    Line #6 (got 4 columns instead of 1)
    Line #8 (got 4 columns instead of 1)
    Line #12 (got 4 columns instead of 1)
    Line #15 (got 6 columns instead of 1)
    Line #17 (got 4 columns instead of 1)
    Line #21 (got 3 columns instead of 1)
    Line #31 (got 3 columns instead of 1)
```

It works fine on another machine running python 3.8 and astroquery 0.4.3

### PR DESCRIPTION
**Pull request by bsipocz**
To fix #2644

Thanks @weaverba137 for the suggestion, this does the trick.

### CODE REVIEW

**Comment by bsipocz** [comment]
Before merging, we need to make sure to pay a bit closer attention on the test coverage for older DRs, and whether everything keeps working for those.

**Comment by weaverba137** [comment]
The changes look good, but here's some follow up from the SDSS data team that might be worth thinking about.

> The load balancers are setup with a standard 301 redirect to https when clients connect using http. However, most http clients see 301 redirects and ( surprisingly ) drop the body, headers, and arguments of the original request ( and sometimes change their HTTP method ). This is why when you queried over http, you were getting a non-existent key stack trace: your original arguments were not being forwarded to a server after a 301 redirect.

Clearly if the query still works, then the payload is not being dropped, but it might even be worth testing both http and https separately to be absolutely sure. Maybe for only a few releases, so it doesn't add a huge number of tests.

**Comment by bsipocz** [comment]
This is eyeopening, thanks for sharing their response.

> Clearly if the query still works, then the payload is not being dropped, but it might even be worth testing both http and https separately to be absolutely sure. Maybe for only a few releases, so it doesn't add a huge number of tests.

if we change the default url for https, then I think we'll be good without testing http behaviour. If a user changes the default, they are on their own to make sure that request actually works and makes sense 🤷‍♀️

**Review by pllim — APPROVED** [review]
Makes sense. Thanks!

**Comment by pllim** [comment]
Thanks! Any plans to push a pre-release out to PyPI?

**Comment by bsipocz** [comment]
Sure, I'll merge a few more things and push one at the end of the day.

**Comment by pllim** [comment]
I can confirm that the error went away downstream. Thanks again!

**Pull request merged**
