### PR TITLE
ESASky test updates

### PR DESCRIPTION
**Pull request by imbasimba**
I'll add some spectra tests and bug fixes next week, but this should be enough to get all tests to pass.

The test of the rst file is skipped when I try to run it locally. Am I missing something obvious to be able to analyze the code & documentation locally? (i.e. looking for incorrect white spaces etc)

### CODE REVIEW

**Comment by bsipocz** [comment]
If you temporarily remove the `doctest-skip-all` from the docs, the testrunner should be able to pick it up. To build the docs, with warnings on, use `python setup.py build_docs -W` you will need `sphinx-astropy` installed

**Comment by bsipocz** [comment]
Btw we're currently working on with our Outreachy intern, @tinumide, to enable doctesting on the narrative docs.

**Comment by imbasimba** [comment]
Thanks @bsipocz, that is very useful!

Another question: When running `test -P esasky -R` with `doctest-skip-all` removed, the code-blocks are run and the output compared with what's written in the code block. This is fine in most cases, but some of the calls have a lot of repetetive output, which I'd rather not add to the doc code block. Is there any elegant way to deal with this situation where I could also run the test on the doc?
Example: row 253 on esasky.rst

**Comment by imbasimba** [comment]
This PR is now ready for final review

**Comment by bsipocz** [comment]
I've rebased this to pick up the newly enable CI, and removed the changelog entry.

>Another question: When running test -P esasky -R with doctest-skip-all removed, the code-blocks are run and the output compared with what's written in the code block. This is fine in most cases, but some of the calls have a lot of repetetive output, which I'd rather not add to the doc code block. Is there any elegant way to deal with this situation where I could also run the test on the doc?
Example: row 253 on esasky.rst

There are two, maybe three doctestplus directives that can be used for these cases: `IGNORE_OUTPUT`, `SKIP`, or `ELLIPSIS`, all to be used in line as e.g. ``# doctest: +IGNORE_OUTPUT``, in which case the line will run, but all output will be ignored. `SKIP` also skips the line, so if you use that, the rest of the code snippets cannot rely on that line. And the `ELLIPSIS` will cover the current version of the docs, when you only include the a partial output.

**Review by bsipocz — APPROVED** [review]
This all looks good, thank you!

**Pull request merged**
