### PR TITLE
Refactor the Gallery

### PR DESCRIPTION
**Pull request by keflavich**
See related #863.

I think we want some sort of Gallery to show useful interactions between
astroquey and other components of the astropy environment, and in general have
a place to store neat one-off examples, but the existing gallery suffers
from several problems noted in the other Issue, including:

 * The current version is not tested
 * There is no value added over individual modules' documentation for most
 of the examples
 * A more suitable home is the astropy-tutorials repository

### CODE REVIEW

**Comment by keflavich** [comment]
(this is incomplete)

**Comment by keflavich** [comment]
[The current test failure is unrelated:](https://travis-ci.org/astropy/astroquery/jobs/411038394#L3391)
```
E   ImportError: numpy.core.multiarray failed to import
```

**Comment by keflavich** [comment]
Yay.  @bsipocz, you want to have one last glance & merge?

**Comment by bsipocz** [comment]
@keflavich - Ideally all these examples need to be tested in the remote tests. But as I remember we have issues with running tests on included python scripts. 

Anyway, that really is a separate issue, and this PR makes the current situation better, so I'm all for merging this now.

**Comment by bsipocz** [comment]
Thanks!

**Pull request merged**
