### PR TITLE
Fix for #1647: jplhorizons upstream change

### PR DESCRIPTION
**Pull request by mommermi**
fixes error caused by upstream changes as documented in #1647 

no changes to API, no changelog entry should be necessary

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @mommermi! I'm ambivalent with the changelog, it doesn't need it as you stated the changes are internal, but users might be confused why the old version is not working any more when seamlessly nothing has happened to the module. So I would add one entry like we did for 0.4, and the merge this.

**Comment by bsipocz** [comment]
I need to fix the (unrelated) issues with the deployment. Hopefully a release will hit pypi after that, over the weekend or early next week.

**Comment by Olivier-Lakoue** [comment]
Hi mommermi,

Hope you're well.
I leave in France and i'm a new user of Astroquery and it's seems to be a very great api.

I find this post because i also have the bug "KeyError: 'ObsSub-LON'" whn using ephemerides() function.

I saw you solved this bud and I've updaded my astroquery to 0.4 version but the bug stills exist ...
I think i made a mistake with the upgrade, how can i do to make it works correctly ?

Thanks for your help.
Olivier.

**Comment by bsipocz** [comment]
@Olivier-Lakoue - Please upgrade your astroquery with `pip install --pre -U astroquery`

**Comment by Olivier-Lakoue** [comment]
Hi bsipocz,

Thanks for your help, i've upgrade as mentionned and it's ok.

This package is very greats, many thanks !!

**Pull request merged**
