### PR TITLE
yet another fix to ALMA's https handling

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by keflavich** [comment]
argh, this was NOT supposed to be opened.

**Comment by keflavich** [comment]
I can't seem to attach this PR to issue #827, and I don't know why.

```
$ hub pull-request -b astropy:master -h keflavich:alma_https -i 827
Error creating pull request: Unprocessable Entity (HTTP 422)
fork_collab Fork collab can't be granted by someone without permission
```

**Comment by bsipocz** [comment]
@keflavich - I have no idea what goes wrong, but it looks weird. I always used ``issue2pr.py`` from ``astropy-tools`` in the rare occasions when I converted an issue to a PR.

**Comment by keflavich** [comment]
I didn't know about that, I'll check it next time.

Anyway, the fix works for `--remote-data` locally, so I'm merging.

**Pull request merged**
