### PR TITLE
Reduce running time for MAST doctests

### PR DESCRIPTION
**Pull request by snbianco**
Adjusted some of the queries in MAST documentation to reduce the running time of the doctests. Reduced from ~9.5 minutes to ~3 minutes.

I also reformatted some of the queries to be more readable and updated outputs.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
These look good, thanks for making the rearrangements to make these faster.

**Comment by bsipocz** [comment]
@snbianco - do I need to wait for sign-off from @dr-rodriguez or @astrojimig when you CC them, or that is more of a FYI shout out to them?

**Comment by dr-rodriguez** [comment]
Sam let us know during out standup about this change so this is more of an FYI for us. Thanks!

**Comment by bsipocz** [comment]
Thanks Sam!

**Pull request merged**
