### PR TITLE
parse xmatch tables if they have duplicate column headings

### PR DESCRIPTION
**Pull request by keflavich**
We discovered some errors where duplicate column names broke astropy's ascii reader (related to https://github.com/astropy/astropy/issues/5374).  We circumvent this by appending _1, _2, etc. to the column names.

cc @tboch

### CODE REVIEW

**Comment by keflavich** [comment]
example:
```
In [11]: colnames = ['a','a','a','b','b','c','d','e','e']

In [12]: %paste
        for cn in colnames:
            if colnames.count(cn) > 1:
                ii = 1
                while colnames.count(cn) > 0:
                    colnames[colnames.index(cn)] = cn + f"_{ii}"
                    ii += 1
## -- End pasted text --

In [13]: colnames
Out[13]: ['a_1', 'a_2', 'a_3', 'b_1', 'b_2', 'c', 'd', 'e_1', 'e_2']
```

**Comment by keflavich** [comment]
Coverage increased, I don't know why codecov/patch is red.  Merging, since this one is pretty straightforward and passed some additional tests & sanity checks we ran this afternoon.

**Comment by bsipocz** [comment]
This isn't exactly the proposed solution that we came up with in https://github.com/astropy/astroquery/pull/1375 and related discussions, but I suppose having some workaround sooner rather than later is good.

**Comment by bsipocz** [comment]
Also, I suppose this will have some consequences for the users, so will ultimately need docs and a changelog.

**Comment by keflavich** [comment]
Oh man, I totally forgot about that issue.  Anyway, agreed that switching to VO output would be better long-term.

**Comment by bsipocz** [comment]
yes, that was one where it all started with an innocent looking issue, but then there were layers and layers of new upstream issues were triggered by the solution to the point that I didn't have enough time to finish it off. But it's not completely forgotten, hopefully I'll get back to it as some reasonable time.

**Pull request merged**
