### PR TITLE
Removing imp usage

### PR DESCRIPTION
**Pull request by bsipocz**
This should take care of the recent travis failures.

I think this reload of requests is not needed any more, at least this PR doesn't seem to cause much troubles with the remote tests.

### CODE REVIEW

**Comment by keflavich** [comment]
The `imp`s apparently aren't needed, but why were they causing trouble?  Is `imp` deprecated now?

**Comment by bsipocz** [comment]
Yes, imp is deprecated since 3.4. Locally I have 3.7.4 where it doesn't cause issues, but on travis on 3.7.5 it started to.

**Comment by bsipocz** [comment]
There is a related looking failure with astropy-dev,  I suspect the reasons may lie with the recent changes in astropy.utils 

cc-ing  @pllim in case she immediately can see the root cause. If not, I'll try to come back for a more detailed look in the evening.

**Comment by pllim** [comment]
`ValueError: unknown url type: '/tmp/astroquery-test-vmkjn0vh/lib/python3.7/site-packages/astroquery/utils/tests/../../sdss/tests/data/emptyfile.fits'` -- Seems like somehow `astropy.utils.data.get_readable_fileobj` is attempting to download the file after mistakenly thinking it is a form of URL. But I cannot reproduce this behavior locally. I'll post more if I find something else.

```python
>>> import urllib
>>> path = '/tmp/astroquery-test-vmkjn0vh/lib/python3.7/site-packages/astroquery/utils/tests/../../sdss/tests/data/emptyfile.fits'
>>> url = urllib.parse.urlparse(path)
>>> # From this check, it should have treated the file as a local file...
>>> url.scheme.lower() in ['http', 'https', 'ftp', 'sftp', 'ssh', 'file']
False
```

**Comment by pllim** [comment]
Ah, so you monkeypatched it! Now it makes sense:

https://github.com/astropy/astroquery/blob/c96d5f4f306eee44f59de96e77d6f34bc4d784bb/astroquery/utils/tests/test_utils.py#L413

Unfortunately, I don't know the intention of this patching, so I am not sure how to fix it. But the bottom line is, you need to patch it so that `astropy.utils.data.get_readable_fileobj` will not try to download it. The whole machinery of `astropy.utils.data` was refactored in astropy/astropy#9182

**Comment by bsipocz** [comment]
@keflavich - we need to figure this out this caching question for the astropy release. Could you please have a look?

**Comment by bsipocz** [comment]
(if you prefer we can handle it in a new PR/issue, too as it's totally unrelated to this one, but I don't mind to deal with both here).

**Comment by keflavich** [comment]
What caching question?  Do I need to open a particular travis build to see it?

**Comment by pllim** [comment]
@keflavich , https://github.com/astropy/astroquery/pull/1588#issuecomment-555187571

**Comment by pllim** [comment]
FWIW, I vote you merge this and handle the astropy dev issue separately. Thanks!

**Comment by bsipocz** [comment]
Yeah, I suppose we can do that. Would you mind opening an issue for it? Arguably I didn't follow the cache changes, so have little grasps atm of what's going on behind the scene.

**Pull request merged**
