### PR TITLE
Query SIMBAD/Vizier by MOCs

### PR DESCRIPTION
**Pull request by bmatthieu3**
[MOCs](https://mocpy.readthedocs.io/en/latest/) (Multi-order coverage maps) are a type of region describing arbitrary surfaces on the sky. It corresponds to a set of HEALPix cells (that can be of different orders).

This PR gives the user the possibility to query Simbad (or any Vizier catalog) by a MOC object (coming from [mocpy](https://mocpy.readthedocs.io/en/latest/)) i.e. returning all the observations in a given MOC.

### CODE REVIEW

**Comment by bsipocz** [comment]
@bmatthieu3 - thank you! I'll need to do a proper review, but first just a topic for discussion. Rather than adding a totally new method, what about modifying `query_region` to accept a MOC object as input?

**Comment by bmatthieu3** [comment]
@bsipocz - the API of query_region takes a mandatory ``coordinates`` parameter that refers to a center position and can either be associated with an optional radius (in case of a cone) or an optional width and height (in case of a rectangle). But a MOC is a whole type of region so I find it not very explicit to pass it in place of the `coordinates` param (in the case we do not want to break the current API).
I like the fact to define a new `query_moc_region`:
* it does not break the current API
* it implies for the user that a MOC is a new type of region. So if the user is curious he can look to the astroquery documentation that shows the MOC of SDSS and gives links to mocpy.

A better solution in a long term future would be for ``query_region`` to take regions objects (CircleSkyRegion or PolygonSkyRegion or a MOC) but this would break the existent API.

**Comment by bsipocz** [comment]
@bmatthieu3 - yes, my proposal is that `coordinates` could accept either a `SkyCoord` just as it does atm, or a MOC. Providing a coordinate is such a clean API that we may not want to remove that case, but certainly could extend it.

**Comment by bmatthieu3** [comment]
> yes, my proposal is that coordinates could accept either a SkyCoord just as it does atm, or a MOC

But a MOC is not a coordinate, it is a region such as a CircleSkyRegion or a PolygonSkyRegion. That's why I find it weird to pass a MOC object in the ``coordinates`` parameter.

**Comment by bmatthieu3** [comment]
@bsipocz - I made the tests pass. Concerning the API my concern is just that the `coordinates` param name does not correspond to what a spatial coverage is. `region` is more appropriate. Maybe we could add a second new method **query_skyregion** that accepts only one let's say `region` param that can be either a PolygonSkyRegion, CircleSkyRegion (from astropy/regions) or a MOC (from mocpy) object and let the current **query_region** as it is ?

For the moment what I did here is adding a new **query_moc_region** method taking a `moc` param.

**Comment by keflavich** [comment]
I see the issue here.  I think this is a good motivation to expand our API.  Change the API from `query_region(coordinate, radius=...)` to `query_region(coordinate_or_region)` to allow the first, required parameter to be either a coordinate (the current default) or a region (something that should be supported).  It will take some time to refactor the rest of astroquery to support the region-based API, but that seems like the right way forward.

**Comment by ManonMarchand** [comment]
Looks like this API change won't happen. What about a `query_by_moc` method then? This way we don't touch the generic `query_region` of the other modules.

**Comment by bsipocz** [comment]
Hmm, sorry for letting this fall through the cracks.

I think having just one, `query_region` is a more user friendly way, and then it can either take a coordinate or a moc as first parameter. (basically looking at the user perspective, a `query_region` is a wide search around a position, and whether that position is specified as a coordinate+radius/box/polygon or as a moc is really an implementation detail. So I don't think it needs to be a separate method. (And anyway, it's a good inspiration of for other modules to accept moc as input, though I don't see when/how implementations for that will happen)).

**Comment by ManonMarchand** [comment]
After discussions with @bmatthieu3 and @fxpineau , this PR should be closed as we changed the way we want SIMBAD and VizieR to be interrogated by MOCs.

**However  I'm still confused about the API:**

The signature would be something like `Simbad.query_region(region=None, coordinates=None, radius=None, equinox=2000.0, epoch='J2000')`?
And then we use if clauses to determine if the region is given by `region` or by `coordinates/radius/equinox/epoch`?

I think the region parameter could support MOCs , `astropy.regions`, and maybe also STCs.

**Comment by bsipocz** [comment]
> The signature would be something like Simbad.query_region(region=None, coordinates=None, radius=None, equinox=2000.0, epoch='J2000')?

That could work, but I would either make all of the arguments mandatory keyword args, or have `coordinates` as the first argument while everything else is keyword only. That way it would be a better match of the `query_region` methods of the other modules. But honestly, making everything keyword only is probably a way to go to eliminate any error in user assumptions, with the added benefit that the order wouldn't matter then.

> I think the region parameter could support MOCs , astropy.regions, and maybe also STCs.

yes, that sounds like a solid plan, and support can be built up incrementally if needed.

**Comment by bsipocz** [comment]
Closing as requested.

**Pull request closed without merging**
