### PR TITLE
Refactor: Make NIST keyword only

### PR DESCRIPTION
**Pull request by nkphysics**
Is this the type of refactoring you had in mind with #1746 ?

I tried to go off of the already merged PR's listed in #1746, so I now a changlog entry is needed too that I'll squash into this.

### CODE REVIEW

**Comment by bsipocz** [comment]
> Is this the type of refactoring you had in mind with https://github.com/astropy/astroquery/issues/1746 ?

Yes. But tests (and mocks for tests) should be updated, too.

The main parts is to make these changes to the public API. Whether it's done to the private methods (as you did it here), it's not that critical, but then it doesn't hurt either.

**Comment by nkphysics** [comment]
> > Is this the type of refactoring you had in mind with #1746 ?
> 
> Yes. But tests (and mocks for tests) should be updated, too.
> 
> The main parts is to make these changes to the public API. Whether it's done to the private methods (as you did it here), it's not that critical, but then it doesn't hurt either.

Just seeing I only ran the remote stuff. I'm hopping on getting that fixed up.

**Comment by nkphysics** [comment]
I know these changes break the NIST docs, do you want me to also fix those up in a seperate commit?

**Comment by bsipocz** [comment]
Yeap, newly breaking docs should be fixed, too.

**Review by ceb8 — APPROVED** [review]
Looks good to me.

**Review by bsipocz — APPROVED** [review]
Thanks! I'll add a changelog to this and go ahead with the merge.

**Pull request merged**
