### PR TITLE
Make utils and utis/tap kwargs keyword only

### PR DESCRIPTION
**Pull request by nkphysics**
This PR is to address #1746 by making kwargs keyword only for utils and utils/tap.

As I expected, there are many packages that use some of these kwargs in a positional manner. So these changes have broken many packages. I started working though the packages to make the necessary changes so everything not listed in #2634 works again.

Like PRs I've done before here, I'm doing this pretty modularly so I figured I'd create the PR to get some input from yall on whether or not you want me to squash all the fixes to the different packages since in some cases its a 1-3 line change.

### CODE REVIEW

**Comment by nkphysics** [comment]
I can't seem to figure out where these 2 additional misses in utils/tap/ are that codecov is reporting.

**Comment by nkphysics** [comment]
Ok, I figured out why codecov was mad... Should be ok now.

**Comment by nkphysics** [comment]
This should be ready for review.

**Review by bsipocz — APPROVED** [review]
One minor comment, and that this should be also added to the changelog.

**Comment by bsipocz** [comment]
Thanks @nkphysics!

**Pull request merged**
