### PR TITLE
Fix for issue #1160 asynchrounous job launching

### PR DESCRIPTION
**Pull request by emeraldTree24**
Fixing async job launching by separating the creating and running of jobs. Also following redirects when needed.

### CODE REVIEW

**Comment by bsipocz** [comment]
Yes, I think it's mostly waiting for review.

**Comment by brianmajor** [comment]
There has been a bit of a conversation relating to this pull request happening on the issue page for #1160

**Comment by emeraldTree24** [comment]
@jcsegovia sounds good, go ahead.

**Comment by emeraldTree24** [comment]
Waiting for changes from TAP/TAP+

**Pull request closed without merging**
