### PR TITLE
fix flag parsing for ephemerides with planetodetic coordinates in id

### PR DESCRIPTION
**Pull request by m-stclair**
JPL has changed how they respond to ephemerides queries for specific points on a body's surface several times in the past ~18 months. They appear to have settled on a solution. This change parses the additional columns they now add to these tables. Should fix [#1555](https://github.com/astropy/astroquery/issues/1555)

### CODE REVIEW

**Comment by bsipocz** [comment]
Could you please add tests and maybe also an example to the narrative docs for this?

A rebase is also needed to pick up the CI changes.

**Comment by m-stclair** [comment]
@bsipocz Definitely! I've added tests for a bunch of these ephemerides query cases and written some additional documentation about user-specified topocentric queries. How does this look?

**Review by bsipocz — CHANGES_REQUESTED** [review]
This requires a rebase due to the numerous unrelated commits

**Comment by bsipocz** [comment]
I've rebased this to make it ready for review from @mkelley, but couldn't push back the branch as the PR was opened from an org account. So the current, rebased version is here: https://github.com/bsipocz/astroquery/pull/new/MillionConcepts_master

(I haven't done code review, but a changelog entry will certainly be needed prior merging)

**Comment by bsipocz** [comment]
@mkelley - if you can spot some bigger conceptual issues then it's fine to comment on them based on the diff here, but any more nuanced review should wait for the rebase as details may change.

**Comment by mkelley** [comment]
I gave it a look and I think the changes are good.  The only problem I see is that my PR I'm about to submit should go through first, since it is time sensitive.  A new Horizons API URL and some small formatting changes go into effect Sep 27.  So, we may have some collisions on a few test updates, but they should be easy to resolve (not sure if it will be another rebase or not).

I do have a note about the tests.  One of them uses a random set of dates.  Logically it is fine, but then we cannot take advantage of caching.  I'm not concerned, but just wanted to raise the point in case you wanted to avoid that.

**Comment by bsipocz** [comment]
@mkelley - sounds like a good plan. 

Regarding random testing: we should not rely on the cache for testing, so it should be OK for the POV. However, random tests sound to be problematic at time of hunting bugs, as failures may not be easily reproducible.

**Comment by bsipocz** [comment]
This now has conflicts, and test failures appear after a simple rebase, so I remilestone it for now.

**Comment by bsipocz** [comment]
@mkelley - do you have time to pick this up? As I see the discussion above it will need to be a rebase and a new PR, using the commits here, as neither of have the capacity to update the branch in the org account it was opened from.

**Comment by mkelley** [comment]
Hi @bsipocz , sure I can take over.  I hope the due date isn't soon, because I will need to get a release of sbpy done first.

**Comment by bsipocz** [comment]
@mkelley - no, there is no due date at all, I just triaged a lot of PRs recently to see whether anything is close to being ready to merge.

**Comment by bsipocz** [comment]
@m-stclair @mkelley - do you have any update with this?

The PR as is cannot be taken over by the maintainers as it was opened from an org account (so we cannot push back to the fork's branch), so I wonder whether 1) there are plans to resurrect it by you @m-stclair or others in the org, or reopen it after a rebase, or 2) it's so much outdated with the many changes happened in `jplhorizons` in the past year that we rather just close it?

IMO, keeping it around as is, without a clear plan makes little sense.

**Comment by m-stclair** [comment]
Apologies; this had fully fallen off my radar. I will review this in the next few days and see whether it has been obviated by changes to `jplhorizons` in the past year or whether it is worth reopening after a rebase.

**Comment by bsipocz** [comment]
Thanks!

**Comment by m-stclair** [comment]
My assessment is that the substance of this PR would still be useful. This kind of query still produces unexpected behavior:
```query = Horizons(id='g:0,0,0@301')```
JPL Horizons recognizes this as a valid query, and the content of `query.ephemerides_async().text` is sensible, but calling `query.ephemerides()` results in an `InconsistentTableError`. A somewhat more turnkey way to specify target coordinates than using JPL Horizon's weird 'g:' syntax is also probably desirable. I have closed this PR and will open a new draft PR from a rebased fork.

**Pull request closed without merging**
