### PR TITLE
Move away from setup.cfg and astropy-helpers

### PR DESCRIPTION
**Pull request by juliotux**
With Python 3.12, the building infrastructure have serious deprecated chages. Some of them impact in astropy-helpers, which is already [deprecated](https://github.com/astropy/astropy-APEs/blob/main/APE17.rst) by astropy team.

With this merge request, I'm moving everything away from the old astropy helpers and changing the configuration file to the `pyproject.toml`.

I tried to maintain everything as close as possible of what is found in the previous `setup.cfg`.

The file is based in the [`astropy/pyproject.toml`](https://github.com/astropy/astropy/blob/main/pyproject.toml).

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @juliotux, but I'm not sure this is exactly what we need, definitely not before the new release is out, therefore I can't promise a swift review.

(Switching out from the helpers is certainly on the radar, and we very well know it's been retired (we were the maintainers of it after all)).

**Comment by juliotux** [comment]
@bsipocz this MR is just to help. Feel free to use it or not. I created it to adress an issue I'm having with my [CI](https://github.com/sparc4-dev/astropop/actions/runs/6291146614/job/17079242589?pr=121#step:8:45).

I noticed that my devdeps CI is erroring when trying to install `astroquery` from git. And the reason is that, when using python 3.12, the fails come directly from the `astropy_helpers` import.

```
      Traceback (most recent call last):
        File "/tmp/pip-req-build-eembwrpa/astropy_helpers/setup.py", line 22, in <module>
          from astropy_helpers.version_helpers import generate_version_py  # noqa
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-eembwrpa/astropy_helpers/astropy_helpers/version_helpers.py", line 34, in <module>
          from .distutils_helpers import is_distutils_display_option
        File "/tmp/pip-req-build-eembwrpa/astropy_helpers/astropy_helpers/distutils_helpers.py", line 18, in <module>
          from .utils import silence
        File "/tmp/pip-req-build-eembwrpa/astropy_helpers/astropy_helpers/utils.py", line 4, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
```

So, unfortunately, I thing this will be a necessary move you will need soon and this is what is needed to my CI pass.

Python 3.12 is scheduled to be released in [2023-10-02](https://peps.python.org/pep-0693/).

**Comment by bsipocz** [comment]
Yes, I'm very well aware of the issue, see the open PRs about 3.12. Also, astropy has just fixed its 3.12 incompatibility.  So that CI wasn't working for a while anyway, to unblock astroquery in it, I would suggest to pip install the pre release, the wheel should be working (once the pyvo and aq 3.12 PRs are merged).

 Anyway, the plan is to release a 3.12 compatible wheel at the end of the FY, and deal with the helpers after, along with other infrastructure overhauls, but for that release there are way higher priority things to sort out.

**Comment by bsipocz** [comment]
Thank you @juliotux for the contribution.

Unfortunately, this unsolicited PR touches on parts of the infrastructure that should stay, and reactors much more than what's desirable, while doesn't address the plans we will need to do when switching away from the helpers. It also has broken CI.

Python 3.12 compatibility has been addressed in an earlier PR, and a pre-release have been uploaded to pypi, too. That should help you unblock your CI. So, I go ahead and close this one for now.

**Pull request closed without merging**
