### PR TITLE
Some fixes for broken remote tests

### PR DESCRIPTION
**Pull request by keflavich**
Including a fix to ALMA bugs noted in #879

### CODE REVIEW

**Comment by bsipocz** [comment]
@keflavich - If you think the alma change will need a changelog, could you please add one? I think it's easier to do it in the PR than right before release.

**Comment by keflavich** [comment]
@bsipocz Yes, I'll do that.  There are still a few bugs that need fixing or...something, though.  ALMA changed a lot of things upstream that I think are major bugs on their end (many data sets are missing), which has broken our tests that assume data sets will never be removed.  I have two outstanding helpdesk tickets with ALMA - I'll wait to hear at least a first reply before merging this.

**Comment by bsipocz** [comment]
@keflavich - sounds good. I wish they had some API stability in mind rather than this works for us on our web interface one.

**Comment by keflavich** [comment]
I've talked face to face with some of the developers many times, and I still don't fully understand what's changing behind the scenes.  I suspect they did not intend these latest changes and they are instead a major uncaught bug.

**Comment by keflavich** [comment]
Except for some continued server failures that are not generally reproducible, this PR is done and passes locally.  The failures that may come up are:
```
E               ValueError: The query validation failed for unknown reasons.  Try again?
```
and
```
E           requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://almascience.nrao.edu/dataPortal/requests/anonymous/954703801/ALMA/2011.0.00121.S_2012-08-16_002_of_002.tar/2011.0.00121.S_2012-08-16_002_of_002.tar
```

which, afaict, are flaky server issues, so I'm going to merge this.

**Comment by keflavich** [comment]
Closing this because it is done in #888

**Pull request closed without merging**
