### PR TITLE
Fix for #1340: add new VOT hacks for ALMA

### PR DESCRIPTION
**Pull request by keflavich**
edit: I'd written a nice summary that seems to not have made it up here....

There is missing metadata in the ALMA votables.  This updates the existing hack to fix the missing metadata.

### CODE REVIEW

**Comment by bsipocz** [comment]
This may worth a changelog entry?

**Comment by bsipocz** [comment]
Also, the failures I randomly looked at are related.

**Comment by keflavich** [comment]
Ah, I probably need to change the offline tests...

**Comment by bsipocz** [comment]
wow, this is a big diff. Why is the sgra file so much bigger?

**Comment by keflavich** [comment]
I re-did the query; there are a lot more results for Sgr A* these days

**Comment by keflavich** [comment]
It would be nice to keep the data smaller...

**Comment by bsipocz** [comment]
Choose a boring target ;) 

Otherwise is this good to go? Ultimately we need to figure out a clever way to do coverage, but it won't happen in this PR or the next.

**Comment by keflavich** [comment]
You mean improve coverage specifically for this module?  I don't think there's anything to be done, unfortunately; we can't test logging in on a remote system, and even if we'd caught this issue earlier, it still would've taken just as long to identify and debug it...

Anyway, yes, a more boring target is a reasonable idea, I'll consider it as I'm going through other issues

**Comment by bsipocz** [comment]
No, not this one is particular, my comment was triggered by the codecov status and numbers.

**Comment by keflavich** [comment]
This needs to be merged ~last week.  I picked a different (less popular) target to decrease the data size.  I'll merge once it passes.

**Comment by bsipocz** [comment]
@keflavich - can you squash the commits of the data sets?

**Comment by keflavich** [comment]
I ended up squashing the whole thing down to 1 commit because the addition/removal of the .xml tables wasn't very linear

**Pull request merged**
