### PR TITLE
Remote test fixes

### PR DESCRIPTION
**Pull request by keflavich**
First, this adds a skip for several ALMA tests that were too slow.

@bsipocz, do we need *all* of the remote tests to pass to get to the final stage in deployment?  We might not want it to be that restrictive

### CODE REVIEW

**Comment by keflavich** [comment]
Last remote-data run:
```
astroquery/alfalfa/tests/test_alfalfa.py ...
astroquery/alma/tests/test_alma.py ......
astroquery/alma/tests/test_alma_remote.py ..sssFss
astroquery/alma/tests/test_alma_utils.py ..F
astroquery/atomic/tests/test_atomic.py ....
astroquery/atomic/tests/test_atomic_remote.py ....
astroquery/besancon/tests/test_besancon.py ....
astroquery/data/README.rst .
astroquery/esasky/tests/test_esasky.py ....
astroquery/esasky/tests/test_esasky_remote.py ..FF..
astroquery/eso/tests/test_eso.py ...
astroquery/eso/tests/test_eso_remote.py .F....ss............................
astroquery/exoplanet_orbit_database/tests/test_exoplanet_orbit_database.py ....s.
astroquery/fermi/tests/test_fermi.py ....
astroquery/gaia/tests/test_gaiatap.py .........
astroquery/gama/tests/test_gama.py ..
astroquery/gama/tests/test_gama_remote.py ..
astroquery/heasarc/tests/test_heasarc_remote.py ......
astroquery/hitran/tests/test_hitran.py .
astroquery/ibe/tests/test_ibe.py ......
astroquery/ibe/tests/test_ibe_remote.py ..
astroquery/irsa/tests/test_irsa.py .............................
astroquery/irsa/tests/test_irsa_remote.py ......
astroquery/irsa_dust/tests/test_irsa_dust.py ..................................................................
astroquery/irsa_dust/tests/test_irsa_dust_remote.py ..........................................
astroquery/jplhorizons/core.py .....
astroquery/jplhorizons/tests/test_jplhorizons.py ...
astroquery/jplhorizons/tests/test_jplhorizons_remote.py .............
astroquery/lamda/tests/test_lamda.py ..
astroquery/lamda/tests/test_lamda_remote.py .
astroquery/lcogt/tests/test_lcogt.py .............................
astroquery/lcogt/tests/test_lcogt_remote.py xxxxxxxx
astroquery/magpis/tests/test_magpis.py ...x
astroquery/magpis/tests/test_magpis_remote.py ..
astroquery/mast/tests/test_mast.py ...........................
astroquery/mast/tests/test_mast_remote.py ............F...............
astroquery/mpc/tests/test_mpc.py ....
astroquery/mpc/tests/test_mpc_remote.py ...........
astroquery/nasa_ads/tests/test_nasaads.py F
astroquery/nasa_exoplanet_archive/tests/test_nasa_exoplanet_archive.py ...s.
astroquery/ned/tests/test_ned.py .......................
astroquery/ned/tests/test_ned_remote.py ....................
astroquery/nist/tests/test_nist.py ...
astroquery/nist/tests/test_nist_remote.py ..
astroquery/nrao/tests/test_nrao.py ....
astroquery/nrao/tests/test_nrao_remote.py ....
astroquery/nvas/tests/test_nvas.py ......
astroquery/nvas/tests/test_nvas_remote.py ...
astroquery/oac/tests/test_oac.py .........
astroquery/oac/tests/test_oac_remote.py ......FF.
astroquery/ogle/tests/test_ogle.py ...
astroquery/open_exoplanet_catalogue/utils.py ..
astroquery/open_exoplanet_catalogue/tests/test_open_exoplanet_catalogue_local.py .
astroquery/open_exoplanet_catalogue/tests/test_open_exoplanet_catalogue_remote.py .
astroquery/sdss/tests/test_sdss.py .................................xxxxxxxxxxx..................................xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...xxxxxxxxxxx.......................
astroquery/sdss/tests/test_sdss_remote.py FF..........xx..
astroquery/sha/tests/test_sha.py .....
astroquery/simbad/core.py ....
astroquery/simbad/tests/test_simbad.py .........................................................
astroquery/simbad/tests/test_simbad_remote.py ............................
astroquery/skyview/tests/test_skyview.py ..
astroquery/skyview/tests/test_skyview_remote.py ........F.....F.....F.F...FF
astroquery/splatalogue/core.py .
astroquery/splatalogue/tests/test_splatalogue.py ...........
astroquery/splatalogue/tests/test_utils.py ...
astroquery/template_module/tests/test_module.py .
astroquery/template_module/tests/test_module_remote.py .
astroquery/tests/test_internet.py .
astroquery/tests/test_resume.py s
astroquery/ukidss/tests/test_ukidss.py ........
astroquery/ukidss/tests/test_ukidss_remote.py ......
astroquery/utils/commons.py .
astroquery/utils/url_helpers.py .
astroquery/utils/tap/conn/tests/test_conn.py ...
astroquery/utils/tap/model/tests/test_column.py .
astroquery/utils/tap/model/tests/test_filter.py .
astroquery/utils/tap/model/tests/test_job.py ..
astroquery/utils/tap/model/tests/test_table.py ..
astroquery/utils/tap/tests/test_tap.py .......
astroquery/utils/tap/xmlparser/tests/test_xmlparser.py ....
astroquery/utils/tests/test_url_helpers.py .
astroquery/utils/tests/test_utils.py .......................
astroquery/vamdc/tests/test_vamdc_remote.py s
astroquery/vizier/tests/test_vizier.py ............................
astroquery/vizier/tests/test_vizier_remote.py ...............
astroquery/vo_conesearch/tests/test_conesearch.py ......x..........x....
astroquery/vo_conesearch/tests/test_vos_catalog.py ...............
astroquery/vo_conesearch/validator/tests/test_inpect.py ....
astroquery/vo_conesearch/validator/tests/test_validate.py ....
astroquery/vsa/tests/test_vista_remote.py .....
astroquery/xmatch/tests/test_xmatch.py .....
astroquery/xmatch/tests/test_xmatch_remote.py ....
docs/api.rst .
docs/gallery.rst .
docs/index.rst .
docs/license.rst .
docs/query.rst .
docs/release_notice_v0.2.rst .
docs/template.rst .
docs/testing.rst .
docs/utils.rst .
docs/alfalfa/alfalfa.rst .
docs/alma/alma.rst .
docs/atomic/atomic.rst .
docs/besancon/besancon.rst .
docs/cosmosim/cosmosim.rst .
docs/esasky/esasky.rst .
docs/eso/eso.rst .
docs/exoplanet_orbit_database/exoplanet_orbit_database.rst .
docs/fermi/fermi.rst .
docs/gaia/gaia.rst .
docs/gama/gama.rst .
docs/heasarc/heasarc.rst .
docs/hitran/hitran.rst .
docs/ibe/ibe.rst .
docs/irsa/irsa.rst .
docs/irsa/irsa_dust.rst .
docs/jplhorizons/jplhorizons.rst .
docs/lamda/lamda.rst .
docs/magpis/magpis.rst .
docs/mast/mast.rst .
docs/mpc/mpc.rst .
docs/nasa_ads/nasa_ads.rst .
docs/nasa_exoplanet_archive/nasa_exoplanet_archive.rst .
docs/ned/ned.rst .
docs/nist/nist.rst .
docs/nrao/nrao.rst .
docs/nvas/nvas.rst .
docs/oac/oac.rst .
docs/ogle/ogle.rst .
docs/open_exoplanet_catalogue/open_exoplanet_catalogue.rst .
docs/sdss/sdss.rst .
docs/sha/sha.rst .
docs/simbad/simbad.rst .
docs/skyview/skyview.rst .
docs/splatalogue/splatalogue.rst .
docs/ukidss/ukidss.rst .
docs/utils/tap.rst .
docs/vamdc/vamdc.rst .
docs/vizier/vizier.rst .
docs/vo_conesearch/client.rst .
docs/vo_conesearch/validator.rst .
docs/vo_conesearch/vo_conesearch.rst .
docs/vsa/vsa.rst .
docs/wfau/wfau.rst .
docs/xmatch/xmatch.rst .
```

**Comment by keflavich** [comment]
There appears to be a real OAC test failure:
```
_______________________________________________________________________ TestOACClass.test_get_single_spectrum ________________________________________________________________________

self = <astroquery.oac.tests.test_oac_remote.TestOACClass object at 0x1822c8ea58>

    def test_get_single_spectrum(self):
        test_time = 54773
        spec = OAC.get_single_spectrum(event="GW170817", time=test_time)
>       assert isinstance(spec, Table)
E       assert False
E        +  where False = isinstance(None, Table)

astroquery/oac/tests/test_oac_remote.py:71: AssertionError
-------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------
ERROR: API Server returned the following error:
{"message": "When retrieving spectra in delimited format, exactly one at a time can be requested."}
```

cc @pcowpert - could you look into this error?

**Comment by keflavich** [comment]
The MAST error is a mismatch in the count of hits:
```
__________________________________________________________________ TestMast.test_observastions_query_criteria_count __________________________________________________________________

self = <astroquery.mast.tests.test_mast_remote.TestMast object at 0x1822fd56d8>

    def test_observastions_query_criteria_count(self):
        maxRes = mast.Observations.query_criteria_count()
        result = mast.Observations.query_criteria_count(proposal_pi="Osten",
                                                        proposal_id=8880)
        assert isinstance(result, (np.int64, int))
>       assert result == 7
E       assert 3 == 7

astroquery/mast/tests/test_mast_remote.py:137: AssertionError
```

@ceb8, could you have a look?  Should there be 3 or 7 hits here?

**Comment by ceb8** [comment]
@keflavich It looks like something changed about how the search is executed server-side,  which is causing the change in number of results.  I can do a quick patch that stops this test failing or if you prefer you can just remove that test and I'll update it when I actually fix the issue, which will take a little more time.

**Comment by keflavich** [comment]
@ceb8 I'll remove the test for now.  If you'd like, it might be appropriate to open an Issue to remind us to add the test back when the remote service is fixed.

**Comment by ceb8** [comment]
@keflavich  Will do!

**Comment by pcowpert** [comment]
@keflavich 

I am able to reproduce this failure by running `python setup.py test -P oac -R`. Judging by the error message it might be something API side which might require a little debugging from @guillochon 

If it is urgent, you can go the "comment out" route for now and we will figure it out on our end.

**Comment by keflavich** [comment]
This failure:
```
astroquery/alma/tests/test_alma_utils.py ..F
```
is a really awkward upstream failure of aplpy + astropy visualization tools.

**Comment by keflavich** [comment]
@pcowpert OK, thanks.  I recommend opening an Issue about this.  I will comment out the failing test for now

**Comment by pcowpert** [comment]
@keflavich Okay. Some other tests might fail. It seems to be an issue with querying the object `GW170817` specifically.

If you change the test_time to something like `56680` and replace `GW170817` with `SN2014J` then all tests pass on my end.

**Comment by pcowpert** [comment]
@keflavich Okay. We ID'd the issue. It was some event naming confusion on the API side.

It might be better if the tests are for an older more "stable" event. I've pushed an updated remote test file. Everything passes on my end.

It's currently on my fork, but I can PR it if that's preferred.

https://github.com/pcowpert/astroquery/blob/master/astroquery/oac/tests/test_oac_remote.py

**Comment by keflavich** [comment]
@pcowpert could you PR it onto this branch?

**Comment by keflavich** [comment]
Merging.  Let's see if this gets us to deployment...

**Pull request merged**
