### PR TITLE
bugfixes for jplhorizons and jplsbdb

### PR DESCRIPTION
**Pull request by mommermi**
This PR fixes the following bugs:

* `jplhorizons`: described in issue #1332; the new behavior will not list `H` in the resulting table if it is not defined in the raw data
* `jplsbdb`: fixes a bug in which non-existing vales for parameters will lead to a crash as the code tried to attach a unit to a `NoneType`; now, the `NoneType` is kept without trying to attach unit type

### CODE REVIEW

**Comment by bsipocz** [comment]
@mommermi - Could you please add a test for this, e.g. using the same object as in #1332

**Comment by mommermi** [comment]
oh, please wait with the merge. There is one more thing I would like to add.

**Comment by mommermi** [comment]
except for the pytest issues in the Travis-CI build, this pr is done

**Comment by bsipocz** [comment]
Thanks @mommermi!.
I'm having #1334 for fixing the unrelated failures. Once that's in, I'll give this a rebase to make sure it passes.

**Comment by bsipocz** [comment]
Thanks @mommermi!

**Pull request merged**
