### PR TITLE
Fix NRAO project_code query

### PR DESCRIPTION
**Pull request by e-koch**
The `project_code` was not being passed to `NraoClass.query_async`. I added a test using the oldest archival project from the existing reqion queried in other tests.

### CODE REVIEW

**Comment by e-koch** [comment]
The test code works in the terminal but fails in the test suite, locally and on travis. Is there a difference in how the test runs in pytest?

**Comment by keflavich** [comment]
@e-koch did you forget to add a test file?  You added a non-remote test, which means you need a file to test against, and it looks like there should be a new file.

**Comment by e-koch** [comment]
@keflavich thanks! I've moved the test to be remote. That seemed appropriate for this case, given the other remote tests.

**Comment by e-koch** [comment]
The code style failures appear to be from files not changed in this PR.

**Comment by keflavich** [comment]
I'll try to merge this once tests are running again - NRAO archives are toast right now =(

**Comment by keflavich** [comment]
This has one remote failure that is solved by #1672

**Comment by keflavich** [comment]
Merged in 19485c0fa9345a886412f67423f3b22bcbbb4df3

**Comment by bsipocz** [comment]
@keflavich - same here, please do force push the rebases back, it's also good to get one more CI run after a rebase, before merging stuff in.

**Pull request closed without merging**
