### PR TITLE
[SIMBAD] Add emtpy response warning

### LINKED ISSUE #3060: Handling  No astronomical object found response
When I run the following script that queries a tiny sky region where Simbad has no object:

```python
from astroquery.simbad import Simbad
from astropy.coordinates import SkyCoord, search_around_sky, Angle
import astropy.units as u

ra = 0
dec = -90
output_table= Simbad.query_region(SkyCoord(ra, dec,unit=(u.deg, u.deg), frame='icrs'), radius=0.01*u.arcsec)
```

This code raises the following warning:

```
WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '0:00:00 -90:00:00': No astronomical object found : [astroquery.simbad.core]
```
The problem is that `output_table` is `None`. 
There is no way to grab by software the reason of the failure except by parsing the WARNING message (awkward/ugly).

There are 2 options to improve this issue:
- The query region  could return a tuple such as e.g. `(error_status, table)`
- The method should  be refactored in order to return a VOTable in any case (as announced by the warning)

### PR DESCRIPTION
**Pull request by ManonMarchand**
Hi astroquery devs, 

This PR adds a `NoResultWarning` when a SIMBAD query returns an empty table. This should fix #3060 .

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
This looks good thank you. 

I see the doctest failing locally, but it's some weird issue that I don't yet tracked down as it not always showing up in CI. So I'll just leave it as is now.


Thanks!

**Comment by ManonMarchand** [comment]
Oh? Could you show your local failure? I don't have any.

**Comment by bsipocz** [comment]
It's just messing around ELLIPSIS and whitespace, it really is a local issue most of the time.

But for this one, I see it in CI, too: https://github.com/astropy/astroquery/actions/runs/9814474694/job/27525866043#step:5:13186

(just restarted this run after merging a bunch of PRs this morning, so any failures your see there are on `main`)

**Comment by ManonMarchand** [comment]
Maybe I have something different in my config, because I see the failure the other way, and I patched the width of the output in https://github.com/astropy/astroquery/pull/3068/commits/9f65c6f87f59f0ef598c634e11c10e232d945e94
I'll have a look on my side too

**Comment by bsipocz** [comment]
I would say don't worry about it for now (or we should just patch things up for the weekly CI to have fewer issues, but then again it doesn't really matter. I'll open an issue upstream for doctestplus as ideally, we should handle it within it. 

(Also, maybe you have an older pytest-doctestplus version? If yes, that may help to narrow down when and why this became a problem).

**Pull request merged**
