### PR TITLE
Minor splatalogue change

### PR DESCRIPTION
**Pull request by keflavich**
1. improved example
2. change parsing to be local again after finding out that the remote chemical parser is highly inflexible

### CODE REVIEW

**Comment by keflavich** [comment]
Unfortunately py2.7 is comparing unicode to unicode incorrectly.  I don't know how to fix this.  I'm inclined to just skip these tests, but if anyone else knows how to fix this bug, please let me know.

**Comment by bsipocz** [comment]
@keflavich - I think it's fine to skip the tests for python 2.7, if this brakes in the future we will be able to identify it with python3.

**Comment by keflavich** [comment]
Is it possible to disable a specific doctest for only py 2.7?

**Comment by bsipocz** [comment]
@keflavich - I'm not sure whether the is a proper, more elegant way, but you should be able to use ``__doctest_requires__`` with specifying a python2.7 only thing to import.

**Comment by keflavich** [comment]
....what the heck is going on with Windows?  It doesn't like `isclose` any more?  
https://ci.appveyor.com/project/Astropy/astroquery/build/1.0.266/job/yqbw4sk5dl57l41e#L948
I'm going to ignore these failures.

**Comment by bsipocz** [comment]
The appveyor error is very weird, probably we can have a workaround by pinning some package version, I'll have more opportunity to check the details once back from the holidays. I also wonder whether other affiliated packages, or core astropy experience it?

Maybe @mwcraig saw this problem before?

**Pull request merged**
