### PR TITLE
Astroquery.splatalogue query not respecting "exclude" keyword(?)

### PR DESCRIPTION
**Pull request by keflavich**
There might be an issue with the "exlcude" parameter in Splatalogue modeul of Astroquery. The example below will only work if "potential" and "probable" are not selected (i.e only 'atmospheric' selected), I run it with None (which should work as well).
Running (in Astroquery 0.3.0)

```
from astroquery import splatalogue
import astropy.units as u
results = splatalogue.Splatalogue.query_lines(
    min_frequency=351.9*u.GHz,
    max_frequency=352.*u.GHz,
    chemical_name='Formaldehyde',
    energy_max=4000,
    energy_type='eu_k',
    line_lists=['CDMS'],
    export_limit=1000.,
    exclude=None,
    version='v2.0',
    show_upper_degeneracy=True,
    )
results.pprint()
```

should give one hit on 'D213CO', but gives an empty table, i.e.:

```
Species Chemical Name Freq-GHz ... E_U (K) Upper State Degeneracy Linelist
------- ------------- -------- ... ------- ---------------------- --------
```

The direct URL for the query is
http://www.cv.nrao.edu/php/splat/c.php?submit=submit&sid[]=&chemical_name=Formaldehyde&el4=el4&ls1=ls1&ls5=ls5&displayCDMS=displayCDMS&data_version=v2.0&from=351.9&to=352&frequency_units=GHz&energy_range_to=1000&energy_range_type=eu_k&submit=1
and indeed gives one hit.

Can someone double check if this is an issue?

### CODE REVIEW

**Comment by keflavich** [comment]
@vilhelmp does this fix your issue?

**Comment by keflavich** [comment]
yeah, I had messed it up.  Try now

**Comment by vilhelmp** [comment]
I still cannot make it respect the keywords. Is there anyway to get the raw payload (URL) that it uses to see if it is included?

**Comment by keflavich** [comment]
Use `result = Splatalogue.query_lines_async(get_query_payload=True)`.  But I've implemented a real fix with a test now.

**Comment by keflavich** [comment]
@vilhelmp could you check this again?  This time, I'm pretty sure it will work because I added a real test.

**Comment by vilhelmp** [comment]
Hey sorry for late response, was down with the flu.
It still doesn't work. It's something got to do with the default keywords. It sets it to the default first right. and the we try to delete them, and that doesn't work somehow.

**Comment by keflavich** [comment]
This now includes a remote test that appears to work.  @vilhelmp I'm going to merge this when tests pass, but it would be nice to have confirmation from you that it works.  Note that the syntax in your example will *not* work and is not intended to. You should instead do:

```
results =Splatalogue.query_lines(
    min_frequency=351.9*u.GHz,
    max_frequency=352.*u.GHz,
    chemical_name='Formaldehyde',
    exclude='none', # not None
    )
```

**Comment by vilhelmp** [comment]
In my _Anaconda Python 3.5_ dist, I created an environment, and after `git clone https://github.com/astropy/astroquery` and `cd astroquery && conda develop .` I start Ipython and:

    from astroquery import splatalogue

I get the following error:

    ImportError                               Traceback (most recent call last)
    <ipython-input-4-1bd50a79c8c2> in <module>()
    ----> 1 from astroquery import splatalogue
    
   /python/development/testing/astroquery/astroquery/splatalogue/__init__.py in <module>()
         34 from . import load_species_table
         35 from . import utils
    ---> 36 from .core import Splatalogue, SplatalogueClass
         37 
         38 __all__ = ['Splatalogue', 'SplatalogueClass',
    
   /python/development/testing/astroquery/astroquery/splatalogue/core.py in <module>()
         10 from astropy import units as u
         11 from astropy import log
    ---> 12 from ..query import BaseQuery
         13 from ..utils import async_to_sync
         14 from ..utils.docstr_chompers import prepend_docstr_noreturns

     /python/development/testing/astroquery/astroquery/query.py in <module>()
          15 import astropy.utils.data
          16 
     ---> 17 from . import version
          18 
          19 __all__ = ['BaseQuery', 'QueryWithLogin']
     ImportError: cannot import name 'version'

**Comment by keflavich** [comment]
I don't know - I've never used conda develop.  Maybe you need to run `python setup.py develop`?

**Comment by bsipocz** [comment]
I'm not sure how to use conda develop, but the suggested way is usually to either ``pip install git+http://github.com/astropy/astroquery.git#egg=astroquery`` , or simply run ``python setup.py develop``

**Comment by vilhelmp** [comment]
Alright, it works. Everything looks good. I get the expected results now. Great job! 

Perhaps `conda develop .` will not build things, just link the folder in the python path, anyway, running the `pip install ` command in an environment worked fine.

**Pull request merged**
