### PR TITLE
Vizier: respect UCD specification in find_catalogs

### PR DESCRIPTION
**Pull request by keflavich**
Also, start documenting the base class

### CODE REVIEW

**Comment by bsipocz** [comment]
@keflavich - could you add a test for this, too?

**Comment by keflavich** [comment]
Related to https://github.com/astropy/astroquery/issues/998

**Comment by bsipocz** [comment]
@keflavich - This can go in I think, the CI failures are related to the upstream numpy 1.14 issue that should be fixed in numpy 1.14.1 and worked around with the new astropy releases soon to be released, too.

**Comment by bsipocz** [comment]
(rebased to resolve the changelog conflict)

**Comment by bsipocz** [comment]
@keflavich - There was a changelog already...

**Comment by keflavich** [comment]
Ahh....oops, we both rebased at the same time, and I force-pushed over you

**Comment by bsipocz** [comment]
Oh, ok, that's fine. It look all good now (github just behaved weirdly as it kept all my rebased commits and added another "add changelog entry", refreshing the page cleared it up).

**Pull request merged**
