### PR TITLE
Refactor `astroquery/utils/system_tools.py` and its tests

### PR DESCRIPTION
**Pull request by eerovaher**
See the commit messages for details.

### CODE REVIEW

**Comment by bsipocz** [comment]
I recall some issues around non-availablity of gzip on windows, thus this whole workaround was added in https://github.com/astropy/astroquery/pull/1613? It was done after we dropped python2 support though 

@pllim - do you see any issue with this PR?

**Comment by pllim** [comment]
I can see `gzip` on Windows with Python 3.8. If it passes in your Windows CI, probably ok?

**Comment by bsipocz** [comment]
OK, thanks for confirming. Let's try to see this then, thanks @eerovaher for the cleanup.

**Comment by eerovaher** [comment]
I'll try to clear any confusion there may be about the availability of `gzip` on different platforms. There exists a program called [gzip](https://www.gzip.org/) which has nothing to do with Python, and which is not guaranteed to be installed by all users. Before #1613 `astroquery` tried to use that program, but its availability had to be checked. What #1613 did was it replaced the external `gzip` with the Python standard library module also called [gzip](https://docs.python.org/3/library/gzip.html), which can be safely assumed to be available for all `astroquery` users without any need to  check its presence.

**Comment by bsipocz** [comment]
Yes, I suppose part of the issues came with the fact that the standalone, UNIX `gzip` could deal with the `fits.Z` files, but it broke when we switched. Or something else, I can't recall and some of that may be lost in discussions on slack, but it certainly raised as an issue during the precious PR and thus we ended up with the extra checks.

**Pull request merged**
