### PR TITLE
Check whether no result is returned from the query (SDSS)

### LINKED ISSUE #539: Issue an informative message when the query returns empy result (SDSS)
Currently a ``ValueError`` is raised when the query returns an empty result in the ``sdss`` module (e.g. #539). Empty results can be valid, and so I think at least a warning message should be given, and maybe even drop ``ValueError``.

### PR DESCRIPTION
**Pull request by bsipocz**
and deal with it...
Closes #539 

(in part response to #538)

### CODE REVIEW

**Comment by eteq** [comment]
In what can only be labeled as a miracle, it looks like this doesn't conflict with #545.

This looks fine to me except that I don't understand why it's a print statement instead of a warning.  A warning has the advantage that it can be silenced (which is certainly useful here if you have a bunch of automated queries where you *want* it to be). 

@keflavich - is there a general policy for this in astroquery?  I would think the best thing would be to create a NoResultsWarning that's generic to astroquery. @bsipocz could add that here if it doesn't exist and maybe it could filter into the other modules eventually where relevant?

**Comment by keflavich** [comment]
I like warnings for this.  I don't think there is a policy; the original SDSS module was written not according to astropy standards.   Perhaps that should be added as  a (recommended) policy in https://github.com/astropy/astroquery/blob/master/CONTRIBUTING.rst?

**Comment by bsipocz** [comment]
@eteq, @keflavich  - I've added the NoResultsWarning and changed the previous prints and warnings to issue this when relevant. Also gave a quick (but may not be complete for all moduls) search for similar warning like prints and changed them to be warnings instead (mostly all were in the cosmosim module).

**Comment by keflavich** [comment]
I've skimmed this and it looks fine.  @bsipocz is it ready for merge?

**Comment by bsipocz** [comment]
I think yes.

**Pull request merged**
