### PR TITLE
VISTA test

### PR DESCRIPTION
**Pull request by eztean**
Added functionality to query the VISTA database, which has almost identical structure to the one for UKIDSS.

For now, this works through a function within UkidssClass, and VISTA queries should be submitted using an object of the UkidssClass:

`vista = UkidssClass()`
`vista.setup_vista()`
`vista.get_images(...) #for example`

### CODE REVIEW

**Comment by keflavich** [comment]
There are some minor style issues that need fixing.

@pep8speaks suggest a diff

**Comment by keflavich** [comment]
@eztean this looks great.  Could you confirm - do we need any more local tests, or are the local tests identical to UKIDSS?

Discussion topic (@bsipocz, @astrofrog, chime in): Is the current approach (`Ukidss.setup_vista()`) best, or should we try something else?  Or should VISTA and UKIDSS both inherit from a common parent class, and both be available in the "top-level" astroquery namespace?

**Comment by bsipocz** [comment]
@keflavich - While I agree that WSA and VSA are run by the same group, using the same backend, but from the user point of view these are different. Thus I very much like the idea of having a common parent class but making the them separate at top-level.

**Comment by OrkoHunter** [comment]
@keflavich @bsipocz I have implemented the issue comments api for the pep8speaks' commands in [this PR](https://github.com/OrkoHunter/pep8speaks/pull/47). Now there is no need to make a review comment, you can simply make a general PR comment and it will work. [Example](https://github.com/OrkoHunter/test-pep8speaks/pull/63)

@pep8speaks suggest diff

**Comment by keflavich** [comment]
This was superceded by #984, which included most of what was in this PR.  I suspect a rebase prevented github from catching that.

**Pull request closed without merging**
