### PR TITLE
LAMDA writer fails on windows and python3

### PR DESCRIPTION
**Pull request by bsipocz**
This fail was hidden in #887 as the last commit had ``skip ci`` in its message and thus got an all green.

https://ci.appveyor.com/project/Astropy/astroquery/build/1.0.520/job/mvlsvj9ibrd53ecv#L936

### CODE REVIEW

**Comment by bsipocz** [comment]
@keflavich - I could push a commit to this issue and make it a PR (using issue2pr.py). However it was my own issue, I'll try to find another one opened by someone else to test it further.

**Comment by bsipocz** [comment]
@keflavich - FYI this is a bug in astropy on py3 windows https://github.com/astropy/astropy/issues/5126

**Comment by bsipocz** [comment]
@pep8speaks Resume now.

**Comment by bsipocz** [comment]
@pep8speaks Resume now.

**Comment by bsipocz** [comment]
@pep8speaks Suggest diff.

**Comment by bsipocz** [comment]
@pep8speaks suggest a diff

**Comment by OrkoHunter** [comment]
@bsipocz Currently the commands are implemented as a review comment (and not general comment like your last one). Normal comments have a different API than the review comments and I'll work on to get it working very soon :) 
https://github.com/OrkoHunter/pep8speaks/issues/36

**Comment by bsipocz** [comment]
@OrkoHunter - Thanks, good to know.

**Comment by migueldvb** [comment]
Sorry that I missed this issue. I think that the problem is now fixed in [migueldvb:lamda_windows](https://github.com/migueldvb/astroquery/tree/lamda_windows) (https://github.com/migueldvb/astroquery/commit/fad5a39eacb9cb4e490e1294bc9322e9fbd6f382). @bsipocz do you want to merge the change to this PR?

**Comment by migueldvb** [comment]
This issue has a workaround in #1059

**Comment by migueldvb** [comment]
This has been fixed in `master` and the PR can be closed now.

**Pull request closed without merging**
