### PR TITLE
Update to v0.4 / v1.0 astropy configuration system

### PR DESCRIPTION
**Pull request by keflavich**
@mdboom migrated this from #498 since there's some hope that that PR and other old ones can be merged against astropy with reversion.

This is still a WIP as there are some unclear conflicts remaining.

### CODE REVIEW

**Comment by keflavich** [comment]
I see that the automatic generation of .cfg files has been removed here:
http://astropy.readthedocs.org/en/latest/config/config_0_4_transition.html#for-affiliated-package-authors
Is there any way to generate one, though?  Or do I have to manually dig through each package to see what configuration options exist?

**Comment by jwoillez** [comment]
@keflavich - Maybe what you are looking for is in https://github.com/astropy/astroquery/pull/442, especially the first few commits?

**Comment by keflavich** [comment]
Thanks @jwoillez that's what I needed.  Totally forgot about it.

**Comment by keflavich** [comment]
I get 3 failures:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <astroquery.skyview.tests.test_skyview.MockResponseSkyviewForm object at 0x10d4aa0d0>, method = 'GET', url = 'http://www.pa.uky.edu/~peter/atomic/'

    def get_content(self, method, url):
        if 'basicform.pl' in url and method=='GET':
            with open(data_path('query_page.html'),'r') as f:
                return f.read()
        elif 'runquery.pl' in url and method =='GET':
            with open(data_path('results.html'), 'r') as f:
                return f.read()
        else:
>           raise ValueError("Invalid method/url passed to "
                             "Mock Skyview request")
E           ValueError: Invalid method/url passed to Mock Skyview request

astroquery/skyview/tests/test_skyview.py:29: ValueError
___________________________________________________________________ test_survey_validation ____________________________________________________________________

patch_get = <_pytest.monkeypatch.monkeypatch instance at 0x10d3ab3f8>

    def test_survey_validation(patch_get):
        with pytest.raises(ValueError) as ex:
            urls = SkyView.get_image_list(position='doesnt matter',
                                          survey=['not_a_valid_survey'])
>       assert str(ex.value) == ("Survey is not among the surveys hosted "
                                 "at skyview.  See list_surveys or "
                                 "survey_dict for valid surveys.")
E       assert 'Invalid meth...yview request' == 'Survey is not...alid surveys.'
E         - Invalid method/url passed to Mock Skyview request
E         + Survey is not among the surveys hosted at skyview.  See list_surveys or survey_dict for valid surveys.

astroquery/skyview/tests/test_skyview.py:55: AssertionError
__________________________________________________________________________ test_url ___________________________________________________________________________

    def test_url():
        assert 'http://' in splatalogue.core.Splatalogue.QUERY_URL
>       assert 'cv.nrao.edu' in splatalogue.core.Splatalogue.QUERY_URL
E       assert 'cv.nrao.edu' in 'http://www.cosmosim.org/uws/query'
E        +  where 'http://www.cosmosim.org/uws/query' = <astroquery.splatalogue.core.SplatalogueClass object at 0x109440e50>.QUERY_URL
E        +    where <astroquery.splatalogue.core.SplatalogueClass object at 0x109440e50> = <module 'astroquery.splatalogue.core' from 'astroquery/splatalogue/core.py'>.Splatalogue
E        +      where <module 'astroquery.splatalogue.core' from 'astroquery/splatalogue/core.py'> = splatalogue.core

astroquery/splatalogue/tests/test_splatalogue.py:55: AssertionError
================================================ 3 failed, 361 passed, 188 skipped, 2 xfailed in 16.90 seconds ================================================
```

I cannot explain how this url: `'http://www.pa.uky.edu/~peter/atomic/'` is getting passed to skyview.  It doesn't show up anywhere in the skyview package or configuration; it is part of the `atomic` package.  Similarly, there is no reason a `cosmosim` URL should get passed to `splatalogue`.  All I know is that this is somehow related to the configuration system, but I don't understand how.

**Comment by mdboom** [comment]
Automatic generation of the configuration file is gone, that's true.  But you can use the config file from a previous version as a starting point.

**Comment by mdboom** [comment]
@keflavich: I'm checking out your branch now and will see if I can fix some of the issues being seen here.

**Comment by mdboom** [comment]
Sorry for the confusion yesterday.  It looks like you are already on the new API here, and the only fault was the breakage in https://github.com/mdboom/astropy/commit/7186664e777153f5f0d735aee9f09a1bf4c1c5db.  I think this PR can probably just be closed.

**Comment by mdboom** [comment]
Except having the fixed config file is helpful.  Sorry -- still working on it.

**Comment by mdboom** [comment]
All of the errors here go away with astropy/astropy#3627.  So I'd suggest closing this, and only merging #502, which is just the part to add the config file to the repo.

**Pull request closed without merging**
