### PR TITLE
xmatch: bug with caching

### PR DESCRIPTION
**Pull request by keflavich**
This commit makes the remote test ``test_xmatch_query(xmatch)`` fail for both python2 and python3: https://github.com/astropy/astroquery/pull/751/commits/325c60f6f131d041e4423ba4c94ec9ee4ab06541

### CODE REVIEW

**Comment by keflavich** [comment]
I think the PR solves the hashing issue, but I get a different failure:
```
xmatch = <astroquery.xmatch.core.XMatchClass object at 0x111b0e860>

    @remote_data
    def test_xmatch_query(xmatch):
        with open(os.path.join(DATA_DIR, 'posList.csv')) as pos_list:
            table = xmatch.query(
                cat1=pos_list, cat2='vizier:II/246/out', max_distance=5 * arcsec,
>               colRA1='ra', colDec1='dec')

astroquery/xmatch/tests/test_xmatch_remote.py:44:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
astroquery/xmatch/core.py:62: in query
    return ascii.read(response.text, format='csv')
/Users/adam/repos/astropy/astropy/io/ascii/ui.py:336: in read
    dat = reader.read(table)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <astropy.io.ascii.basic.Csv object at 0x111af98d0>
table = '<?xml version="1.0" encoding="UTF-8"?>\n<VOTABLE version="1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ...atch.servlet.SyncXMatch.getXMatchDataSet(SyncXMatch.java:410)\n\t... 25 more\n\n\t</INFO>\n\t</RESOURCE>\n</VOTABLE>\n'

    def read(self, table):
        """Read the ``table`` and return the results in a format determined by
            the ``outputter`` attribute.

            The ``table`` parameter is any string or object that can be processed
            by the instance ``inputter``.  For the base Inputter class ``table`` can be
            one of:

            * File name
            * File-like object
            * String (newline separated) with all header and data lines (must have at least 2 lines)
            * List of strings

            Parameters
            ----------
            table : str, file_like, list
                Input table.

            Returns
            -------
            table : `~astropy.table.Table`
                Output table

            """
        # If ``table`` is a file then store the name in the ``data``
        # attribute. The ``table`` is a "file" if it is a string
        # without the new line specific to the OS.
        with suppress(TypeError):
            # Strings only
            if os.linesep not in table + '':
                self.data.table_name = os.path.basename(table)

        # Get a list of the lines (rows) in the table
        self.lines = self.inputter.get_lines(table)

        # Set self.data.data_lines to a slice of lines contain the data rows
        self.data.get_data_lines(self.lines)

        # Extract table meta values (e.g. keywords, comments, etc).  Updates self.meta.
        self.header.update_meta(self.lines, self.meta)

        # Get the table column definitions
        self.header.get_cols(self.lines)

        # Make sure columns are valid
        self.header.check_column_names(self.names, self.strict_names, self.guessing)

        self.cols = cols = self.header.cols
        self.data.splitter.cols = cols
        n_cols = len(cols)

        for i, str_vals in enumerate(self.data.get_str_vals()):
            if len(str_vals) != n_cols:
                str_vals = self.inconsistent_handler(str_vals, n_cols)

                # if str_vals is None, we skip this row
                if str_vals is None:
                    continue

                # otherwise, we raise an error only if it is still inconsistent
                if len(str_vals) != n_cols:
                    errmsg = ('Number of header columns (%d) inconsistent with '
                              'data columns (%d) at data line %d\n'
                              'Header values: %s\n'
                              'Data values: %s' % (n_cols, len(str_vals), i,
                                                   [x.name for x in cols], str_vals))
>                   raise InconsistentTableError(errmsg)
E                   astropy.io.ascii.core.InconsistentTableError: Number of header columns (1) inconsistent with data columns (3) at data line 25
E                   Header values: ['<?xml version="1.0" encoding="UTF-8"?>']
E                   Data values: ['? cols1|2=col1', 'col2', 'col3']
```

**Comment by keflavich** [comment]
```
/Users/adam/repos/astropy/astropy/io/ascii/core.py:1177: InconsistentTableError --> https://bpaste.net/show/af001c882ae1
/Users/adam/repos/astropy/astropy/io/ascii/core.py:1177: InconsistentTableError --> https://bpaste.net/show/1706537b54b5
```

**Comment by bsipocz** [comment]
First of all the ``response.text`` returns a votable rather than a csv file, so this line doesn't seem to be right
```
> /Users/bsipocz/munka/devel/astroquery/astroquery/xmatch/core.py(62)query()
     60         response = self.query_async(cat1, cat2, max_distance, colRA1, colDec1,
     61                                     colRA2, colDec2, cache=cache)
---> 62         return ascii.read(response.text, format='csv')
```

**Comment by keflavich** [comment]
Interesting... I wonder if xmatch changed something, or if there is some parameter (output table type) not being set correctly any more?

**Comment by bsipocz** [comment]
Weird looking at the result it's an error rather than a data containing votable, but the payload still seems to be valid according to their API documentation.

``{'distMaxArcsec': 5.0, 'colRA1': 'ra', 'RESPONSEFORMAT': 'csv', 'colDec1': 'dec', 'cat2': 'vizier:II/246/out', 'REQUEST': 'xmatch'}`` vs http://cdsxmatch.u-strasbg.fr/xmatch/doc/API-calls.html

Maybe it's a red herring but the response seems to complain about the input catalog:
```
ipdb> response.text
'<?xml version="1.0" encoding="UTF-8"?>\n<VOTABLE version="1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ivoa.net/xml/VOTable/v1.2"  xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.2">\n\t<DESCRIPTION>\n\t\tSynchronous version of the CDS XMatch Service.\n\t\tGenerated by the CDS XMatch engine.\n\t\tPlease report any problem to:\n\t\t - francois-xavier.pineau@astro.unistra.fr or\n\t\t - thomas.boch@astro.unistra.fr or\n\t\t - cds-question@unistra.fr\n\t</DESCRIPTION>\n\t<INFO name="queryParameters" value="7">\n\t\tresponseformat=CSV\n\t\tdistmaxarcsec=5.0\n\t\tcoldec1=dec\n\t\tcolra1=ra\n\t\trequest=xmatch\n\t\tcat2=vizier:II/246/out\n\t\tcat1=cat1\n\t</INFO>\n\t<INFO name="EXPLAIN" value="USAGE">\n\t\t request=xmatch\n\t\t cat1|2=NAME|URL|FILE (NAME = simbad|vizier:II/246/out)\n\t\t colRA1|2=colName\n\t\t colDec1|2=colName\n\t\t distMaxArcsec=5 (max=180.0)\n\t\t responseFormat=[CSTP]SV|VOTABLE|JSON\n\t\t ? cols1|2=col1,col2,col3\n\t\t ? selection=best|all (default = all)\n\t\t ? maxRec=LONG (default = 2000000)\n\t</INFO>\n\t<RESOURCE type="results">\n\t<INFO name="QUERY_STATUS" value="ERROR">\n\t\t Message: An error occurs while trying to read the table &quot;cat1&quot;data\n\t\t Trace:\njava.lang.Exception: An error occurs while trying to read the table &quot;cat1&quot;data\n\tat cds.xmatch.servlet.SyncXMatch.getXMatchDataSet(SyncXMatch.java:412)\n\tat cds.xmatch.servlet.SyncXMatch.exec(SyncXMatch.java:720)\n\tat cds.xmatch.servlet.SyncXMatch.doPost(SyncXMatch.java:466)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:646)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:727)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)\n\tat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)\n\tat org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:190)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)\n\tat org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2442)\n\tat org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2431)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.io.EOFException\n\tat uk.ac.starlink.fits.AbstractArrayDataIO.readFully(AbstractArrayDataIO.java:194)\n\tat uk.ac.starlink.fits.AbstractArrayDataIO.readFully(AbstractArrayDataIO.java:285)\n\tat uk.ac.starlink.votable.FitsPlusTableBuilder.readMetadata(FitsPlusTableBuilder.java:206)\n\tat uk.ac.starlink.votable.FitsPlusTableBuilder.makeStarTable(FitsPlusTableBuilder.java:83)\n\tat uk.ac.starlink.table.StarTableFactory.makeStarTable(StarTableFactory.java:375)\n\tat uk.ac.starlink.table.StarTableFactory.makeStarTable(StarTableFactory.java:501)\n\tat cds.xmatch.servlet.SyncXMatch.getXMatchDataSet(SyncXMatch.java:410)\n\t... 25 more\n\n\t</INFO>\n\t</RESOURCE>\n</VOTABLE>\n'
```

**Comment by keflavich** [comment]
The input catalog might no longer be compatible... seems like this needs some real attention to get fixed.

**Comment by bsipocz** [comment]
Thanks @keflavich!

**Pull request merged**
