### PR TITLE
Add new Gallery example and utilities for ALMA

### PR DESCRIPTION
**Pull request by keflavich**
In preparation for the ALMA deadline... a nice example showing ALMA primary beam FOVs overlaid on a 2MASS image

### CODE REVIEW

**Comment by keflavich** [comment]
I can't reproduce any of the failures locally.  What happened to the configuration system?!

**Comment by keflavich** [comment]
@astrofrog - do you have any clues about what broke here?  I didn't make any changes in astroquery that were relevant, but something in the astropy config system changed, and I don't understand what it is.  I looked into this last week but had to give up on it for lack of time.

**Comment by keflavich** [comment]
@mdboom this has become the merge point for the broken configuration system in astroquery.  I'm completely lost about how some of the errors are coming about; it looks like configurations in some sub-packages are being read by other sub-packages.  Tom R pointed me to you - if you have any tips for cleaning up a gigantically broken config system, I could use them.

**Comment by mdboom** [comment]
The configuration system was overhauled in version 0.4, but the pre-0.3 API is still present and should work, although it emits AstropyDeprecationWarnings.

It's possible that https://github.com/astropy/astropy/commit/7186664e777153f5f0d735aee9f09a1bf4c1c5db inadvertently broke things for people on the old config API.  You could experiment with reverting that change to see if it resolves things for you.  If so, let me know, and I'll revert it over on astropy master.

ced65d5 doesn't make much sense to me -- where are the kwargs `defaultvalue` coming from?  (astropy doesn't have such a string anywhere).

I'd start here for info about how to move from the old to the new API:

http://docs.astropy.org/en/stable/config/config_0_4_transition.html

**Comment by keflavich** [comment]
Thanks @mdboom.  Everything on astroquery builds fine on 4f6b9b18160d21fd9627feb041941e87ff8ac51c, at least on astroquery/master.

I don't really know where some of the config items are coming from... I'll blame them, and if it's from me, then it was a different me.

**Comment by keflavich** [comment]
@mdboom the `defaultvalue` keyword is right in ConfigItem (https://github.com/astropy/astropy/blob/master/astropy/config/configuration.py#L223)

**Comment by mdboom** [comment]
Sorry for the confusion about `defaultvalue` -- not sure what I did wrong there.

I'll fix the problem created in astropy/astropy@7186664 on astropy master.  That should fix the legacy configuration API.  You can then migrate to the new API when ready rather than under duress :)

**Comment by mdboom** [comment]
See astropy/astropy#3627.

**Comment by keflavich** [comment]
@mdboom - I think I have migrated to the new API in #501 but I am getting some errors I really don't understand with configurations from one submodule showing up in another.

**Pull request merged**
