### PR TITLE
Removed name mangling for test variable

### PR DESCRIPTION
**Pull request by imbasimba**

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @imbasimba, and also to do the fixes the bot suggested. Please let me know any suggestions (we've just started using it), whether you found it too nitpicky, etc. Currently we let it comment on almost any pep8 issues it finds, while only a handful of those will make travis fail.

**Comment by imbasimba** [comment]
@bsipocz Some kind of code analyzer is definitely needed on a project like this, where the contributors have vastly different backgrounds. Personally though, I find the "no white space at the end of the line"-rule a bit tedious. Especially when it is combined with rules forcing many method calls to be like this:
method(
parameter1,
parameter2,
parameter3)

**Comment by imbasimba** [comment]
@bsipocz @keflavich Sorry to be pushy, but integrating this change as soon as possible would really help the ESASky project :) Integrating this change would give us accurate statistics of the real usage of this module.

**Comment by bsipocz** [comment]
@imbasimba - I'm sorry @imbasimba, looks like the appveyor failure was unrelated so merging now. 

Regarding the next release, I'm not sure when that will be. I'm sure there will be one once the new NOAO module is ready to go, it is being worked on atm by our GSoC student.  pinging @keflavich what he thinks about a bugfix.

**Comment by imbasimba** [comment]
@bsipocz @keflavich No rush to get it into a new release! As long as the dev server has this code, we should get pretty accurate statistics :)

**Comment by bsipocz** [comment]
@imbasimba - Actually I have no best guess how many users we have for the dev version, so your measurement will be quite interesting for us, too.

**Comment by keflavich** [comment]
We'd be very interested in hearing about usage stats!

@imbasimba If you ever need something merged urgently, feel free to say so in the PR like you did above.  Even if it's not urgent, it's helpful to say something like "ready for final review" or "ready to be merged" so we know you're done working on it.

**Pull request merged**
