### PR TITLE
astroquery.mast TESS input catalog fix

### PR DESCRIPTION
**Pull request by ceb8**
The bulk of this PR is a bugfix for MAST's TIC functionality, but a few other small things are included.

Changes:
- Fixed bug in TIC catalog criteria queries by:
  - Updating service string to reflect database changes
  - Updating the _get_col_config function
- Made catalog names case insensitive for criteria queries
- Put in decorations to temporarily skip the tesscut tests
  I will remove these in a separate PR after the service goes live, and also get rid of the checking code (that didn't really work anyway unfortunately)
- Fixing the mock_download function so it works with the new auth changes 
- Adding decoration to temporarily skip the session info test which is broken
  Will make an issue to fix that, but it will come in in a separate PR

### CODE REVIEW

**Comment by ceb8** [comment]
@bsipocz @adamginsburg I'm a little at sea with the current travis failure.  It seems to be in the coverage test, but I'm not getting a coverage map so I am just guessing what is missing coverage. I put in `# pragma no cover` on all the functions where I had to disable the tests (not best practice I know, but I promise there will be forthcoming PRs dealing with it), so I don't know what else to do.  Going through to the travis log, I don't see any errors even thought the test fails. Ideas?

**Comment by keflavich** [comment]
@ceb8 it's this issue: https://github.com/astropy/astroquery/pull/1300

**Comment by ceb8** [comment]
@bsipocz Github won't let me approve my own PR, but this one is ready to merge when it passes the tests.

**Comment by pllim** [comment]
Not sure what is going on here but at least it does not segfault this time! 😬 
```
_____________________________ test_args_to_payload _____________________________
    def test_args_to_payload():
        out = irsa.core.Irsa._args_to_payload("fp_psc")
>       assert out == dict(catalog='fp_psc', outfmt=3, outrows=conf.row_limit)
E       AssertionError: assert {'catalog': '...'selcols': ''} == {'catalog': 'f...outrows': 500}
E         Omitting 3 identical items, use -vv to show
E         Left contains more items:
E         {'selcols': ''}
E         Use -v to get the full diff
astroquery/irsa/tests/test_irsa.py:82: AssertionError
```

**Comment by ceb8** [comment]
@pllim  Argh, that's not even a mast test!

**Comment by jgagneastro** [comment]
That would make sense yes. Sorry it didn’t come to my mind to check the test.

Jonathan
------
PhD, Astrophysics
Banting Postdoctoral Fellow
Institute for Research on Exoplanets
Université de Montréal
2900 Boulevard Édouard-Montpetit
Montréal, QC H3T 1J4
Phone : 514-343-6111‬#7077
Email : jonathan.gagne@astro.umontreal.ca
------

**Comment by keflavich** [comment]
I fixed the broken test in #1303, and it was my fault for merging w/a  broken test in place

**Comment by bsipocz** [comment]
Unrelated test failures should have been fixed in master. I've rebased since this had a conflict.

**Comment by bsipocz** [comment]
@astrofrog - I've just rebased this, so it's weird that the bot config is not picked up here?

**Comment by bsipocz** [comment]
Thanks @ceb8!

**Pull request merged**
