### PR TITLE
Added selcols keyword to astroquery.irsa

### PR DESCRIPTION
**Pull request by jgagneastro**
Added selcols keyword to astroquery.irsa allowing to select subsets or extra columns from IRSA tables

### CODE REVIEW

**Comment by keflavich** [comment]
This mostly looks fine.  Could you add something to the docstring to explain the format of `selcols`?  e.g., include an example of what columns could be selected.  It would also be helpful to link to IRSA's documentation on this parameter.  Is the selcols argument specified somewhere in their docs?

For our reference, this is a fix for Issue #766

**Comment by jgagneastro** [comment]
By docstring do you mean the comment header in core.py ? If so, I’ve already done both of these things. Otherwise, I can add this info if you point me where that docstring is located

**Comment by keflavich** [comment]
Yes, that's what I mean, at least in part.  It would also be helpful to add something to the prose documentation:
https://github.com/astropy/astroquery/blob/master/docs/irsa/irsa.rst

However, as far as I can tell, you have not made any changes to the docstring (the commend section below the function definition) for any functions in `irsa/core.py` in this pull request.  Check that you committed the change?

**Comment by jgagneastro** [comment]
Oh wow, indeed I lost them somewhere along the way. I’ll fix this asap

**Comment by jgagneastro** [comment]
I just added back the header comments about selcols

**Pull request merged**
