### PR TITLE
Remove duplication from SDSS

### PR DESCRIPTION
**Pull request by keflavich**
There is some duplication in the SDSS class in query_crossid(), it would be nicer to change ``_args_to_payload`` to create a payload for the crossid api and not just the sql api.

### CODE REVIEW

**Comment by keflavich** [comment]
Um... I screwed up.  This PR has *nothing* to do with the issue.  I just got the issue ID incorrect using `hub`.  Any idea how to undo this?

**Comment by keflavich** [comment]
Still trying to figure out how to fix this: http://stackoverflow.com/questions/29866288/detach-a-pull-request-from-an-issue.  For now, I'll try the workaround approach...

**Comment by bsipocz** [comment]
@keflavich - No idea how this can be redone, maybe the best to edit the title and description and I open a new issue for the original one.

**Comment by bsipocz** [comment]
(maybe one other approach to remove the commits is to rebase against master and remove them there, but that means you need to copy them over to another branch first)

**Comment by keflavich** [comment]
@bsipocz could you open a new issue with the exact same content?  Apparently there's no way to fix this.

**Comment by keflavich** [comment]
oh you did, sorry

**Pull request closed without merging**
