### PR TITLE
NXSAPCR-1197: minor fix

### PR DESCRIPTION
**Pull request by toniorte**
Hello Astroquery team,

This is a minor fix for [PR 2910](https://github.com/astropy/astroquery/pull/2910), as it was processing PNG files as FITS, and it was failing under those cases.

Thanks in advance for your support.

C.c. @esdc-esac-esa-int

### CODE REVIEW

**Comment by jespinosaar** [comment]
Hi @bsipocz , this is a bug we detected after my PR was merged this morning. It is a very simple change, just filtering the files in a tar and skipping the images. Thanks!

**Comment by jespinosaar** [comment]
Please let us know if you prefer to do it in a different way.

**Review by bsipocz — APPROVED** [review]
Thanks!

**Comment by bsipocz** [comment]
The dev version CI job has issues due to upstream astropy and numpy compatibility issues, most likely you can ignore all those failures for these PRs.

**Comment by jespinosaar** [comment]
That was fast, many thanks! And congratulations to @toniorte for his first contribution to Astroquery! Is there any pre-released version for this?

**Comment by bsipocz** [comment]
I'll see how many more PRs I can merge in the next hour or two, after that I'll push a new pre-release.

**Comment by bsipocz** [comment]
Release is here: https://pypi.org/project/astroquery/0.4.7.dev9069/

**Pull request merged**
