### PR TITLE
WIP: add basic SOFIA query tool

### PR DESCRIPTION
**Pull request by keflavich**
Solves #2232, but very much a WIP.   I've gotten the server to return data, finally, but I haven't parsed it yet.

### CODE REVIEW

**Comment by bsipocz** [comment]
@keflavich - We've briefly discussed this, and would prefer to have one layer flatter namespace for the different irsa services, e.g. have astroquery.ipac.irsa.Irsa to handle the generic services based on tap, sia, etc, but have the one-off ones in this namespace, too, e.g. `astroquery.ipac.irsa.Most` and `astroquery.ipac.irsa.Sofia` I know that ibe and sha currently is one layer down, but those are legacy services that got moved unto astroquery.ipac.irsa from the main namespace.

**Comment by keflavich** [comment]
Right, I forgot about that.   Moved.

**Comment by bsipocz** [comment]
(also, something went wrong with the move, and now you've deleted all the files rather than moved them)

**Comment by keflavich** [comment]
:facepalm: added it back.

But it might be a good idea to keep this one separate within this space because the implementation is so different?  I'm ok either way; I'm not sure when I'm going to finish this though.

**Comment by bsipocz** [comment]
My thinking is these are all IRSA services, and the added namespace doesn't really adds much. I would not suggest to add support for any of the mission specific services in the `Irsa()` class, but to not have an additional layer such as `astroquery.ipac.irsa.sofia.Sofia()`, but expose it directly in `astroquery.ipac.irsa.Sofia()`

**Comment by bsipocz** [comment]
As for docs, having a separate sofia.rst would be nice, and I'll suggest chopping up mast.rst, too.

**Comment by keflavich** [comment]
Ah, ok, I can lower the namespace a level.  I think it's helpful to have `sofia.py` though.

and yes, sofia.rst for docs sounds good

**Comment by bsipocz** [comment]
>  I think it's helpful to have sofia.py though.

Yeap, each service class should have its own file. I'll do an audit on sha and ibe, too, if they will still be needed after we switch to the VO backends, I think they should also be exposed in the `irsa` namespace.

**Comment by bsipocz** [comment]
@keflavich - FYI: SOFIA datasets are getting moved to be served by the VO backends, so they will be available using the generic `irsa` module (at least the images will be available, we don't yet have an SSA layer, but if needed that can be done and is preferred as opposed to a custom sofia only tool). I would suggest this module won't be necessary and the PR should eventually be closed without merging.

**Comment by bsipocz** [comment]
FYI: SOFIA via VO tools is coming soon, so I expect most things to work out of the box with the current IRSA module. So, the most useful thing would be to come up with use cases that we can add to the narrative documentation as well as to the tests.

**Comment by bsipocz** [comment]
SOFIA is landed in the VO backends, so I'm closing this now. 

Please try and play with it, and add examples to the IRSA docs (or if there are too many of them, we can break it out to a separate page, but nevertheless using TAP and SIA you should be able to access most of the data (and I'm actively adding SSA methods, so the spectral examples will be covered very soon, too.).

**Pull request closed without merging**
