### PR TITLE
` return_submission_id` option added to astrometry_net monitor_submission.

### PR DESCRIPTION
**Pull request by prajwel**
Addresses issue #2335. Implements suggestion by @mwcraig (https://github.com/astropy/astroquery/pull/2336#issuecomment-1331185367).

### CODE REVIEW

**Comment by bsipocz** [comment]
Would be nice to have a test for this, even though we cannot really run the tests from CI. Thanks.

Also, cc @mwcraig to ask whether he could review/wrap-up this and the other astronomy_net PR. Thanks!

**Comment by prajwel** [comment]
I have added tests.

**Review by mwcraig — CHANGES_REQUESTED** [review]
Thanks for the PR, @prajwel, and apologies for the long delay in reviewing it.

It looks like it needs one change -- the `return_job_id` keyword should be added to the argument list [here](https://github.com/astropy/astroquery/pull/2685/files#diff-1b4e2fa6e8440300c09f3bd20ad98ddf812800e805a8b5bb3c480d64b6154f92R444-R450). Right now the job id is not returned if the plate solve is done from an image but the image is not uploaded.

**One questions:** should the name of the argument be changed from `return_job_id` to `return_submission_id`? As you allude to in the comments in the code you added, an astrometry.net solve has both a "Submission ID" and a "job id" (see screenshot below) and it is really the submission ID that we need and are returning. 

Astrometry_net

**Comment by mwcraig** [comment]
@bsipocz -- I think the other PR that addresses this, #2336, should be closed in favor of this PR. This one implements the functionality requested in #2335 but preserves backwards compatibility.

**Comment by prajwel** [comment]
> Thanks for the PR, @prajwel, and apologies for the long delay in reviewing it.
> 
> It looks like it needs one change -- the `return_job_id` keyword should be added to the argument list [here](https://github.com/astropy/astroquery/pull/2685/files#diff-1b4e2fa6e8440300c09f3bd20ad98ddf812800e805a8b5bb3c480d64b6154f92R444-R450). Right now the job id is not returned if the plate solve is done from an image but the image is not uploaded.
> 
> **One questions:** should the name of the argument be changed from `return_job_id` to `return_submission_id`? As you allude to in the comments in the code you added, an astrometry.net solve has both a "Submission ID" and a "job id" (see screenshot below) and it is really the submission ID that we need and are returning.
> Astrometry_net

If I remember correctly, the "submission ID" is not particularly useful. Only "Job ID" can be used for accessing astrometry.net output files. Also, Astroquery makes use of "Job ID" internally, not "Submission ID". I think there has been a confusion between "Submission ID" and "Job ID".

**Comment by prajwel** [comment]
@mwcraig Thank you very much for your careful review. I made a mistake. I intended to return the "Job ID"; however, the `return_job_id` returns the "Submission ID". I am sorry if it created unnecessary confusion. 

I will implement the following changes you suggested. 
1. Change  `return_job_id` to  `return_submission_id`. 
2.  Add `return_submission_id` keyword to the [location](https://github.com/astropy/astroquery/pull/2685/files#diff-1b4e2fa6e8440300c09f3bd20ad98ddf812800e805a8b5bb3c480d64b6154f92R444-R450) you suggested.

**Review by mwcraig — APPROVED** [review]
Thanks @prajwel, this looks great!

@bsipocz -- I tested the changes manually. The tests won't run with pytest at the moment because `astrometry_net` is using the `photutils` API from 0.4 or 0.5 😬. Opening a separate PR to fix that momentarily...

**Review by bsipocz — COMMENTED** [review]
This will need a changelog entry, but otherwise I'll merge it with the approval above.

**Comment by bsipocz** [comment]
Thanks @prajwel!

**Pull request merged**
