### PR TITLE
Feature Request: ADS queries

### PR DESCRIPTION
**Pull request by keflavich**
See https://github.com/jonathansick/ads_bibdesk: the python component can certainly be adapted into astroquery

### CODE REVIEW

**Comment by keflavich** [comment]
@vilhelmp I have started merging in the `adslib` tool you wrote.  It could use quite a bit of cleanup but it works on a basic level.  

We need to do at least the following:

 * [ ] Add a useful set of keyword arguments and some keyword validation
 * [ ] Parse the result into an astropy Table

Please add to this list and add PRs onto the [`ads_vilhelmp`](https://github.com/keflavich/astroquery/tree/ads_vilhelmp) branch

**Comment by vilhelmp** [comment]
Oh, I already added ADS search to my fork of Astropy. However I partly rewrote stuff in trying to learn how to contribute properly. It is in my fork. For the basic functionality all I have left is to get the results into a Astropy Table. Instead of parsing HTML I now request the XML directly, then I am not relying on Beautiful soup, only the built in XML DOM inspector.

Due to massive amounts of work, I haven't had the time to finish it up and do a pull request, I will see if I get the time today.

**Comment by vilhelmp** [comment]
Also, as this is the first version it is rather simple. Only the single field search is available. As you say there are things to do:
* Parse results into astropy table
* Add advanced search with different filers (year interval, title, author)
* Add a mirror-checking, ADS have several mirrors (now just in the Conf variable)
* Perhaps add some nice analysis function, relating to e.g. h-number, no citations
* PDF download
* Get PDF through proxy?

**Comment by vilhelmp** [comment]
OK, so I fixed it now. In my fork of astroquery, I have nasa_ads as a search provider. It gets the XML results from the simple query tool, and parses the results into a astropy.Table table. No test is set up, and no interface to the advanced search is set up (http://adsabs.harvard.edu/abstract_service.html). However, that should be simple now that we can parse the results XML page.

**Comment by keflavich** [comment]
OK @vilhelmp can you make that into a separate PR then?

**Comment by bsipocz** [comment]
@vilhelmp, @keflavich - Is there any open issues with this PR? It looks close to be ready to me.

**Comment by keflavich** [comment]
@vilhelmp I think this is closed by #499?  I'm closing this because we definitely have the feature in now.  Sorry about the delay @bsipocz, I just didn't realize.

**Comment by vilhelmp** [comment]
Yes, you are right. It should be closed.

**Comment by bsipocz** [comment]
@keflavich - Ohh, I missed #499 so it's good to see it's already in there.

**Pull request closed without merging**
