### PR TITLE
Customize astropy-bot configuration to specify changelog filename

### LINKED ISSUE #1290: Fix changelog bot
our changelog has a different name

cc @pllim or @astrofrog in case they got here with a fix quicker

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes #1290 

(might not work yet, so WIP, but don't want to label as WIP since I need to test the bot...)

### CODE REVIEW

**Comment by astrofrog** [comment]
Fix forthcoming in astropy-bot: https://github.com/astropy/astropy-bot/pull/98

**Comment by astrofrog** [comment]
It looks like this works now, as it is just complaining about the PR number being missing, not the changelog file.

**Comment by pllim** [comment]
@astrofrog , isn't the bot supposed to post comment about "see below for checks"? I don't see that comment here.

**Comment by astrofrog** [comment]
@pllim - no, that's only when it commented in the past and we had to edit the comment. There is no comment by default.

**Comment by pllim** [comment]
@astrofrog --- Oh, so that means no more "special message"? :cry:

**Comment by astrofrog** [comment]
@pllim - packages can opt-in to the comment behavior of course, it's still a supported option. But we could make the special message be a special status instead for the current behavior? :) The commenting stuff is just broken at the moment due to some GitHub issue which causes comments to be shown multiple times.

**Comment by bsipocz** [comment]
@pllim @astrofrog - it's off topic here, but for special day special messages we can certainly override the no commenting thing and just start commenting on repos ;) Multiple comments then would be a fun feature rather than a bug....

**Comment by bsipocz** [comment]
@astrofrog - on topic: it's complaining about the missing changelog file. Is that correct that the bot doesn't take into account the diff in a PR? E.g. we need to merge this to fix the issue, there is no way it figuring out that this very PR changes the bot's settings?

**Comment by astrofrog** [comment]
Huh wait it worked just now, not sure why it changed back to not working...

**Comment by astrofrog** [comment]
@bsipocz - fixed. Not sure what happened there. Yes normally it should only read the config from the master branch but I temporarily changed it to not.

**Comment by bsipocz** [comment]
Ohh. But then what about https://github.com/OpenAstronomy/baldrick/issues/41#issuecomment-441747421?

Anyway, thank you very much for this fix, I'm merging this now.

**Comment by astrofrog** [comment]
@bsipocz - I changed it in astropy-bot to read from the PR config for this specific plugin. But I'll change it back.

**Pull request merged**
