### PR TITLE
TST: Fix vo_conesearch test failures

### LINKED ISSUE #2054: vo_conesearch errors with astropy-dev
There are quite a few errors coming for `astroquery.vo_conesearch` when testing with the current dev version of astropy

See: https://github.com/astropy/astroquery/pull/2050/checks?check_run_id=2500552000

(and also there are a ton of warnings, but maybe we can ignore those...)

### PR DESCRIPTION
**Pull request by pllim**
~I am not sure if I am seeing the same failures locally, so I am going to smoke it out in a PR.~

I think I fixed it. Let's see what CI says. Also see astropy/astropy#10434 . Fix #2054

# TODO

- [x] Drop temporary commit(s).

### CODE REVIEW

**Comment by pllim** [comment]
whoops... My patch to monkeypatch isn't backward compatible.

**Comment by pllim** [comment]
These 12 lines took way too much time. 😆 😭  Anyways, tests pass now.

**Comment by bsipocz** [comment]
Thanks @pllim! 

would you mind opening as issue about the monkeypatch refactor?

**Comment by pllim** [comment]
Issue opened at #2063

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
A million thanks @pllim!

**Comment by embray** [comment]
Thank you!

**Pull request merged**
