### PR TITLE
Stop using astropy.utils.compat.concurrent.futures for Python 3

### LINKED ISSUE #974: What is astroquery's plan of dropping Python 2 support?
I need to fix some imports to replace `astropy.utils.compat.futures`, which is deprecated in astropy/astropy#6598, in `vo_conesearch` here. *How* I fix it depends on Astroquery's plan with Python 2 support going forward. Please advise.

### PR DESCRIPTION
**Pull request by pllim**
Fix #974

### CODE REVIEW

**Comment by keflavich** [comment]
It's not obvious whether [this](https://travis-ci.org/astropy/astroquery/jobs/281310879#L1816) is a real failure: 
```
___________________________ test_filecontainer_save ____________________________
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <urllib.request.Request object at 0x7f972ac5d048>
    def _parse(self):
        self.type, rest = splittype(self._full_url)
        if self.type is None:
>           raise ValueError("unknown url type: %r" % self.full_url)
E           ValueError: unknown url type: '/tmp/astroquery-test-oe3flu_w/lib.linux-x86_64-3.6/astroquery/utils/tests/../../sdss/tests/data/emptyfile.fits'
/home/travis/miniconda/envs/test/lib/python3.6/urllib/request.py:384: ValueError
======== 2 failed, 564 passed, 284 skipped, 68 xfailed in 32.41 seconds ========
```

I'm going to try to restart it

**Comment by pllim** [comment]
That's weird. I didn't even touch `sdss`.

**Comment by keflavich** [comment]
I can reproduce it locally.

**Comment by keflavich** [comment]
It appears to be an astropy issue of some sort.  It only affects astropy-dev.  @bsipocz, it looks like this might be a side effect of the py2 removal, though I can't see how.

**Comment by pllim** [comment]
Somehow it is treating those as URL and tries to download them.

**Comment by pllim** [comment]
Must be something that is incompatible in https://github.com/astropy/astroquery/blob/master/astroquery/utils/commons.py#L334 . It is not related to what I am trying to fix though.

**Comment by keflavich** [comment]
Yeah, it's not related to what you've done, I think.  It's not an astropy error, though - `download_file` never worked on non-URLs (I tested against astropy 2.0.2).  Something changed in commons?

**Comment by keflavich** [comment]
the problem is in `astropy.utils.data._is_url` - it is returning `True` incorrectly

**Comment by pllim** [comment]
How so? I tested `_is_url` locally on a file and it worked. Do you have a reproducible snippet?

**Comment by keflavich** [comment]
No.  It's weird.
```python
(Pdb) name_or_obj
'/private/var/folders/_r/c4nkvmpn4vx6qc91qygz8h740000gr/T/astroquery-test-9k71ag_r/lib.macosx-10.6-x86_64-3.5/astroquery/utils/tests/../../sdss/tests/data/emptyfile.fits'
(Pdb) _is_url(name_or_obj)
True
(Pdb) urllib.parse.urlparse(name_or_obj).scheme.lower()
''
```
so `_is_url` is returning `True`, even thought the internals of `_is_url` *definitely* should be returning `False`....

**Comment by keflavich** [comment]
maybe we unwittingly monkeypatched this function somewhere?

**Comment by keflavich** [comment]
yep, that's it.

**Comment by keflavich** [comment]
I wish I had left comments about *why* monkeypatching that was necessary, because I bet it was...

**Comment by keflavich** [comment]
alright, so the deal is that we need the file on disk to be treated as a URL so that the caching operation is performed - the whole idea of this test (`test_utils.test_filecontainer_save`) is to make sure the download/caching/loading from cache operations all work nicely.

*Something* has changed, though.  Apparently `urllib.request.open` used to, at some point, be able to open local files on disk?  But it can no longer do that?

**Comment by keflavich** [comment]
Also changing from `_open_shelve` to `shelve.open` breaks python2, which I don't want to do.  Argh.

**Comment by bsipocz** [comment]
Hmm, I'm sorry to see this thread. It seems that most things got figured out, let me know if there is still something I could do.

**Comment by keflavich** [comment]
in the PR onto this, I added `_open_shelve` to astroquery (I don't know why it's necessary but it appears to be....) and added a second layer of monkeypatching on `urllib.urlopen`.  Again, I don't understand the need, but maybe it has to do with order-of-imports in py3?  or in `astropy.utils.data`?  In any case, monkeypatching `urllib.urlopen` wasn't good enough, I also had to monkeypatch `aud.urllib.urlopen`

**Comment by pllim** [comment]
For Python < 3.4, you need the astropy version of open shelve, see astropy/astropy#2040 . Not sure about `urllib` but it is split into multiple modules in Python 3.

**Comment by bsipocz** [comment]
Yes, the ``_open_shelve`` got removed from astropy along with the other python2 stuff. However it's weird why it stopped working here, as for py2.7 we cannot really use the latest dev anyway.

**Comment by keflavich** [comment]
I've confirmed that my changes fix this, so I'm going to merge via #977

**Comment by pllim** [comment]
Weird. I opened this PR but I don't see option to delete branch.

**Comment by bsipocz** [comment]
you can always delete it from the command line:
``git push pllim :compat-futures`` assuming the remote of your fork is named pllim

**Pull request merged**
