### PR TITLE
Accept astropy Table as upload_resource

### PR DESCRIPTION
**Pull request by smoh**
This is my attempt to address #1257 with the least change. The goal is to be able to use astropy Table instance directly to upload. Currently `launch_job(_async)` can only handle filename with the file containing table in VOTable format.

A minimal example to test the feature (although it relies on the actual Gaia server):
```python
from astroquery.gaia import Gaia
from astropy.table import Table
table = Table({'a':[1,2,3], 'b':[4,5,6]})

r = Gaia.launch_job("select * from TAP_UPLOAD.mytable",
    upload_resource=table, upload_table_name='mytable')
```

I am happy to modify or add documentation/tests as needed but just wanted to see if the maintainers are open to it first.

### CODE REVIEW

**Comment by keflavich** [comment]
I think this is a great idea, thanks for making it!

It needs a test.  It would also be great to add this feature for other tools that allow file uploads.  We can add a list of those to the Issue.

**Comment by jcsegovia** [comment]
@smoh thanks for implementing this. However, we have evolved the code in order to work with different sources, for instance, our changes allow the user to work with a job results, a URL, a Table and the original one: a file.
Do you mind if we reject your changes? 
It is going to be complicated if we need to merge our changes with yours.
Thanks again.

**Comment by smoh** [comment]
No problem, looking forward to it. A reminder to close #1258 when this is implemented.

**Comment by bsipocz** [comment]
@jcsegovia - do you have an ETA when to push those changes to astroquery? It would be really nice to have the development process out in the open, so people can comment on it early on.

**Comment by keflavich** [comment]
@jcsegovia If there's a big code change forthcoming, we strongly prefer to have a pull request labeled "WIP" (so we know not to merge it right away).  This PR is an important case: a user has made a contribution that is apparently obsolete, but they had no prior way to know that.

**Comment by jcsegovia** [comment]
@keflavich Thanks, I will label our pull request with 'WIP'. But I think I have to wait for #1255 to be integrated because we have updated also the core module of TAP. There are going to be conflicts that need to be solved before we execute a PR.

**Comment by keflavich** [comment]
You could always merge that one into your branch or rebase against that branch after opening the WIP PR.  But, I agree, it will be best to have that one merged before doing major review.

**Comment by bsipocz** [comment]
> Rather than doing local merges, I would rather merge it here in the main repo, and then you can rebase. This was we can ensure proper crediting to all authors being involved.

**Comment by keflavich** [comment]
@bsipocz With #1255 merged, that's straightforward, but is there really any issue with branching off of a branch?  I thought that would be fine?

**Comment by bsipocz** [comment]
Ohh, sorry, you're totally right. I'm just a bit behind with my notifications, haven't noticed that.

**Comment by jcsegovia** [comment]
@keflavich @bsipocz  We are merging the changes. I think we are going to need a day o two to create the PR.

**Pull request closed without merging**
