### PR TITLE
Creating ESA subpackage to hold esa packages in the namespace

### PR DESCRIPTION
**Pull request by bsipocz**
Currently the only critical thing for the 0.3.10 release is to put the esa_hubble module into the new namespace, the rest of the modules already exist at the top level so  their move is  not super urgent.

The only remaining questions is whether to rename `esa_hubble` to `hubble`? I would slightly prefer not to, but am open to hear arguments for it, too.

This is the only blocker on 0.3.10, otherwise there are a small cleanups being left and we can tag the release.

### CODE REVIEW

**Comment by keflavich** [comment]
`esa.esa_hubble` seems a bit redundant; `esa.hubble` has nice symmetry w/`esa_hubble`, and nicely promotes the usage of `from astroquery.esa import hubble as esa_hubble`.  But, I don't feel too strongly about this.

**Comment by bsipocz** [comment]
Yes, my only reservation with `esa.hubble` is that when it's not used as you suggested, but as `from astroquery.esa import hubble` then it becomes ambiguous. Though of course it's not as mast is called mast rather than hubble. But you see my dilemma. (I also don't feel strongly about it, maybe just overthinking it a bit.)

**Comment by keflavich** [comment]
Yes, but from that perspective, we should require that `mast.hubble` be `mast.mast_hubble`.

**Comment by bsipocz** [comment]
Yes, indeed we would need to do that, except we don't have `mast.hubble`, and anyway, that's the canonical source, isn't it?

**Comment by keflavich** [comment]
Eh, that's a bit of a politically charged statement, no?

**Comment by bsipocz** [comment]
Yeah, you're right, amended it.

**Comment by keflavich** [comment]
yeah, I think we just need to encourage people to use the `from <parent> import <child> as <parent>_<child>` approach and put that into examples.

**Comment by bsipocz** [comment]
But the so far we encourage to do:
```
from parent.child import Class
child = Class()
```

in this example that would be, which is not ideal. Keeping it esa.esa_hubble would be more consistent with other, non nested modules.
```
from esa.hubble import EsaHubble
hubble = EsaHubble()
```

**Comment by keflavich** [comment]
I like that latter example, but:
```
from esa.hubble import EsaHubble
esahubble = EsaHubble()
```

**Comment by bsipocz** [comment]
Haha, I suppose we're at a standoff then.

If no one else chimes in, I'll add another commit in the coming days to change it to `hubble` as you preferred, and then hopefully can finish off the release on Thursday, or Friday the latest.

**Comment by bsipocz** [comment]
OK, this is now changed to `esa.hubble`, but also the examples are updated to use the recommendation from https://github.com/astropy/astroquery/pull/1534#issuecomment-523190189

**Pull request merged**
