### PR TITLE
Fixed login issue.

### PR DESCRIPTION
**Pull request by agroener**
This PR contains fixes for:
1) The observed login issue, 
2) Updated dict.keys() issue which prevented tags from being searched for (containing namespaces)
3) And restored check_all_jobs/delete_all_jobs basic functionality.

There are still numerous issues w/ the basic functionality, but it is less broken than it was before. Little by little I intend to fix everything.

Interesting notes:
-> In python3 dict.keys() does not return a list; rather, it returns a dict_keys() object which yields values when you iterate over it.
-> The CosmoSim jobid is now stored as an attribute in the jobref tag, rather than in its own tag like it was before.

Both of these cases can be thought of as  "code rot", since this package has not been updated in a while.

### CODE REVIEW

**Comment by agroener** [comment]
@keflavich I noticed there is no official maintainer for this service. Mind if I take over the reigns? I would like to be more proactive with CosmoSim.

**Comment by bsipocz** [comment]
Thanks @agroener! Ideally cosmosim needs to have remote tests, so these regressions would be picked up sooner by CI rather than by our users.

I don't know about policies about "official" maintenance on the module level, for best of my knowledge we only have a handful one where the archive providers supports the astroquery module, too (e.g. esasky, gaia, mast). So by all means, please feel free to open PRs for cosmosim, or the rest of astroquery to fix or extend things.

**Comment by agroener** [comment]
My pleasure @bsipocz! I have been attempting to include tests for CosmoSim for a while now. My next PR will finally fix all of the login/logout (storing and not storing passwords in keyring) use cases, and I will be sure it includes tests.

Thanks for the invite to also contribute to the general astroquery package, too. I am definitely happy to contribute to the project if/when I have the time.

**Comment by agroener** [comment]
Also - do you guys generally hit the 'delete branch' button when a PR is merged in? Does it just delete on the remote repo and not on my local repo?

**Comment by keflavich** [comment]
@agroener yes, it deletes the remote branch, and yes, I do that.  I also occasionally delete excess local branches with `git branch --merged | grep -v "\*" | xargs -n 1 git branch -d`

**Comment by bsipocz** [comment]
(and I never delete them, but I don't really have a good reason why not, hardly ever went back to an already merged branch)

**Comment by pllim** [comment]
I delete them too (but it is never really deleted forever if you can memorize the hash, or so I heard). It comes down to personal preference. :smile:

**Pull request merged**
