### PR TITLE
Add alma.utils automodapi docs

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by keflavich** [comment]
I thought we had solved the `AttributeError: module 'distutils.config' has no attribute 'ConfigParser'` issue? https://travis-ci.org/astropy/astroquery/jobs/147460714#L561

**Comment by keflavich** [comment]
I'm merging this over the errors; they're all false-positives but may deserve their own issue.

**Comment by bsipocz** [comment]
> I thought we had solved the AttributeError: module 'distutils.config' has no attribute 'ConfigParser' issue? https://travis-ci.org/astropy/astroquery/jobs/147460714#L561

@keflavich - We did, I'll have a look at it.

**Comment by bsipocz** [comment]
Ahh, OK. So this is an upstream issue in APLpy, we need a new bugfix release of it with the fixes for the configparser. In the meantime we could use the dev version instead? What do you prefer @keflavich?

@astrofrog - Do you have time to do a quick release?

**Comment by bsipocz** [comment]
Ohh, my bad, looking at it again I've realized that we are pip installing it rather than conda (which I think should work). PR is on its way.

**Pull request merged**
