### PR TITLE
`astroquery.mast` : adding GALEX mission Cloud support

### PR DESCRIPTION
**Pull request by jaymedina**
Adding cloud support for the GALEX mission.

### CODE REVIEW

**Comment by jaymedina** [comment]
```
result = Observations.download_file(uri, cloud_only=True)
ERROR: Error pulling from S3 bucket: 'productFilename' [astroquery.mast.observations]
WARNING: Skipping file... [astroquery.mast.observations]
```

**Comment by bsipocz** [comment]
It's not much help for you for this PR, but ultimately I think we need to make these download functions a bit more generic/ or rewrite them and put into `utils`, so eventually the same approach will work for all three archives.

**Comment by jaymedina** [comment]
I think this is ready to go. It sounds like this is a high priority one, so should take precedent over https://github.com/astropy/astroquery/pull/2279 . Thanks!

**Review by keflavich — APPROVED** [review]

**Review by ceb8 — APPROVED** [review]

**Comment by ceb8** [comment]
Thanks @jaymedina!

**Pull request merged**
