### PR TITLE
Updating CADC documentation

### PR DESCRIPTION
**Pull request by migueldvb**
Some updates to the CADC documentation:

* fixing references to astroquery docs
* `cadc.run_query` is no longer supported
* `cadc.query_region` requires currently astropy quantities
* updated queries results

### CODE REVIEW

**Comment by keflavich** [comment]
@andamian , care to review?

**Comment by andamian** [comment]
@keflavich - for sure.

**Comment by andamian** [comment]
@keflavich - I've reviewed and this looks good.

@migueldvb - thank you for doing this cleanup. Next time I should probably run a spell checker before committing. :-)

**Review by bsipocz — APPROVED** [review]
reviewed and approved by @andamian, and that's good enough for me. Thanks!

**Pull request merged**
