### PR TITLE
Make automated remote test runs

### PR DESCRIPTION
**Pull request by keflavich**
It would be nice to catch remote API changes (like the one in #575),  by running the remote tests e.g. once in per week/2 weeks or similar.

@keflavich - What do you think? I'm not sure about the best optimal way to set it up, but there must be some tools for it somewhere.

### CODE REVIEW

**Comment by keflavich** [comment]
@astrofrog do you know how to tell travis to build with a specific set of parameters, i.e., get it to do a remote-data build?  I've copied over & (I think appropriately) modified the glue script you were using.  I can set up a cronjob for that, but not until I'm sure it's doing the right thing.

**Comment by astrofrog** [comment]
@keflavich - I think that you would need to either set a non-critical build as I mentioned above and just trigger that build whenever needed, or you can create a separate repository just for that purpose with a Travis config that includes remote data.

**Comment by keflavich** [comment]
OK, I think we need to go the extra-repository path: we can't have remote tests run on any branch on the main astroquery because these tests should *not* be run frequently; they can cause a severe burden for the hosting archives if run too often.

**Comment by bsipocz** [comment]
Agree with @keflavich , but I have a third idea I'm testing at the moment.

**Comment by keflavich** [comment]
@bsipocz - sounds great.  I'll close this if your 3rd idea works.  FYI, the ALMA folks restarted one of their servers earlier today, and since that happened, the ALMA timeouts have stopped for me.

**Comment by keflavich** [comment]
@bsipocz any word on your alternative approach?

**Comment by bsipocz** [comment]
Ohh, sorry. I stuck with being unable to build the ``travis`` ap on my laptop due to some stupid ruby nonsense, thus couldn't try it out (it was basically just to hack .travis.xml with some extra if statements, probably it wouldn't worked anyway).

**Comment by keflavich** [comment]
@bsipocz did you finish this?

**Comment by bsipocz** [comment]
@keflavich - Actually it was you who made this PR (I've only opened the issue), so I'm not sure whether it's finished or not. I don't have much time now to figure out alternative ways to do this.

**Comment by bsipocz** [comment]
The issue of running the remote tests is solved with the current solution, so closing this PR.

**Pull request closed without merging**
