### PR TITLE
CADC

### PR DESCRIPTION
**Pull request by andamian**
Not ready for release yet.

### CODE REVIEW

**Comment by bsipocz** [comment]
@andamian - Ignore @pep8speaks for now, I have to fine tune it to set which errors to ignore.

**Comment by keflavich** [comment]
@andamian any chance you'll be wrapping this up any time soon?

**Comment by andamian** [comment]
?Adam,


That's unlikely. You can reject it and I can retry at a later time.


Thanks,

Adrian

________________________________

**Comment by caseyjlaw** [comment]
@andamian My understanding from JJ is that the CADC integration is being developed in this fork: https://github.com/brianmajor/astroquery.
Should this pull request be closed?

**Comment by keflavich** [comment]
Closing per recommendations in #516

**Pull request closed without merging**
