### PR TITLE
The future is now

### PR DESCRIPTION
**Pull request by keflavich**
Remove a docstring line that is out of date

### CODE REVIEW

**Comment by keflavich** [comment]
@bsipocz We might want to consider how to have trivial PRs like this *not* trigger a new release...

**Comment by bsipocz** [comment]
@keflavich - So far I've manually cancelled the deploy job after merging. But see https://github.com/astropy/astroquery/issues/1143 for the exact same idea.

**Comment by bsipocz** [comment]
Please don't merge this, I'm starting to hack on that issue so will use this PR as a guinea pig.

**Comment by bsipocz** [comment]
Actually I would rather just merge this now as it wasn't opened from a branch on a fork, so I can't test everything I planned to.

**Pull request merged**
