### PR TITLE
Refactors: Make kwargs keyword only for remaining packages

### PR DESCRIPTION
**Pull request by nkphysics**
This PR is to address the remaining packages requiring refactors to make kwargs keyword only (#1746).

From the list in #1746 
- [x]  astroquery/vo_conesearch (in this PR)
- [x] astroquery/cadc (#2671)
- [x] astroquery/heasarc (#2671)
~~- [ ] astroquery/vamdc~~ (deprecated since 0.4.2 ??? If I am understanding correctly)
- [ ] astroquery/cosmosim (has no tests other than docs which are all skipped. I can make refactors but if stuff breaks I won't know) 
P.S. Thought about forking branch from #600 but probably requires more work than I think, might look into it in the future.
- [ ] ~~astroquery/mast (can try to address #2665 later)~~ (Seems to be a broader issue effecting more than Mast)

Hoping for some feedback on vamdc and cosmosim as I'm a little confused as to what's going on there or what you'll think is the best way to proceed.

### CODE REVIEW

**Comment by nkphysics** [comment]
I'm marking this ready for review. 
I can address astroquery/vamdc and astroquery/cosmosim once I know if we want refactors for them despite there being no tests for cosmosim, and the deprecation status of vamdc.

**Review by keflavich — APPROVED** [review]
Looks good to me.  None of these changes look like they would break any standard use cases.

**Comment by bsipocz** [comment]
> I can address astroquery/vamdc and astroquery/cosmosim once I know if we want refactors for them despite there being no tests for cosmosim, and the deprecation status of vamdc.

It's more than OK to skip vamdc (@keflavich - we really need to do something about it), but if you don't mind to add cosmosim, it would be great, so the we can say all is done.

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Thanks @nkphysics!

**Pull request merged**
