### PR TITLE
Fix ESO

### PR DESCRIPTION
**Pull request by keflavich**
ESO queries are broken (see #969).  We need to fix the module.

This is a WIP that fixes login.  The todo items are:

 * [x] list_instruments
 * [x] list_surveys
 * [x] query_apex_quicklooks
 * [x] query_instrument
 * [x] query_survey
 * [x] query_surveys
 * [ ] retrieve_data

### CODE REVIEW

**Comment by keflavich** [comment]
the conda-forge build appears to be failing.  Beyond that, I think this is ready.  @bsipocz, any thoughts abouts about the erroring build?

**Comment by bsipocz** [comment]
@keflavich - Travis has had issues with the osx builds for a few days now, I guess the failing build was part of that issue. I've restarted it now.

**Comment by keflavich** [comment]
@bsipocz I restarted it again, but it looked like maybe you had canceled?  I'm ready to merge this PR unless you see any problems.  The coverage decrease is fine and, afaict, the appveyor failure is some installation junk that is officially above my pay grade.  I think I actually fixed the astropy-bot comments....

**Comment by bsipocz** [comment]
Travis totally shut down their osx infra, so I vote for merging this without that build (and yes, I've cancelled it again, so it's not blocking other astropy builds in the queue).

The bot complains about the missing changelog, but here it's not an issue at all do to at release time.

**Comment by bsipocz** [comment]
Hmm, the astropy-helpers change is definitely unneeded, would you remove that last commit?

**Comment by keflavich** [comment]
yeah, that seemed weird to me.  Done.

**Comment by bsipocz** [comment]
Thanks! We can then just merge away, as everything except the osx has passed previously. Or are you waiting for the appveyor build?

**Comment by keflavich** [comment]
I'm OK to merge, but I also am not feeling all that impatient.  I can wait for the builds to finish.

**Comment by bsipocz** [comment]
I'm pretty sure the appveyor issue can be traced back to this:
https://github.com/pyca/pyopenssl/issues/674

I'll try to open a PR with a workaround, but first want to get the aastropy release out of the door.

**Pull request merged**
