### PR TITLE
Fix passing additional args to Gemini's query_criteria

### PR DESCRIPTION
**Pull request by saimn**
cc @olyoberdorf

### CODE REVIEW

**Comment by bsipocz** [comment]
@saimn - could you write some motivation for this? As @olyoberdorf mentions above, `rawqueryargs` got added to the end in the PR to keep the API backward compatible.

**Comment by saimn** [comment]
The only way to use the current API is a bit absurd: 
```
query_criteria(None, 0.3*units.deg, None, None, None, None, None, None, None,
                       None, None, None, None, 'MY_EXTRA_ARG!')
```
After a positional argument after a huge list of optional ones is not a great idea.

**Comment by bsipocz** [comment]
What about then making it a keyword with an interable value? Are both the `rawqueryargs` and `rawquerykwargs` necessary? 
We don't have any examples for either, so it's somewhat difficult to see their exact use cases.

**Comment by saimn** [comment]
An archive query looks like this https://archive.gemini.edu/searchform/notscience_verification/not_site_monitoring/imaging/science/cols=CTOWEQ/filter=r/Pass/notengineering/GMOS/20180101 where you have the equivalent of args (`/key/`) and kwargs (`/key=value/`). 
Then in the Python API @olyoberdorf added some arguments for the most commonly used parameters, but sometimes it can be useful to pass other arguments, e.g. restricting search to SV data with `/science_verification/`, or engineering data, etc.

**Comment by bsipocz** [comment]
OK, let's ask what @keflavich thinks. gemini is a pretty new archive, so I'm now inclined to be not too picky for the API change.

**Comment by bsipocz** [comment]
Thanks @saimn and @olyoberdorf!

**Pull request merged**
