### PR TITLE
Fix missing columns: Obsrv-lon, Obsrv-lat, Solar-lon, Solar-lat

### PR DESCRIPTION
**Pull request by mkelley**
To do:
- [x] Add regression test
- [x] Get @mommermi 's approval

Observing the moon crashes with KeyError (target=301, id_type='majorbody') due to returned columns missing in jplhorizons's column definition array:
```
In [6]: eph = Ephem.from_horizons('301', id_type='majorbody', location='688', epochs=dict(start='2019-01-01', stop='2019-01-02', step='15min'))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-206e7a0a1d74> in <module>()
----> 1 eph = Ephem.from_horizons('301', id_type='majorbody', location='688', epochs=dict(start='2019-01-01', stop='2019-01-02', step='15min'))

/home/msk/local/lib/python3.6/site-packages/sbpy-0.0.dev296-py3.6.egg/sbpy/data/ephem.py in from_horizons(cls, targetids, id_type, epochs, location, **kwargs)
    108             obj = Horizons(id=targetid, id_type=id_type,
    109                            location=location, epochs=epochs)
--> 110             eph = obj.ephemerides(**kwargs)
    111 
    112             # workaround for current version of astroquery to make

/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.9.dev5009-py3.6.egg/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.9.dev5009-py3.6.egg/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response
---> 29             result = self._parse_result(response, verbose=verbose)
     30             self.table = result
     31             return result

/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.9.dev5009-py3.6.egg/astroquery/jplhorizons/core.py in _parse_result(self, response, verbose)
   1221             return None
   1222         else:
-> 1223             data = self._parse_horizons(response.text)
   1224 
   1225         return data

/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.9.dev5009-py3.6.egg/astroquery/jplhorizons/core.py in _parse_horizons(self, src)
   1184         rename = []
   1185         for col in data.columns:
-> 1186             data[col].unit = column_defs[col][1]
   1187             if data[col].name != column_defs[col][0]:
   1188                 rename.append(data[col].name)

KeyError: 'Obsrv-lon'
```

### CODE REVIEW

**Comment by mommermi** [comment]
I am mommermi and I approve these changes.

**Comment by mommermi** [comment]
This PR addresses #1235

**Comment by bsipocz** [comment]
(I've rebased to get rid of the merge commit, sorry @keflavich :) )

**Comment by bsipocz** [comment]
Thank you @mkelley!

**Pull request merged**
