### PR TITLE
Add optional kwargs of BaseQuery to modules and modify tests where necessary

### LINKED ISSUE #1233: Add all optional kwargs of BaseQuery to the modules
E.g. at least `cache` and `timeout`. It will help to easier debug sporadic serverside issues users run into but we cannot reproduce, see e.g. #1232

### PR DESCRIPTION
**Pull request by kakirastern**
Fixes #1233. 

Add at least the kwargs `timeout` and `cache` to all modules to facilitate easy debugging. Changes to some tests needed to be introduced because of the new kwargs.

### CODE REVIEW

**Comment by keflavich** [comment]
Sorry it took me so long to review this, but now that I'm looking, I don't understand the motivation.  Unless a non-default behavior is explicitly required, we do _not_ want to specify all of the optional kwargs.  That's generally bad practice, as it adds a lot of redundant text, and it means that any global updates in `BaseQuery` that are intentionally global (inherited by others) would not propagate.

**Comment by bsipocz** [comment]
>  That's generally bad practice

I would disagree, but we can talk about it later this week. I'm sure we can find a middle ground.

**Comment by keflavich** [comment]
Fair enough.  I suppose there's no particular reason that specifying all optional arguments would be bad practice, and indeed it can be necessary for ensuring consistency over time for some operations.  But I really don't like it in this case, and if we think we need to specify 10 optional keyword arguments to ensure stability of the call, we have a major design flaw that we should be correcting.  I don't think that's the case.

These keyword arguments:
```
data=None,
headers=None,
files=None,
save=False,
savedir='',
stream=False,
auth=None,
```
should not be specified, though.  Since there is no sensible alternative default for any of these (except, maybe, `stream`), they would never be globally changed.  Specifying them just makes the code extra verbose without reason.

**Comment by eteq** [comment]
closed at request of author - last SHA 050b5905a583b2a2176e4b15352d3c261ab9b0e9

**Pull request closed without merging**
