### PR TITLE
Utils to cleanup docs downloads

### LINKED ISSUE #2058: Cleanup files generated by tests
There are at least 3 files generated by `esa_hubble` during the tests. Those should be ideally temporary files only, or at least be removed at the end of the test run.

### PR DESCRIPTION
**Pull request by bsipocz**
After a pytest run I ended up with a lot of files yet again, so dived into adding `testcleanup` to the end of the offending narrative docs. Rather than repeating the same code for all of them I opted for adding a new utility ``cleanup_saved_downloads``. I'm open for suggestions if anyone has a better idea for naming it or for its namespace.

This is to address some parts of #2058

### CODE REVIEW

**Comment by bsipocz** [comment]
cc @pllim - let me know if you think this would be useful upstream, too.

**Review by pllim — COMMENTED** [review]
While convenient, this does make the cleanup less explicit in the doc itself and the `rmtree` might accidentally remove things we want to keep if someone pass the wrong input to the function? Still, maybe worth bringing up at the next infrastructure tag-up; do you want to add it to the agenda?

If we decide to move this upstream, maybe over at... pytest-doctestplus or sphinx-astropy ?

**Comment by bsipocz** [comment]
Yeah, I'm not that much worried about the misuse of it, folks would notice if something from the git tree is removed accidentally before committing it, and users shouldn't use the function. 
I just very much like to have something short and simple and copy pasteable for the modules than having to work around it separately.

**Comment by pllim** [comment]
Why don't you add it to astroquery for now and we can always move it upstream later? Then, the upstream decision won't hold off this work for astroquery. Thanks for the ping!

**Comment by bsipocz** [comment]
I need to add this to astroquery even in the case it ends up upstream, as we cannot just bump the required version numbers for the dependencies. So it's more like a heads up to see whether it maybe useful for others. If not, then I would rather keep and maintain it here.

**Pull request merged**
