### PR TITLE
Refactor: SIMBAD keyword-only

### PR DESCRIPTION
**Pull request by keflavich**
This refactors the SIMBAD queries to have all keyword arguments be keyword-only (except region radius, which is a required keyword argument that includes a default).

Re: #1746.  @bsipocz, is this what you have in mind?

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
This needs a changelog (we have a template sentence already for the other modules)

**Comment by bsipocz** [comment]
> Re: https://github.com/astropy/astroquery/issues/1746. @bsipocz, is this what you have in mind?

yes. It's tedious and API-changing, but rather trivial.

**Comment by bsipocz** [comment]
Oh, and do run the remote tests locally to make sure all is well.

**Comment by keflavich** [comment]
We have a bunch of errors, but I suspect they're unrelated.  And they raise questions.
```
E           astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in self.last_parsed_result.
E            Exception: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '0:01:00 +0:00:00': No astronomical object found :

astroquery/simbad/core.py:1029: TableParseError
============================================================================================ short test summary info ============================================================================================
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_query_regions - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_query_multi_object - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_null_response[query_criteria] - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_null_response[query_object] - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_null_response[query_catalog] - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_null_response[query_bibobj] - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_null_response[query_bibcode] - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_null_response[query_objectids] - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_query_objects_null - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_query_region_null - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
FAILED astroquery/simbad/tests/test_simbad_remote.py::TestSimbad::test_query_small_region_null - astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in s...
=================================================================================== 11 failed, 19 passed in 70.28s (0:01:10) ====================================================================================
```

I'll dig a bit.

**Comment by bsipocz** [comment]
Yes, these are present on `main`, too and are due to the switch that we started failing on unprocessed warnings.

e.g. these:

```
E           UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '0:01:00 +0:00:00': No astronomical object found :
```

**Comment by bsipocz** [comment]
Thanks @keflavich!

**Pull request merged**
