### PR TITLE
Force used simbad coordinate system to align to esasky coordinates

### PR DESCRIPTION
**Pull request by imbasimba**

### CODE REVIEW

**Comment by pllim** [comment]
What is the motivation for this change? Also, it is more flexible as a configuration item.

**Comment by bsipocz** [comment]
@imbasimba - Some of the travis failures were totally unrelated and were present in master. I've fixed them and cherry-pick it to your branch, as well as fixed a pep8 style fail that was introduced here. So now I hope we get the CI green light.

**Comment by imbasimba** [comment]
@pllim The ESASky website uses simbad coordinates and name resolution. 
Since astropy seems to use the reponse listed first in sesame, it usually defaults to NED. This results in getting slightly different responses for the same object (like m51) from the astroquery esasky module and the esasky website.

**Comment by bsipocz** [comment]
The appveyor failure is unrelated and is being dealt with separately, so I'm merging this now.

**Comment by bsipocz** [comment]
@imbasimba - Thanks for the fix. Could you please use feature branches in the future, rather than master? That case rebases are cleaner, and merge commits will be easier to avoid.

**Comment by imbasimba** [comment]
@bsipocz Will do!

**Pull request merged**
