### PR TITLE
Astrometry.net solvers returning jobid

### PR DESCRIPTION
**Pull request by alsimoneau**
Modifications according to astropy/astroquery#2335.

### CODE REVIEW

**Review by bsipocz — CHANGES_REQUESTED** [review]
removing kwargs should be done with a deprecation period otherwise it will break user code. Please use e.g. the `deprecated_renamed_argument` from `astropy.utils` to do that.

It will also need to be mentioned in the changelog.

**Comment by bsipocz** [comment]
@mwcraig - could you please have a look at this and the linked issue?

**Comment by mwcraig** [comment]
@bsipocz -- I should have some time Friday or Saturday.

**Comment by bsipocz** [comment]
gentle ping @mwcraig, if you have time to review this and the referenced issue

**Comment by mwcraig** [comment]
My apologies for the epic delay here.

I think it makes sense to return the job id, or at least to have that be an option.

The issue at the moments is that we would need, at a minimum, a deprecation period for removing the keywords. 

A better approach might be to add a new keyword, maybe `return_job_id` or something, that allows users to opt in to this behavior instead of removing the timeout option completely.

Having access to the job ID is important if the user wants to download more results than what the we currently provide.

Classes end here in about 1.5 weeks, could take a longer look then (but don't be shy about pinging if I don't 😬 ).

**Comment by alsimoneau** [comment]
I agree that backward compatibility is important.

I mostly did this commit to show how it could be possible to implement. I fully expected the actual implementation to me more complex.

I'm very busy with my own studies at the moment, but I could try to implement a better approach to this change when I have more time.

Thank you for your comprehension and your time.

**Comment by mwcraig** [comment]
@bsipocz -- I would recommend closing this in favor of #2685.

@alsimoneau -- thanks for opening this: the discussion on this PR led to the fix being made in #2685.

**Pull request closed without merging**
