### PR TITLE
Using explicit imports to fix pytest 3.7+ issue

### PR DESCRIPTION
**Pull request by bsipocz**
This should fix the failure in #1283

### CODE REVIEW

**Comment by bsipocz** [comment]
This latest commit is not compatible with astropy 1.3. 

@keflavich - how do you feel about officially stop supporting astropy 1.3? Requiring pytest-astropy currently only means that we cannot test with 1.3, but if we don't do that we easily can became non compatible so better not to promise it...

**Comment by bsipocz** [comment]
Weird, I don't really see how the astropy 1.3 test passed, but we have other issues instead.

**Comment by keflavich** [comment]
astropy-2 is still py2-compatible, right?  In that case, sure, we can drop astropy 1.3

**Comment by bsipocz** [comment]
Yes, astropy 2 is python2 compatible and will be supported for one more year (ouch for me).

**Comment by bsipocz** [comment]
but it seems like that things still pass with 1.3, so as I said I'm confused a bit here.

**Comment by bsipocz** [comment]
Tests on appveyor have passed before and the latest commits only affected the travis config, so this can be confidently merged.

**Pull request merged**
