### PR TITLE
Usage statistics for ESASky module

### PR DESCRIPTION
**Pull request by imbasimba**
We would like to know more about how our users use this module, especially for users downloading data. Since the download requests go directly to each archive, and never touch to the ESASky servers we have no idea how much data and which missions are being downloaded. 

This is my proposal on how to solve this issue. I've tried to only collect high level information (which mission, data volume, and which methods are used), which I hope no user would protest against. What do you think about this @keflavich, @bsipocz?

### CODE REVIEW

**Comment by keflavich** [comment]
Can you not ask the servers to share their data?  I'm not comfortable with sending data around specifically for the purpose of tracking use.

**Comment by imbasimba** [comment]
In theory, yes. But in practice, probably not, since ESASky is exposing data from dussins and dussins of missions all around the world. 

I do agree with your sentiment that sending data for the purpose of tracking is not the nicest thing to do... I was hoping the information was vague enough not to be intrusive. It would certainly be helpful though.

Are you aware of any type of tracking in any other part of astroquery/astropy?

**Comment by keflavich** [comment]
We have explicitly prevented any sort of tracking in other parts of astroquery to this point.  However, I think this case may be reasonable - as long as we're only tracking by sending requests, not user data, to ESASky, it is just doing what a user going through the web would do.  But I want to be very careful in this realm.

**Comment by imbasimba** [comment]
Hmm... Yes. The golden nugget information is only what is needed to be able to say "X Bytes downloaded for mission Z" for each mission. Anything else, is just gravy. Speaking of that, I will remove the gravy (the proposed method useage tracking).

The server is GDPR compliant, IP is scrambled and not stored, and no other user info is sent or stored. 

Anyway, let's wait at least a few days if more people want to weigh in.

**Comment by keflavich** [comment]
So one thing we do, in astroquery, is set the user agent to be the specific astroquery version.  This allows the data repositories to track how much traffic they get from astroquery.  So you might consider just asking the various data repositories that ESASky serves up how much traffic they get from astroquery.  We would love to have that information available!  We could also modify the user agent further for ESASky queries to say 'astroquery.esasky', say.

**Comment by bsipocz** [comment]
If we do this, what about exposing a config item that switches this off? I agree with @keflavich that ideally the info could be collected from the server-side already using the user-agent. On the other hand this doesn't seem to expose much more user info than what we already do (I would guess the version number could be used as a better identification of the user than these size stats)

**Comment by imbasimba** [comment]
I agree that this would ideally be collected from the servers, but it will be very difficult to implement logistically, since we are talking about so many servers, stakeholders, and legacy missions.

As I see it we can either
1. Do something like this PR
or 
2. Go on a long quest to convince missions to analyze and share their usage data regurally. If this usage data (like data volume downloaded & number of queries) is of high value to you, this option may be worth it. If this is only of low or medium value to you, I vote for the first option. I imagine I could get most ESA missions onboard eventually, but the other institutions will require more of an astroquery coordinated effort.

**Comment by imbasimba** [comment]
Or
3. Scrap this PR

Of course, I prefer option 1, but what do you think @keflavich @bsipocz ?

**Pull request closed without merging**
