### PR TITLE
Workaround bugfix for IRSA issue #2008

### PR DESCRIPTION
**Pull request by keflavich**
#2008 pointed out an upstream failure on the IPAC service.  This is a simple workaround for that issue.

### CODE REVIEW

**Comment by bsipocz** [comment]
Could you add a changelog entry? Possibly a test that both options work?

**Comment by keflavich** [comment]
`xml` is presently broken, but an upstream fix has been promised.  Otherwise, adding a test is a good idea; will try today.

**Comment by bsipocz** [comment]
> `xml` is presently broken

az xfailing test for that would be still great, so we would (ideally) notice when it gets fixed upstream

**Comment by bsipocz** [comment]
@keflavich - did this ever worked for you, or maybe you have uncommitted changes locally?
 Shall I take it over?

**Comment by keflavich** [comment]
I fwded you the email notification; please feel free to take this over (I don't recall status)

**Comment by bsipocz** [comment]
OK, I'm on it.
The ascii version seems to work with minimal modification. Also, the XML also seems to work with the online form, so I'm confident it just needs a little bit of tweaking here.

**Comment by bsipocz** [comment]
Damn, the xml is working out of the box, but picks up from the cache...

**Comment by bsipocz** [comment]
OK, so do we in fact need the `mode` kwarg? I mean `list_catalogs` would return the same dictionary no matter whether `ascii` or `xml` is used, now that the link is fixed upstream.

**Comment by bsipocz** [comment]
Thanks for the workaround!

However, I will just go ahead and close this, the imminent issue has been fixed upstream and I can't see any use cases where this kwarg would make a difference (whether we want to switch to e.g. ascii from XML is a separate question, but I don't think that is necessary either).

**Pull request closed without merging**
