### PR TITLE
Added vo module

### PR DESCRIPTION
**Pull request by andamian**
This is a generic VO module for image searches that uses only VO services and standards to implement astroquery basic API. Data providers, such as ALMA or CADC, can further customize this functionality for their own modules.

Note that this PR depends on a number of changes in `pyvo` that have not been released yet but will be in the near future.

### CODE REVIEW

**Comment by bsipocz** [comment]
Before doing any review here, I suppose we need to discuss the ideas here a bit, both from the user perspective as well as the holistic view of what goes into astroquery vs pyvo.

**Comment by andamian** [comment]
`pyvo` contains the IVOA spec implementations (One big exception is `VOTable` which is already part of the core `astropy`). It is a library for developers that are familiar with IVOA standards.

`astroquery` on the other hand offers a common API for accessing data from various data providers. The users of `astroquery` do not need to know the details of the underlying access mechanisms and protocols. To that end, the `vo` module proposed in this PR attempts to do just that: implement that generic `astroquery` API by putting together protocols implemented in `pyvo` for those data providers that offer VO services. Users need to know little (if anything) about these protocols while the data providers can get instant exposure to the `astroquery` general community.

**Comment by keflavich** [comment]
@andamian when you have a chance, could you revisit this?  Are the needed pyvo changes done?

**Comment by andamian** [comment]
This was completely out of my radar. I'll add it to my list of things to do.

**Comment by pllim** [comment]
A long time ago, there was also a `astropy.vo` module, so having `astroquery.vo` is going to be super confusing.

**Comment by bsipocz** [comment]
I'm going through the open PRs, and while the motivation here is something more generic I suppose this could certainly address my desire of one/multiple VO based baseclass: https://github.com/astropy/astroquery/issues/2360

**Comment by bsipocz** [comment]
Overall, regarding the generic module I think it's an interesting idea and certainly needs more discussion between pyvo and astroquery maintainers.

**Comment by andamian** [comment]
OK. Closing it here.

**Pull request closed without merging**
