### PR TITLE
Remove unused code from `utils.tap` and related sub-packages

### PR DESCRIPTION
**Pull request by eerovaher**
I've removed some code related to `astroquery.utils.tap` that was not used or for which there was an obvious alternative in the standard library. I did not search for such code thoroughly, this pull request simply removes the few instances I stumbled upon.

I also removed an unused test data file.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
This looks fine for now, but I would also ask @jespinosaar to have a look at it.

However @eerovaher, in the future, please refrain from refactoring or pour any significant resource to improve the tap module as the plan is to phase it out in favour of pyvo, so resources are best spent elsewhere than cleaning up/improving something that is practically deprecated.

**Comment by eerovaher** [comment]
I agree that the `Tap` class in `utils.tap` should be replaced with the `pyvo` implementation, which is why I am trying to decouple the `esa` and `gaia` tests from `utils.tap`.

**Comment by bsipocz** [comment]
OK, let's have this now. Thanks @eerovaher for the cleanup.

**Comment by jespinosaar** [comment]
Hi, thanks for this!

**Pull request merged**
