### PR TITLE
Add interface to IRSA image server (IBE)

### PR DESCRIPTION
**Pull request by lpsinger**
This module talks to IRSA's image server, which is currently used by WISE and PTF. The program interface is called IBE (not sure what it stands for). It supports cone searches and limited SQL-like queries to find images and catalog files for individual exposures. The system is described here:

http://www.ptf.caltech.edu/page/ibe

This is different from the existing astroquery.irsa module: that talks to a service called 'Gator' which provides access to catalogs; IBE, on the other hand, is designed for discovering data associated with given observations.

### CODE REVIEW

**Comment by keflavich** [comment]
@lpsinger - Just a reminder that we should continue this when you have time again

**Comment by lpsinger** [comment]
Wow, it's been a while since I looked at this PR. I just rebased it and I am going to add docs and tests shortly. Are there any major changes in Astroquery that I need to be aware of in these patches?

**Comment by lpsinger** [comment]
@keflavich, I don't know why the Travis tests are failing; they work on my machine. It looks like under Travis the files that I added to `astroquery/ibe/tests/data` cannot be found.

**Comment by keflavich** [comment]
@lpsinger looks like you figured it out; `setup_package` was the culprit.

**Comment by keflavich** [comment]
@lpsinger when this passes, ping me again and I'll perform the remote tests locally (sounds weird, but it makes sense) and then merge.

**Comment by lpsinger** [comment]
I accidentally cancelled the Travis build and I can't restart it.

**Comment by lpsinger** [comment]
Pretty sure the tests are going to pass, so I'm going to squash the commits now.

**Comment by lpsinger** [comment]
@keflavich, [the tests passing now](https://travis-ci.org/lpsinger/astroquery/builds/93039209), though the PR build has yet to catch up with the branch.

**Comment by keflavich** [comment]
Great!  thanks @lpsinger!  Good to know that we can sometimes resolve these old issues.

**Comment by lpsinger** [comment]
BTW, when is your next release scheduled?

**Comment by keflavich** [comment]
We haven't really been following a schedule, mostly "when enough things get added".  This will push us to make a new one sooner than later.

**Pull request merged**
