### PR TITLE
add query_star function

### LINKED ISSUE #1351: nasa_exoplanet_archive module would benefit from a query_star function
At the moment there is a query_planet() function but not a query_star() function [as far as I can tell].  This would be a great feature to develop! @bmorris3

### PR DESCRIPTION
**Pull request by sashank27**
Fixes #1351 
Adds a `query_star()` function for `nasa_exoplanet_archive`, which lists up the planets under a specifc stellar system.
Also, `.gitignore` is updated so as to include sample virtual environment folders

### CODE REVIEW

**Comment by keflavich** [comment]
This is a nice little feature.  Does the NASA exoplanet archive support directly searching by star, though?  It would be more efficient to send that query to their server rather than download the whole table then downselect on the user machine.

Also, please include an example use in the docs and, ideally, a test.

**Comment by bsipocz** [comment]
Haven't they just changed their API? 

I would rather see the whole module being rewritten to based on that, rather than keep the current hacks in place. 

If there is any interest for this from the archive folks, I'm happy to mentor the contribution on e.g. the AAS hackday.

**Comment by keflavich** [comment]
No, they're adding new things, but I don't think their API is changed yet.  They will have a TAP-based one next year, though? https://twitter.com/i/web/status/1207001305232752640

**Comment by bsipocz** [comment]
Ah, ok, that's the one I remembered, but then misremembered the timeline.

**Comment by sashank27** [comment]
After exploring the API, this is what I found out:
1. To search for a specific exoplanet, we can create a query as:
`http://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets&where=pl_name=' + planet_name`
2. To search for all exoplanets under a specific stellar system, we can create a query as:
`http://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets&where=pl_hostname=' + star_name`

Should I refactor the whole API using these specific queries? @bsipocz @keflavich 

Reference:
- https://exoplanetarchive.ipac.caltech.edu/docs/API_queries.html
- https://exoplanetarchive.ipac.caltech.edu/docs/API_exoplanet_columns.html

**Comment by bsipocz** [comment]
> Should I refactor the whole API using these specific queries?

that would be indeed a very nice contribution. (caveat, as you've seen the discussion above, that at some point in the next year their whole system will change, so the refactor might get refactored again)

**Comment by sashank27** [comment]
Okay, I'll refactor the API as of now

**Pull request closed without merging**
