### PR TITLE
Skyview: fixing keys to match changed remote

### PR DESCRIPTION
**Pull request by bsipocz**
AKARI was added, and names were all changed in SkyView. 

@keflavich - I wonder you know whether they have a changelog somewhere, or a mailing list where they announce the changes. It would be great to know about these things rather that trying to reverse engineer.

### CODE REVIEW

**Comment by keflavich** [comment]
@bsipocz no idea, but we can ask directly

**Comment by bsipocz** [comment]
Do you have a direct e-mail address, or should I just leave a note/question on their feedback webform?

**Comment by keflavich** [comment]
no, I don't have a direct contact

**Comment by augustfly** [comment]
You could always try Tom McGlynn directly -- tom.mcglynn@nasa.gov

**Pull request merged**
