### PR TITLE
Cleanup test decorations

### PR DESCRIPTION
**Pull request by bsipocz**
remove obsolete slow marks and change known failures to xfail

Most of these slow tests were decorated way back, and since then they seemed to be fixed. There are also a handful of tests that got decorated with skip due to a know failure, I've changed those to xfail which better reflects on their status.

So overall the changes are 36 pass 14 skip to 41 pass 4 skip 5 xfail, total runtime from 6 min to 7.25 min

The current durations:

```
============================================================================ slowest 50 durations ============================================================================
84.72s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_download_and_extract
62.84s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_stage_data
56.75s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_bands
45.53s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_data_info
33.90s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_download_data
22.22s call     astroquery/alma/tests/test_alma_remote.py::test_download_html_file
14.68s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_doc_example
12.94s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_stage_data_listall
11.04s call     astroquery/alma/tests/test_alma_remote.py::test_verify_html_file
11.04s call     astroquery/alma/tests/test_alma_utils.py::test_make_finder_chart
10.98s call     astroquery/alma/tests/test_alma_remote.py::test_staging_stacking
8.35s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_freq
5.54s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_SgrAstar
5.31s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_public
4.91s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_user
4.64s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_keywords
4.02s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_query
3.95s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_stage_data_json
3.88s call     astroquery/alma/tests/test_alma_remote.py::test_staging_postfeb2020
3.87s call     astroquery/alma/tests/test_alma_remote.py::test_staging_uptofeb2020
3.68s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_data_proprietary
3.63s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_misc
2.82s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_alma_source_name
2.74s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_equivalent_columns
2.67s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_docs_example
2.33s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_ra_dec
2.19s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_cycle1
2.09s call     astroquery/alma/tests/test_alma_remote.py::test_project_metadata
0.25s setup    astroquery/alma/tests/test_alma_remote.py::TestAlma::test_SgrAstar
0.09s call     astroquery/alma/tests/test_alma.py::test_gen_pos_sql
0.04s call     astroquery/alma/tests/test_alma_utils.py::test_pyregion_subset
0.03s call     astroquery/alma/tests/test_alma.py::test_query
0.02s call     astroquery/alma/tests/test_alma.py::test_get_data_info
0.01s call     astroquery/alma/tests/test_alma.py::test_galactic_query
0.01s setup    astroquery/alma/tests/test_alma_remote.py::TestAlma::test_equivalent_columns
0.01s call     astroquery/alma/tests/test_alma.py::test_sia
0.01s call     astroquery/alma/tests/test_alma.py::test_tap

(13 durations < 0.005s hidden.  Use -vv to show these durations.)
```

### CODE REVIEW

**Comment by bsipocz** [comment]
Overall it would be great to be able to cut back some on the slowest tests, maybe it's possible by working with smaller datasets? Either way,  think this is an improvement. It's not release critical though, so I'll leave a chance for comments before merging.

**Comment by bsipocz** [comment]
I've changed the default test server to be the ESO one as it cuts back the test runtime from 40mins to 15min, even for based in Seattle. And CI is not located at nrao network either, all those closer to those other sources can use `--alma-site` to override.

cc @keflavich whether this is OK.

**Comment by bsipocz** [comment]
Updated timings after the rebase, on the same local computer using the eso site  (just as it was used for the previous timings above):

```
================================================================ slowest 50 durations =================================================================
496.14s call     docs/alma/alma.rst::alma.rst
117.80s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_bands
43.48s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_data_info
35.61s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_download_and_extract
35.49s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_freq
30.72s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_doc_example
29.26s call     astroquery/alma/tests/test_alma_remote.py::test_data_info_stacking
26.66s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_download_data
20.61s call     astroquery/alma/tests/test_alma_remote.py::test_download_html_file
13.17s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_user
12.93s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_keywords
12.44s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_SgrAstar
11.48s call     astroquery/alma/tests/test_alma_remote.py::test_verify_html_file
10.83s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_data_proprietary
10.61s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_misc
9.66s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_public
6.10s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_equivalent_columns
3.10s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_alma_source_name
2.69s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_query
2.54s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_ra_dec
2.42s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_cycle1
2.35s call     astroquery/alma/tests/test_alma_remote.py::test_project_metadata
0.09s call     astroquery/alma/tests/test_alma.py::test_gen_pos_sql
0.03s call     astroquery/alma/tests/test_alma.py::test_query
0.02s call     astroquery/alma/tests/test_alma.py::test_get_data_info
0.01s call     astroquery/alma/tests/test_alma.py::test_galactic_query
0.01s call     astroquery/alma/tests/test_alma.py::test_sia
0.01s call     astroquery/alma/tests/test_alma.py::test_tap

(22 durations < 0.005s hidden.  Use -vv to show these durations.)
=============================================================== short test summary info ===============================================================
```

**Comment by keflavich** [comment]
:+1: to switching to ESO.  I don't know what's up with the NRAO servers, but they have repeatedly and consistently been slow for me this year.

**Comment by bsipocz** [comment]
I'm going ahead and merge this now. One test that was skipped before is failing now, but that should be fixed separately as it seems to be a legit issue (and it shows that it's in fact valuable to not skip the tests :) )

Current timings, the docs could certainly use some fine tunings, as it even timed out around line 370 (maybe switching off from the nrao mirror hidden away in a `testsetup` would be enough?):
```
1264.00s call     docs/alma/alma.rst::alma.rst
149.85s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_bands
66.80s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_freq
64.12s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_data_info
43.08s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_download_data
42.12s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_download_and_extract
41.10s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_doc_example
36.23s call     astroquery/alma/tests/test_alma_remote.py::test_data_info_stacking
24.33s call     astroquery/alma/tests/test_alma_remote.py::test_download_html_file
21.90s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_keywords
20.83s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_user
18.62s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_SgrAstar
14.03s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_misc
11.92s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_public
10.86s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_data_proprietary
10.57s call     astroquery/alma/tests/test_alma_remote.py::test_verify_html_file
6.09s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_equivalent_columns
2.60s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_query
2.56s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_ra_dec
2.47s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_cycle1
2.44s call     astroquery/alma/tests/test_alma_remote.py::TestAlma::test_alma_source_name
2.41s call     astroquery/alma/tests/test_alma_remote.py::test_project_metadata
0.05s call     astroquery/alma/tests/test_alma.py::test_gen_pos_sql
0.03s call     astroquery/alma/tests/test_alma.py::test_query
0.01s call     astroquery/alma/tests/test_alma.py::test_get_data_info
0.01s setup    astroquery/alma/tests/test_alma_remote.py::TestAlma::test_data_info
0.01s call     astroquery/alma/tests/test_alma.py::test_galactic_query

```

**Pull request merged**
