### PR TITLE
Update jplhorizons columns

### PR DESCRIPTION
**Pull request by mkelley**
JPL Horizons has had a few additions to their columns.  Update astroquery to match.  Based on the Horizons documentation, the new quantities are:

```
       44. Apparent target-centered longitude of Sun (L_s)
     * 45. Inertial frame apparent RA & DEC
       46.   Rates: Inertial RA & DEC
     * 47. Sky motion: angular rate & angles
       48. Lunar sky brightness & target visual SNR
```

Also add units to `hour_angle`, `solartime`, and `siderealtime`.  (bugfix)

Addresses issue #2783

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @mkelley!

**Comment by bsipocz** [comment]
Not sure what went wrong here that bloated up the diff this badly. Could you maybe rebase and remove that second to last commit that only added noise by reformatting, but haven't really fixed the whitespace issue?

**Comment by mkelley** [comment]
Shucks, I had worked so hard to keep black from reformatting the file... but missed it one time.

**Review by bsipocz — APPROVED** [review]
All looks good! Thanks @mkelley!

**Pull request merged**
