### PR TITLE
Updated astropy-helpers to v1.0.2

### PR DESCRIPTION
**Pull request by cdeil**
This is needed to make `python setup.py build_sphinx` work with Sphinx 1.3.

(It's why I didn't notice the Sphinx error which then showed up on travis-ci here: https://github.com/astropy/astroquery/pull/523#discussion_r28965846)

### CODE REVIEW

**Comment by cdeil** [comment]
This astropy-helpers update results in issues for astroquery.

Sphinx build: https://gist.github.com/cdeil/782fef6e464d23c797cf
Tests: https://gist.github.com/cdeil/265e8c76c65e55f4a8f6

Somehow the way astroquery sets up `conf` doesn't work any more:
```python
In [16]: %paste
from astropy import config as _config


class Conf(_config.ConfigNamespace):
    """
    Configuration parameters for `astroquery.irsa_dust`.
    """
    # maintain a list of URLs in case the user wants to append a mirror
    server = _config.ConfigItem(
        ['http://irsa.ipac.caltech.edu/cgi-bin/DUST/nph-dust'],
        'Name of the irsa_dust server to use.'
        )
    timeout = _config.ConfigItem(
        30,
        'Default timeout for connecting to server.'
        )

conf = Conf()
## -- End pasted text --

In [17]: conf
Out[17]: <__main__.Conf at 0x1069c9668>

In [18]: conf.server
---------------------------------------------------------------------------
VdtValueError                             Traceback (most recent call last)
/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev12096-py3.4-macosx-10.10-x86_64.egg/astropy/config/configuration.py in __call__(self)
    431         try:
--> 432             return self._validate_val(val)
    433         except validate.ValidateError as e:

/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev12096-py3.4-macosx-10.10-x86_64.egg/astropy/config/configuration.py in _validate_val(self, val)
    444         # instance or sub-class, it will be used
--> 445         return self._validator.check(self.cfgtype, val)
    446 

/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev12096-py3.4-macosx-10.10-x86_64.egg/astropy/extern/configobj/validate.py in check(self, check, value, missing)
    624 
--> 625         return self._check_value(value, fun_name, fun_args, fun_kwargs)
    626 

/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev12096-py3.4-macosx-10.10-x86_64.egg/astropy/extern/configobj/validate.py in _check_value(self, value, fun_name, fun_args, fun_kwargs)
    656         else:
--> 657             return fun(value, *fun_args, **fun_kwargs)
    658 

/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev12096-py3.4-macosx-10.10-x86_64.egg/astropy/extern/configobj/validate.py in is_option(value, *options)
   1331     if not value in options:
-> 1332         raise VdtValueError(value)
   1333     return value

VdtValueError: the value "http://ned.ipac.caltech.edu/cgi-bin/" is unacceptable.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-18-a27f955e9921> in <module>()
----> 1 conf.server

/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev12096-py3.4-macosx-10.10-x86_64.egg/astropy/config/configuration.py in __get__(self, obj, objtype)
    268         if obj is None:
    269             return self
--> 270         return self()
    271 
    272     def set(self, value):

/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev12096-py3.4-macosx-10.10-x86_64.egg/astropy/config/configuration.py in __call__(self)
    432             return self._validate_val(val)
    433         except validate.ValidateError as e:
--> 434             raise TypeError('Configuration value not valid:' + e.args[0])
    435 
    436     def _validate_val(self, val):

TypeError: Configuration value not valid:the value "http://ned.ipac.caltech.edu/cgi-bin/" is unacceptable.
```

@embray Is this a result of your changes in https://github.com/astropy/astropy-helpers/pull/158 ?
@keflavich Need help!?

**Comment by cdeil** [comment]
The issue I had locally was fixed by updating Astropy master from `4649c94` to `481d1d3`!?

Don't know what it is, but it works find now and tests passed on travis-ci.
So @keflavich , OK to merge this?

**Comment by keflavich** [comment]
Sure, but can you explain it to me tomorrow?

**Comment by cdeil** [comment]
All this PR does is update Astroquery to the latest astropy-helpers using these commands:
http://astropy.readthedocs.org/en/latest/development/affiliated-packages.html#updating-to-the-latest-template-files

This is needed for all affiliated packages (sigh) to make `python setup.py build_sphinx` work with Sphinx 1.3 (see https://github.com/astropy/astropy-helpers/pull/148).

**Pull request merged**
