### PR TITLE
Atomic, expand and specify allowed output columns

### PR DESCRIPTION
**Pull request by DavoGrant**
This small update makes way for a new argument in both query_object and query_object_async. A tuple specifying which output columns you want to retrieve; allowing users access to the Einstein A coefficient or fewer columns if preferred.

### CODE REVIEW

**Comment by keflavich** [comment]
Looks good to me on the surface.  I think using `lxml` for the beautifulsoup parsing is fine, assuming the tests pass; we use a mix of lxml and html5lib throughout astroquery.

**Comment by DavoGrant** [comment]
A test failed so I've omitted specifying the parser as lmxl explicitly, as it's not central to this feature.

**Comment by keflavich** [comment]
Looks good.  Maybe add a changelog entry:
"Added ability to select which rows are returned from the atomic line database [#1006]"

**Comment by bsipocz** [comment]
Thanks @DavoGrant!

**Pull request merged**
