### PR TITLE
Minor bug when formatting tables

### PR DESCRIPTION
**Pull request by jespinosaar**
Hi all!

This is a PR to fix a minor issue with the formatting in the tables. Would you mind having a quick look, so we can have it ready (and with a pre-release version) as soon as possible? Thanks in advance!

@esdc-esac-esa-int

### CODE REVIEW

**Comment by jespinosaar** [comment]
Sorry for the rush, but this is associated to a use case we would like to show in a demo...

**Review by keflavich — APPROVED** [review]
Looks fine to me - quite a minor change.

**Comment by jespinosaar** [comment]
Thanks @keflavich , any other comment @bsipocz ?

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Thanks @jespinosaar!

**Comment by bsipocz** [comment]
> we would like to show in a demo

@jespinosaar - when is your demo? There are quite a few other PRs in final review, I'll make sure to get those in before that, too.

**Comment by jespinosaar** [comment]
Many thanks for such a quick response, @bsipocz ! Our demo is on Monday, at ADASS, we will be there in person.

Please let me know when you create the pre-release version so we can test it.

See you!

**Comment by jespinosaar** [comment]
Hi! anything new about the pre-released version?

**Comment by bsipocz** [comment]
I pushed a release earlier today, I'm sorry about the delay.

**Comment by jespinosaar** [comment]
Many thanks!

**Pull request merged**
