### PR TITLE
Fixing pep8 errors and warnings 

### PR DESCRIPTION
**Pull request by bsipocz**
These are the trivial auto fixes for E111, E124, E128, E201, E202, E203,E 221, E231, E261, E265, E271, E272, E301, E302, E303, W291, W292, W293, W391

There are still 1287 errors/warnings left most of which is for long lines.
@keflavich is there a guideline for line length in astroquery? Should we aim for 80 or longer?

### CODE REVIEW

**Comment by keflavich** [comment]
@bsipocz I always aim for 80 but sometimes miss.

**Comment by bsipocz** [comment]
OK, then I'll fix most of those too.

**Comment by bsipocz** [comment]
@keflavich - I've added a pep8 check to the travis matrix, with allowing it to fail. This PR now fixes many of the long lines, too but there are still about ~150 remaining. Some of them will be removed/reworked by #623, but some will stay as they are long urls/etc.

**Comment by bsipocz** [comment]
Coverage decrease is irrelevant (and understandable) in this PR as many single uncovered long lines got wrapped and now become multiple uncovered lines.

**Comment by bsipocz** [comment]
ping @keflavich. Could you please look at this? Leaving this PR open for a long time will most probably cause conflicts with any new PRs.

**Comment by keflavich** [comment]
@bsipocz sorry, I didn't realize you wanted my attention on it.  I think it's fine to merge.  I did not review every line, but I approve the PR.

**Comment by bsipocz** [comment]
Thanks. It's just I prefer not to merge large diffs I made myself :)

**Pull request merged**
