### PR TITLE
Esasky minor documentation change

### PR DESCRIPTION
**Pull request by imbasimba**

### CODE REVIEW

**Comment by keflavich** [comment]
@imbasimba For the `directory_name`->`savename` change: are we using `savename` as a directory locations elsewhere in astroquery, or is that used for filenames?  If the latter, it would be better to use `directory_name` here.  But, if not, I appreciate the effort to improve API consistency!

Let me know if this is done and I'll merge it once tests pass.

(I don't remember details of the API off the top of my head....)

**Comment by imbasimba** [comment]
Here 
https://astroquery.readthedocs.io/en/latest/api.html#common-keywords
I read this:
'savename - [optional - see discussion below] File path to save the downloaded query to'

I did a search in astroquery now and I can't find any other usage of 'savename'.
I changed the name because I thought it was more widely used, but not that it's not the case I agree that directory_name seems better. I will revert the name change if you don't object.

**Comment by keflavich** [comment]
@imbasimba Thanks.  I think we should use `directory_name` when the path in question is a directory, and `savename` when it is a full file path.  @bsipocz, any thoughts on this?

**Comment by bsipocz** [comment]
@keflavich - yes, that sounds a logical distinction.
 However I think the original ``download_dir`` or something along that line would be better than ``directory_name``.

**Comment by imbasimba** [comment]
Yes, `download_dir` seems more accurate.

**Pull request merged**
