### PR TITLE
Improve generating Gaia ADQL queries

### PR DESCRIPTION
**Pull request by eerovaher**
The first commit refactors how the Gaia ADQL queries are generated but does not change the generated queries in any way. The second commit removes useless whitespace which does change the query string but does not make any functional changes.

With 3b2110f0f35ddb8631d2da367bec85fb163bc36c (current `main`):
```python
>>> from astroquery.gaia import Gaia
>>> print(Gaia.cone_search("Vega", radius="0.001deg", columns=["ra", "dec"]).parameters["query"])

                SELECT
                  TOP 50
                  ra,dec,
                  DISTANCE(
                    POINT('ICRS', ra, dec),
                    POINT('ICRS', 279.23473985606415, 38.78369481779005)
                  ) AS dist
                FROM
                  gaiadr3.gaia_source
                WHERE
                  1 = CONTAINS(
                    POINT('ICRS', ra, dec),
                    CIRCLE('ICRS', 279.23473985606415, 38.78369481779005, 0.001)
                  )
                ORDER BY
                  dist ASC
     
```

With b5bb8f0c13d34dfc1f5a74ffd68d2c8310593af0 (this pull request):
```python
>>> from astroquery.gaia import Gaia
>>> print(Gaia.cone_search("Vega", radius="0.001deg", columns=["ra", "dec"]).parameters["query"])
SELECT
  TOP 50
  ra,dec,
  DISTANCE(
    POINT('ICRS', ra, dec),
    POINT('ICRS', 279.23473985606415, 38.78369481779005)
  ) AS dist
FROM
  gaiadr3.gaia_source
WHERE
  1 = CONTAINS(
    POINT('ICRS', ra, dec),
    CIRCLE('ICRS', 279.23473985606415, 38.78369481779005, 0.001)
  )
ORDER BY
  dist ASC
```

For reviewing the code changes it might be helpful to see a version of the diff that does not highlight lines where the only change was in indentation: https://github.com/astropy/astroquery/pull/2831/files?w=1

### CODE REVIEW

**Comment by bsipocz** [comment]
> be registered as [code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) so that GitHub would notify them automatically.

@eerovaher - we do not do code owners here, so please refrain from making such suggestions.

**Comment by eerovaher** [comment]
If you don't set up code owners to notify relevant people automatically then a maintainer needs to do it manually. So why wouldn't you want to set up code owners?

**Comment by keflavich** [comment]
@eerovaher Thanks for the code style change suggestions here.  Because @esdc-esac-esa-int is maintaining this module, though, we prefer to let them decide on relatively minor code style choices like those made here.  @esdc-esac-esa-int and @jespinosaar, please do let us know if and where this sort of style recommendation is best made.

Regarding code owners, and other github features, we are not generally adopting all of the latest features, and this one is not appropriate for astroquery anyway - permissions within astropy are handled at the organization level, and we're only adding write permissions when necessary.

For now, I'm going to close this PR, but we can reopen if @esdc-esac-esa-int request it.

**Comment by eerovaher** [comment]
It didn't occur to me that code owners must have write access until @keflavich mentioned it. Now that I've learned this fact it is indeed simple to understand why `astroquery` doesn't want to use that feature.

**Comment by jespinosaar** [comment]
Hi all,

Please let me contact Gaia team to check this. Thanks for putting esdc account in copy!

**Pull request closed without merging**
