### PR TITLE
astroquery.mast bugfix(es)

### PR DESCRIPTION
**Pull request by ceb8**
This PR includes three things:
- Fixed a bug affecting TESS Input Catalog and Disk Detective Catalog criteria searches. 
  Information about which columns should be treated as numeric and which as discrete when building criteria filtersets for the catalog criteria queries was missing.  This PR corrects this problem.
- Updated the astroquery.mast remote tests to be more robust against expected database changes.
- Added information about choosing calibration vs science observations to the documentation.

### CODE REVIEW

**Comment by bsipocz** [comment]
Test failure is unrelated and I'm fixing it upstream. Will rebase this once the fix is done.

**Comment by ceb8** [comment]
@bsipocz Is the upstream issue ongoing or will rebasing fix the problem now?

**Comment by bsipocz** [comment]
@ceb8 - Indeed, it has been already been fixed. I've restarted travis, however with a rebase we could play it even safer.

**Comment by bsipocz** [comment]
Thanks @ceb8!

**Pull request merged**
