### PR TITLE
Update HITRAN module to use class-based query API

### LINKED ISSUE #824: HITRAN to use class based API
HITRAN was added recently in #617, but it doesn't follow the common class based API. 

It would be nice to get it revised, so we can deprecate some functionality from ``utils.commons``. Also if possible, it would be nice to add more, preferably remote tests, too.

cc @keflavich and @migueldvb, the original authors of the module

### PR DESCRIPTION
**Pull request by migueldvb**
This modifies the HITRAN module to follow the common class based API specification. It does not
support yet any output format description apart from the the 160-byte fixed-width format used in HITRAN 2004. I think that support for user-defined formats could be added in a different PR.

fixes #824

### CODE REVIEW

**Comment by migueldvb** [comment]
I forgot to add the Changelog file to the PR. I think everything should be there now.

**Comment by keflavich** [comment]
Awesome, looks good.  I gave it a once-over and approve, but I should read more carefully before giving official approval.

**Comment by keflavich** [comment]
It looks like there's one legit failure, hitran seems not to be indexed:
https://travis-ci.org/astropy/astroquery/jobs/337249515#L2012

This issue: https://travis-ci.org/astropy/astroquery/jobs/337249517 is probably not real, but some sort of travis configuration issue.

**Comment by migueldvb** [comment]
oh yes, I'll fix the linking of astroquery.hitran in the docs and see if this solves the failure.

**Comment by bsipocz** [comment]
@migueldvb - There is a minor conflict, would you mind to rebase?

**Comment by migueldvb** [comment]
I rebased this branch. Hopefully all the CI checks will pass after the rebase!

**Comment by migueldvb** [comment]
Sorry that I missed fixing this for 0.3.8. This is now rebased on master.

**Pull request merged**
