### PR TITLE
NIST: Fetch statistical weight (g) from NIST ASD

### PR DESCRIPTION
**Pull request by mimurrayy**
This PR makes the NIST module fetch the optional parameter g, which is currently not done. 
The current NIST tests only check certain parts of the response table and should not be affected by the additional parameter.

Related issue: #2953

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
The result table in the doc has changed with this PR, so I'll push a commit to fix it and then go ahead with the merge.

Thanks @mimurrayy!

**Comment by mimurrayy** [comment]
Ah! I was just trying to figure out why the docs were failing. Thanks @bsipocz !

**Review by keflavich — APPROVED** [review]
Assuming we have tests in place that are passing (I hope we do...), this lgtm.

**Comment by bsipocz** [comment]
RTD failure is unrelated (and I'm not exactly sure why it started to show now), so I go ahead and merge this. 

(the remote/server reaching tests are turned off by default, you can run them with e.g. `pytest -P nist -R`)

Thanks again!

**Pull request merged**
