### PR TITLE
Sha quickfix

### LINKED ISSUE #884: Problems with sha
I'm trying to use the astroquery.sha module and unfortunately, I get the following error:

    >>> from astroquery import sha
    /Users/crawford/anaconda/envs/pyjedi/lib/python3.5/site-packages/astroquery/sha/__init__.py:14:   UserWarning: Experimental: SHA has not yet been refactored to have its API match the rest of astroquery.
    warnings.warn("Experimental: SHA has not yet been refactored to have its "
    >>> pos_t2 = sha.query(ra=163.6136, dec=-11.784, size=0.5)
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/Users/crawford/anaconda/envs/pyjedi/lib/python3.5/site-packages/astroquery/sha/core.py", line 144, in query
       dtypes = _map_dtypes(type_names, field_widths)
     File "/Users/crawford/anaconda/envs/pyjedi/lib/python3.5/site-packages/astroquery/sha/core.py", line 265, in _map_dtypes
       raise ValueError('Unexpected type name: {0}.'.format(name))
    ValueError: Unexpected type name: reqkey.
    >>> import astroquery
    >>> astroquery.__version__
    '0.3.5'
    >>> import astropy
    >>> astropy.__version__
    '1.3.2' 

I've tried this in python 3.6 and python 2.7, and both return the same error.   

It would appear the error is being generated due to an extra initial line  being returned in results from the spitzers heritage archive then what the code is expecting.   

I just wanted to check whether this was a known problem or if this was something unique to me  prior to submitting a pull request to fix it.    Strangely, if I run the tests for this package, it passes without an error even though the command above is the same being used in the

### PR DESCRIPTION
**Pull request by crawfordsm**
This is a fix due to updates in the Spitzer Heritage Archive outputs, which appear to have updated.  I've update the code and the example files and this closes #884.

I've also updated the docs to use `SkyCoords` rather than `FK5`, as there seems to be a difference in how those `transform_to` works.  See https://github.com/astropy/astropy/issues/5949 for more details.

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @crawfordsm.

**Comment by keflavich** [comment]
@crawfordsm any chance you could add a remote test for this?

**Comment by crawfordsm** [comment]
If it is just a matter of making one of the calls actually download a set of data from the archive, I could probably do that.  If it is anything more complex then that, I probably won't have the time right now.

**Comment by bsipocz** [comment]
@crawfordsm - Downloading something and comparing to the canned version sounds about right. Anything more comprehensive ones can be done later when addressing #595

**Pull request merged**
