### PR TITLE
Refactor get_password with a common method on QueryWithLogin

### PR DESCRIPTION
**Pull request by saimn**
Following  #1198.

### CODE REVIEW

**Comment by saimn** [comment]
ping :raised_hands:

**Comment by keflavich** [comment]
We have a failure after the merge:
https://travis-ci.org/astropy/astroquery/jobs/424141415
Apparently there's a dependency conflict on python 3.4?  Is this a temporary conda thing?

**Comment by saimn** [comment]
I saw the same error on my other PR, so not related to the merge. It seems related to the recent release of secretstorage 3.1.0 (https://github.com/jaraco/keyring/issues/338#issuecomment-417955630) but I don't understand the error. It looks like keyring is installed with conda, so probably a dependency issue.

**Comment by bsipocz** [comment]
Weird, the keyring version installed is quite old for that version.

**Comment by bsipocz** [comment]
OK, so the failing build is using the same keyring as it used before. Also secretstorage is still around, but as of 3 days ago, it has a new release. I've just restarted the failing build. If it still fails, we may need to pin the secretstorage version to the one everything worked well before.

**Comment by bsipocz** [comment]
OK, so the issue has been fixed directly in master.

**Pull request merged**
