### PR TITLE
Refactor: Make kwargs keyword only 

### PR DESCRIPTION
**Pull request by nkphysics**
This addresses #1746.

At the present time of drafting this PR, refactors to make optional kwargs keyword only have been applied to the following:

- [x] astroquery/alfalfa
- [x] astroquery/astrometry_net
- [x] astroquery/besancon
- [x] astroquery/casda
- [x] astroquery/cds
- [x] astroquery/dace
- [x] astroquery/exoplanet_orbit_database
- [x] astroquery/fermi
- [x]  astroquery/gaia
- [x]  astroquery/gama
- [x] astroquery/gemini
- [x] astroquery/hips2fits
- [x] astroquery/hitran
- [x] astroquery/image_cutouts/first
- [x] astroquery/imcce  (also added  `# doctest: +IGNORE_OUTPUT` for re-emerging issue from #2634 that was addressed in #2652 )
- [x] astroquery/ipac/irsa/ibe
- [x] astroquery/ipac/irsa/irsa_dust
- [x] astroquery/ipac/irsa/sha
- [x] astroquery/ipac/ned
- [x] astroquery/jplsbdb
- [x] astroquery/jplspec
- [x] astroquery/lamda
- [x] astroquery/linelists/cdms
- [x] astroquery/magpis
- [x] astroquery/mpc
- [x] astroquery/nasa_ads
- [x] astroquery/oac
- [x] astroquery/ogle
- [x] astroquery/open_exoplanet_catalogue
- [x] astroquery/splatalogue
- [x] astroquery/template_module
- [x] astroquery/ukidss
- [x] astroquery/vsa
- [x]  astroquery/wfau (FYI: has no tests)
- [x] astroquery/xmatch

Problematic refactors (handle later/ require more scrutiny):
- [ ] astroquery/heasarc (has a few failing tests)
- [ ] astroquery/utls (breaks other packages to the point where all tests should run to make sure everything is working)
- [ ] astroquery/eso (test_each_instrument_SgrAstar is failing)
- [ ] astroquery/cosmosim (has no tests)
- [ ] astroquery/cadc
- [ ] astroquery/utils/tap
- [ ] astroquery/vamdc
- [ ] astroquery/vo_conesearch

### CODE REVIEW

**Comment by nkphysics** [comment]
Would you'll prefer one large PR for this refactoring, or grouping up the refactors into 2-3 smaller PRs to make reviewing a bit easier?

**Comment by bsipocz** [comment]
One big PR is great, thanks!

**Comment by nkphysics** [comment]
CI-devtest failures seem to be no associated with these refactors (https://github.com/astropy/astroquery/actions/runs/4160273194) so I'm just going to proceed with the refactors.

It seems to be a bigger issue with rust compilation in deps.

**Comment by bsipocz** [comment]
> Problematic refactors (need help/feedback, or handle later)

Perfectly fine to leave anything non-trivial for later.

**Comment by nkphysics** [comment]
> > Problematic refactors (need help/feedback, or handle later)
> 
> Perfectly fine to leave anything non-trivial for later.

If you want I'll resolve the conflicts with gaia and then mark this ready for review, and just tackle the problematic refactors on an individual basis.

**Comment by bsipocz** [comment]
Sounds good. I've also looked into the diff, and if there is any way to revert and squash all the changes that black did to formatting, it would be awesome. 

There are quite a lot of places where it expanded 3 lines into 20 without adding anything to it.

**Comment by nkphysics** [comment]
> Sounds good. I've also looked into the diff, and if there is any way to revert and squash all the changes that black did to formatting, it would be awesome.
> 
> There are quite a lot of places where it expanded 3 lines into 20 without adding anything to it, and that's the cause of bloating up the diff to the order of hundreds of lines.
> 
> As I see most of the commits are fine, and you did it very modularly, so it's also fine to cherry pick the affected ones ou from this branch, etc.

I'll work on cleaning it up.

**Comment by nkphysics** [comment]
Cleaned this up as best as I could.

**Comment by bsipocz** [comment]
> Cleaned this up as best as I could.

Thanks! The ibe module is the only one left out (4 files), and it will need a rebase given the 2 unrelated commit from `main` got merged in. However, I'm happy to do the rebase once this is ready to go, once the remote test run finishes (I want to make sure there are no new failures introduced.)

Also, these changes will need a changelog, but I'm thinking about having one changelog that covers all the modules, so we'll just do that before the release listing all the PRs going these kind of changes.

**Comment by nkphysics** [comment]
> > Cleaned this up as best as I could.
> 
> Thanks! The ibe module is the only one left out (4 files), and it will need a rebase given the 2 unrelated commit from `main` got merged in. However, I'm happy to do the rebase once this is ready to go, once the remote test run finishes (I want to make sure there are no new failures introduced.)
> 
> Also, these changes will need a changelog, but I'm thinking about having one changelog that covers all the modules, so we'll just do that before the release listing all the PRs going these kind of changes.

Ibe is cleaned up, I'll leave the changelog and rebasing up to you.

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Thanks @nkphysics!

**Pull request merged**
