### PR TITLE
Issue astropy/astroquery#1722: Turn off verbose Tap Plus messages

### PR DESCRIPTION
**Pull request by jpl-jengelke**
Turn off verbose Tap Plus instantiation messages in Gaia class constructor.

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @jpl-jengelke!

Strictly speaking, changing the default behaviour requires a changelog entry. Also, I'm not sure it's right to change the default (but it's certainly an improvement to be able to control the verbosity)

**Comment by jpl-jengelke** [comment]
Note: This is a solution for #1722, not the earlier referenced ticket (missing leading '1').

**Comment by jpl-jengelke** [comment]
@bsipocz A line has been added to the changelog referencing this fix, and some explanation of the verbosity change was added in a comment in #1722.

**Review by keflavich — APPROVED** [review]

**Comment by bsipocz** [comment]
Thanks @jpl-jengelke!

**Pull request merged**
