### PR TITLE
Adding build with numpy pre-release to the travis matrix

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by keflavich** [comment]
:+1:.  I need to figure out how to tune coveralls to ignore changes like this.

**Comment by bsipocz** [comment]
@keflavich - yes, that's on my list as well for a while,  so let me know if you figure it out :)

**Comment by astrofrog** [comment]
@keflavich @bsipocz - you need to set the threshold for failure to e.g. 0.1% here:

screen shot 2016-03-02 at 6 20 37 pm

**Comment by keflavich** [comment]
Thanks @astrofrog! I'd never located the settings part before; it's good to know what to look for.

@bsipocz I set it to 0.01% now

**Comment by bsipocz** [comment]
@astrofrog - Thanks, one mystery solved for today then :)
@keflavich - Could you please change the threshold? I can't see any of the repos when logging in coveralls.

**Pull request merged**
