### PR TITLE
Added cusom ADQL and TAP+ functionality to ESASky module

### PR DESCRIPTION
**Pull request by imbasimba**

### CODE REVIEW

**Comment by bsipocz** [comment]
@imbasimba - is there any chance to use pyvo.tap instead of tap+ from here? Do you use any of the features in tap+ that is not yet available there? For the long term, we would like to move all modules to use the former, so if any new usage could already do that it would be great.

**Comment by imbasimba** [comment]
Hmm... I guessing the tap+ features won't be heavily used in this module, so pyvo.tap is probably an option. Is there any plan for pyvo.tap to eventually support the full tap+ feature set?

**Comment by bsipocz** [comment]
There were discussions about to port over whatever is missing and deprecate the usage, ~2 years ago at the Paris IVOA. Understandably it's not a quick and trivial port, so while it would be great to get there we would not push an ETA for it, but ask whether the current pyvo.tap is suitable when a new module/functionality tries to rely on tap+. 

 I'm not exactly up to date with recent plans around pyvo, but would cc the maintainers @tomdonaldson, @andamian @jcsegovia and @cbanek.

**Comment by imbasimba** [comment]
I’d rather continue to use the TAP+ class because the ESASky TAP supports all TAP+ features and the other ESA modules use it. Whenever the other ESA modules deem pyvo.tap to be sufficient, I can make a new PR.

**Comment by tomdonaldson** [comment]
@imbasimba This approach seems reasonable for now.  I don't know that we have a timetable for TAP+ deprecation, but to get past needing to maintain two implementations, the goal certainly is to ensure that `pyvo` is ready to perform all the same functionality as TAP+ so that the transition is as smooth as possible.  To that end, are there specific features missing now that are important to you, or is it more of a desire to stay in sync with other ESA modules?

**Comment by imbasimba** [comment]
@tomdonaldson I have not looked into the TAP+ feature set too much, so I am not sure what's potentially missing in pyvo.tap. The ESASky TAP is basically using the same TAP+ server software as the rest of the ESA archives, so any missing functionality is probably the same as for the other ESA archives.

The safe bet for now is to stay in sync with the other ESA modules and later migrate to pyvo.

**Comment by bsipocz** [comment]
OK, then leave the pyvo/TAP+ questions for the future. But in the long term, it would really be awesome to converge into one implementation that has everything, and that lives in pyvo rather than astroquery.

**Comment by andamian** [comment]
> @tomdonaldson I have not looked into the TAP+ feature set too much, so I am not sure what's potentially missing in pyvo.tap. The ESASky TAP is basically using the same TAP+ server software as the rest of the ESA archives, so any missing functionality is probably the same as for the other ESA archives.
> 
> The safe bet for now is to stay in sync with the other ESA modules and later migrate to pyvo.

Last time we've checked, the table upload feature was missing (and maybe some A&A), but that's not part of the standard either (hence the + in the TAP+). I don't know if you are using it or not for the ESASky module, but if we have a case we can lobby for it to be included in the standard and get supported in `pyvo`.

**Comment by bsipocz** [comment]
I know that VO is not exactly grassroot, but I naively think that having an implementation in pyvo, that those who already need the functionality are happy with, it would be a great push to get that included in the standard. At least it looks so much better than the alternative of having the two implementations for all the rest of the functionalities until an agreement is reached outside of pyvo/astroquery.

**Comment by andamian** [comment]
> I know that VO is not exactly grassroot, but I naively think that having an implementation in pyvo, that those who already need the functionality are happy with, it would be a great push to get that included in the standard. At least it looks so much better than the alternative of having the two implementations for all the rest of the functionalities until an agreement is reached outside of pyvo/astroquery.

Agree 100%. We've discussed using it as a platform for proposing new features in the standards.

**Comment by imbasimba** [comment]
Following the May 2021 IVOA interop, it seems inevitable that ESA will do the TapPlus to pyvo migration in the near future. I'll migrate this module to pyvo as soon as that is done.

For now, let me know if you have any review comments. (I suggest letting the slight fall in test coverage through this time, as I have a follow up PR with new features and more tests coming later this week)

**Review by bsipocz — CHANGES_REQUESTED** [review]
Overall this looks good, however #2078 is so close to being merged that I doubt it worth the complication of wrapping this PR up separately.

The missing pieces here: changelog, tests and documentation. The latter two of those should be added to #2078, too to cover this new functionality.

**Comment by bsipocz** [comment]
This has been included in #2078, so I'm closing the PR without merging.

**Pull request closed without merging**
