### PR TITLE
Adding EBHIS to the reference data file

### PR DESCRIPTION
**Pull request by bsipocz**
This should fix the failing remote test of skyview, except that somehow locally it started to produce the old list.
@keflavich - Please check whether it works for you.

### CODE REVIEW

**Comment by keflavich** [comment]
@bsipocz I'm still getting a failure in the same spot

**Comment by bsipocz** [comment]
same failure?

**Comment by keflavich** [comment]
afaict, yes:
```
>       assert SkyView.survey_dict == survey_dict
E       assert {'DiffuseX-ra...x', ...], ...} == {'DiffuseX-ray...x', ...],
...}
E         Detailed information truncated, use "-vv" to show
```

On Fri, Mar 25, 2016 at 9:26 AM, Brigitta Sipocz <notifications@github.com>
wrote:

> same failure?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/astropy/astroquery/pull/667#issuecomment-201350009>
>



-- 
Adam

**Comment by bsipocz** [comment]
@keflavich - This is weird. Temporary I've switched on remote testing on one of the travis builds, and skyview seems to get fixed and now passes. I really have no idea why the local testing mess up for both of us.

Check out this travis build https://travis-ci.org/astropy/astroquery/jobs/118533736

**Comment by keflavich** [comment]
This is wacky.... I think the failures change each time?

True SoftX-ray
True GOODS/HDF/CDF(Allwavebands)
True Optical:DSS
True UV
True WMAP/COBE
True Optical:SDSS
True IRAS
False overlay_red
True GammaRay
True Planck
False overlay_blue
True InfraredHighRes
True SwiftBAT
True OtherOptical
False overlay_green
False Radio
True HardX-ray
True DiffuseX-ray
Canned reference return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'EBHIS', 'nH', 'SUMSS 843 MHz', '0408MHz',
'WENSS', 'CO', 'VLSSr', '0035MHz']
online service return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'nH', 'SUMSS 843 MHz', '0408MHz', 'WENSS',
'CO', 'VLSSr', '0035MHz']


False overlay_green
True IRAS
True SwiftBAT
True OtherOptical
True Optical:DSS
True WMAP/COBE
True InfraredHighRes
True UV
True Optical:SDSS
True DiffuseX-ray
True Planck
True GammaRay
True SoftX-ray
True HardX-ray
False overlay_blue
True GOODS/HDF/CDF(Allwavebands)
False overlay_red
False Radio
Canned reference return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'EBHIS', 'nH', 'SUMSS 843 MHz', '0408MHz',
'WENSS', 'CO', 'VLSSr', '0035MHz']
online service return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'nH', 'SUMSS 843 MHz', '0408MHz', 'WENSS',
'CO', 'VLSSr', '0035MHz']



True GOODS/HDF/CDF(Allwavebands)
True UV
True OtherOptical
True InfraredHighRes
True SwiftBAT
True Optical:SDSS
False overlay_green
True WMAP/COBE
False Radio
True GammaRay
True SoftX-ray
True Planck
True DiffuseX-ray
True HardX-ray
False overlay_blue
True Optical:DSS
True IRAS
False overlay_red
Canned reference return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'EBHIS', 'nH', 'SUMSS 843 MHz', '0408MHz',
'WENSS', 'CO', 'VLSSr', '0035MHz']
online service return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'nH', 'SUMSS 843 MHz', '0408MHz', 'WENSS',
'CO', 'VLSSr', '0035MHz']



True SoftX-ray
True GOODS/HDF/CDF(Allwavebands)
True InfraredHighRes
False overlay_green
True Planck
False Radio
False overlay_red
True WMAP/COBE
True GammaRay
True UV
True IRAS
True OtherOptical
False overlay_blue
True Optical:DSS
True SwiftBAT
True HardX-ray
True DiffuseX-ray
True Optical:SDSS
Canned reference return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'EBHIS', 'nH', 'SUMSS 843 MHz', '0408MHz',
'WENSS', 'CO', 'VLSSr', '0035MHz']
online service return ['GB6 (4850MHz)', 'VLA FIRST (1.4 GHz)', 'NVSS',
'Stripe82VLA', '1420MHz (Bonn)', 'nH', 'SUMSS 843 MHz', '0408MHz', 'WENSS',
'CO', 'VLSSr', '0035MHz']

On Fri, Mar 25, 2016 at 12:01 PM, Brigitta Sipocz <notifications@github.com>
wrote:

> @keflavich <https://github.com/keflavich> - This is weird. Temporary I've
> switched on remote testing on one of the travis builds, and skyview seems
> to get fixed and now passes. I really have no idea why the local testing
> mess up for both of us.
>
> Check out this travis build
> https://travis-ci.org/astropy/astroquery/jobs/118533736
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/astropy/astroquery/pull/667#issuecomment-201429089>
>



-- 
Adam

**Comment by bsipocz** [comment]
@keflavich - I'm just merging this for now.

**Pull request merged**
