### PR TITLE
Use HTTPS for vao.stsci.edu

### PR DESCRIPTION
**Pull request by pllim**
- [x] Resolve 404 error for `tstQuery` URL.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]

**Comment by pllim** [comment]
Update: @theresadower is still looking into `tstQuery` returning 404

**Comment by theresadower** [comment]
I've updated the called TAP service to not require the change to https. I do recommend using https anyway: we have had recurring issues with IT policy and firewalls mistakenly deciding TAP queries over http (not s) are SQL injection attacks, and using https also works around that issue.

Still looking into the 404.

**Comment by theresadower** [comment]
404 should be fixed with a configuration change to re-allow longer query strings (GET and POST). I've tested the query below, can you retest this with your client in case there are additional URL encoding/decoding errors? 

Thanks and apologies!

https://vao.stsci.edu/regtap/tapservice.aspx/sync?lang=adql&query=select%20detail_xpath,%20detail_value%20from%20rr.res_detail%20where%20ivoid%20=%20%22ivo://archive.stsci.edu/gsc/gsc2.3%22%20and%20cap_index=1%20and%20detail_xpath%20in%20(%22/capability/testQuery/ra%22,%20%22/capability/testQuery/dec%22,%20%22/capability/testQuery/sr%22

**Comment by pllim** [comment]
Thank you, @theresadower ! I can confirm that 404 is now gone.

@bsipocz , do I need a change log for this?

**Comment by bsipocz** [comment]
We put in changelog entries when a whole module is switched to https, but mostly because as we did the switch when we already run into some user-reported issues caused by http. So I'm OK either way, if you expect this to be totally transparent to users I would say you don't need to put it on.

**Comment by pllim** [comment]
> if you expect this to be totally transparent to users

Yes, this is just on the server side validation. User should not see anything different.

**Comment by pllim** [comment]
Thanks, everyone!

**Pull request merged**
