### PR TITLE
Conesearch validator to use new TAP registry service

### LINKED ISSUE #1070: ENH: Use newer STScI VAO registry for Cone Search validation
The current VAO registry, `http://vao.stsci.edu/directory/NVORegInt.asmx/VOTCapabilityPredOpt?...` in `astroquery.vo_conesearch.validator.conf.conesearch_master_list` can be finicky and return empty VO table. Its developer says this is actually a "legacy" service now. Hence, I need to investigate if their newer RegTAP service is viable as an alternative.

### PR DESCRIPTION
**Pull request by pllim**
Fix #1070 

This produces non backward compatible metadata but should not affect typical cone search query.

@adamginsburg , I am not convinced that a warning is necessary, as AFAIK I am the only one who uses the validator portion. What do you think after looking at the changes?

Local test results for `python setup.py test -P vo_conesearch --remote-data`:
```
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0

Running tests with astroquery version 0.3.8.dev4518.
Running tests in astroquery/vo_conesearch docs/vo_conesearch.

Date: 2018-04-25T16:10:34

Platform: Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo

Executable: .../anaconda/envs/py36/bin/python

Full Python Version: 
3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 17:14:46) 
[GCC 7.2.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.14.2
Matplotlib: 2.1.1
Pandas: 0.20.3
Astropy: 3.1.dev21789
APLpy: not available
pyregion: not available
Using Astropy options: remote_data: any.

rootdir: /tmp/astroquery-test-dn9x067b/lib/python3.6/site-packages, inifile: setup.cfg
plugins: xdist-1.17.1, remotedata-0.2.0, openfiles-0.2.0, mpl-0.8, flake8-0.8.1, doctestplus-0.1.2, arraydiff-0.1
collected 49 items                                                              

astroquery/vo_conesearch/tests/test_conesearch.py ......x..........x....
astroquery/vo_conesearch/tests/test_vos_catalog.py ...............
astroquery/vo_conesearch/validator/tests/test_inpect.py ....
astroquery/vo_conesearch/validator/tests/test_validate.py .....
docs/vo_conesearch/client.rst .
docs/vo_conesearch/validator.rst .
docs/vo_conesearch/vo_conesearch.rst .

==================== 47 passed, 2 xfailed in 37.47 seconds =====================
```

TODO
- [x] Decision on whether to emit warning to user. Answer: No need.
- [x] Add change log.
- [x] Update documentation.
- [x] Squash commits.

Server side
- [x] Update data at https://astropy.stsci.edu/aux/vo_databases/

### CODE REVIEW

**Comment by keflavich** [comment]
Which warning are you referring to?  I don't know this code well enough to make a judgement on whether it is needed or not, though - please make a call, and we'll respect it.

**Comment by pllim** [comment]
@bsipocz or @keflavich , this should be ready for merge. I am already using it on server side. There are some minor stuff that I don't have time to look into right now, so I'll open up a follow-up issue shortly.

**Comment by bsipocz** [comment]
@pllim - I'm holding this back till next week and would use this as a guinea pig for testing the continuous delivery if you don't mind ;)

**Comment by bsipocz** [comment]
@pllim - Would there be a way to track usage on the serverside? Some modules use astroquery specific user agents, so in theory they can have some idea about usage.

**Comment by pllim** [comment]
> Would there be a way to track usage on the serverside?

Good question. I'll have to check with my colleagues. :+1:

**Comment by pllim** [comment]
> Some modules use astroquery specific user agents

@bsipocz , I am not sure exactly what this means. Can you please elaborate?

**Comment by keflavich** [comment]
The HTTP requests from astroquery should have the `User-Agent` field in the HTTP headers set:
https://github.com/astropy/astroquery/blob/master/astroquery/utils/commons.py#L81

**Pull request merged**
