### PR TITLE
hips2fits remove imshow calls from remote tests

### PR DESCRIPTION
**Pull request by bmatthieu3**
This refers #1734 

@bsipocz @keflavich - I commented the call to matplotlib functions in the remote tests of hips2fits

### CODE REVIEW

**Comment by bsipocz** [comment]
I've rebased to 
- get rid of the astropy-helpers changes
- pick up the CI
- fix the docs warnings.

It can now be merged

**Comment by bsipocz** [comment]
Except I cannot push it back to this branch. @bmatthieu3 - please enable the edit by maintainer checkbox on the right-hand side.

**Comment by bmatthieu3** [comment]
@bsipocz - This checkbox does not appear for me and it seems it is because the forked astroquery repo we have lies in an organization (cds-astro) rather than in a specific user. https://github.com/isaacs/github/issues/1681

I added you as a maintainer of our forked repo: https://github.com/cds-astro/astroquery
Tell me if it works after that.

**Comment by keflavich** [comment]
This can be merged after a rebase, I think, but not til then.

**Review by bsipocz — APPROVED** [review]

**Pull request merged**
