### PR TITLE
Sdss documentaion cleanup

### PR DESCRIPTION
**Pull request by tinumide**

### CODE REVIEW

**Review by ceb8 — APPROVED** [review]

**Comment by bsipocz** [comment]
I've rebased this but see remote data failures with the docs, so changed I changed the status back to draft.

**Review by ceb8 — APPROVED** [review]
Rebased, and confirmed that tests pass when remote-data is allowed.

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
I see an SDSS remote test failure, but that is totally unrelated to this PR, so I go ahead and merge it. Thank you @tinumide and @ceb8!

**Comment by ceb8** [comment]
@bsipocz Yeah, I didn't fix that. I'm planning a go through of the remotes tests to collect failures and fix/make issues when I've finished getting these docs PRs through.

**Comment by bsipocz** [comment]
Yeah, no worries we have plenty of them still (sadly), I suppose it's time to update #2203 with the current status.

**Pull request merged**
