### PR TITLE
Alfalfa documentation clean up

### PR DESCRIPTION
**Pull request by tinumide**
For some reason querying spectrum` Alfalfa.get_spectrum(agc) ` times out. I'm yet to figure out why so I just commented out that part of the doc for now.

### CODE REVIEW

**Comment by bsipocz** [comment]
@keflavich - please do a review if you're OK with getting rid of the iterator approach to work around the byte/str issues.

**Review by keflavich — APPROVED** [review]
lgtm, but let's hold off merging this for a few days while I wait for a reply on whether this service is still active at all

**Comment by bsipocz** [comment]
@keflavich - did they get back to you?

**Comment by keflavich** [comment]
No, no reply.  I think we need to add a deprecation tag to this whole module - it looks like the server that hosted the data is down and no mirror has been made.  I guess we can merge this PR but open a new issue that this module connects to a remote service that is presently unavailable.   I'd like the formal confirmation that it's never coming back before we delete the module, though.

**Pull request merged**
