### PR TITLE
TST: Attempt to fix segfault with pytest 4

### PR DESCRIPTION
**Pull request by pllim**
Attempt to fix segfault as seen in https://travis-ci.org/astropy/astroquery/jobs/463068109 , as suggested by @astrofrog . Also see astropy/package-template#373 .

p.s. It might be better to update a bunch of other files to be consistent with latest template, but that is not the scope of this PR.

### CODE REVIEW

**Comment by pllim** [comment]
Tests passed. Do you want me to remove `pytest-faulthandler` dependency? Also not sure if `test.__test__` really helped; should I remove that or keep that in?

**Comment by keflavich** [comment]
Up to you, I don't know what those are.

**Comment by pllim** [comment]
@astrofrog , why is the bot suddenly complain about change log?

**Comment by bsipocz** [comment]
Magic, pure magic. Thank you @pllim!

**Pull request merged**
