### PR TITLE
Fixes and updates to the ALMA finder chart maker

### PR DESCRIPTION
**Pull request by keflavich**
(this relies on unmerged bugfixes)

The ALMA archive stopped serving up a complete list of individual footprints.
Instead, they now have an approximate amalgamated footprint box included in
each row of the HTML table, but *not* in their votables or CSVs.  I therefore
had to implement an entirely new reader and parser.

### CODE REVIEW

**Comment by keflavich** [comment]
Except for some continued server failures that are not generally reproducible, this PR is done and passes locally.  The failures that may come up are:
```
E               ValueError: The query validation failed for unknown reasons.  Try again?
```
and
```
E           requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://almascience.nrao.edu/dataPortal/requests/anonymous/954703801/ALMA/2011.0.00121.S_2012-08-16_002_of_002.tar/2011.0.00121.S_2012-08-16_002_of_002.tar
```

which, afaict, are flaky server issues, so I'm going to merge this.

**Comment by bsipocz** [comment]
@keflavich - Do you want to make pandas a dependency, wouldn't be astropy.table sufficient?

**Comment by keflavich** [comment]
No, I don't want to make pandas a dependency, but I couldn't get astropy.table to parse these files correctly.  If I recall, it was a problem where astropy refused to ingest unicode and/or ignored quotation pairs, but pandas worked just fine.  Really I should have made this an upstream astropy bug but I didn't have time.

**Comment by bsipocz** [comment]
OK, I see now. That case I suggest to open issues in astropy, and a reminder one here that once it's solved upstream remove pandas. 
In the meantime I'll fix the tests that they are skipped when there is no pandas installed.

**Comment by bsipocz** [comment]
OK, it looks like the usual issue with the fast reader, switching it off seems to be working (except that now I run into random pyregion deprecations, etc, that I'm not sure why I didn't see before). PR to come.

**Comment by keflavich** [comment]
:+1: thanks for cleaning up my mess

**Comment by bsipocz** [comment]
it's not your mess, but upstream, and also a side track of sorting out the pyvo deprecation we started to see just today...

**Pull request merged**
